In [1]:
import pandas as pd
import os

In [39]:
file = pd.read_csv(os.path.join("..","Data","Raw","us_wineries_2009_2019.csv"),header=None)
print(file)

                                                    0  \
0            Producing wineries in the U.S. 2009-2019
1   Total number of wineries in the United States ...
2                                                year
3                                                2009
4                                                2010
5                                                2011
6                                                2012
7                                                2013
8                                                2014
9                                                2015
10                                               2016
11                                               2017
12                                               2018
13                                               2019
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
32                                                NaN
33                                                NaN
34                                                NaN
35                                                NaN
36                                                NaN
37                                                NaN
38                                                NaN
39                                                NaN

                           1
0                        NaN
1                        NaN
2   number of wineries in US
3                      6,357
4                      6,941
5                      7,306
6                      7,396
7                      7,498
8                      7,762
9                      8,287
10                     8,702
11                     9,091
12                     9,654
13                    10,043
14                       NaN
15                       NaN
16                       NaN
17                       NaN
18                       NaN
19                       NaN
20                       NaN
21                       NaN
22                       NaN
23                       NaN
24                       NaN
25                       NaN
26                       NaN
27                       NaN
28                       NaN
29                       NaN
30                       NaN
31                       NaN
32                       NaN
33                       NaN
34                       NaN
35                       NaN
36                       NaN
37                       NaN
38                       NaN
39                       NaN

In [40]:
producing_wineries_df = pd.DataFrame(file)
producing_wineries_df

,0,1
0,Producing wineries in the U.S. 2009-2019,NaN
1,Total number of wineries in the United States ...,NaN
2,year,number of wineries in US
3,2009,"6,357"
4,2010,"6,941"
5,2011,"7,306"
6,2012,"7,396"
7,2013,"7,498"
8,2014,"7,762"
9,2015,"8,287"
10,2016,"8,702"
11,2017,"9,091"
12,2018,"9,654"
13,2019,"10,043"
14,NaN,NaN
15,NaN,NaN
16,NaN,NaN
17,NaN,NaN
18,NaN,NaN
19,NaN,NaN
20,NaN,NaN
21,NaN,NaN
22,NaN,NaN
23,NaN,NaN
24,NaN,NaN
25,NaN,NaN
26,NaN,NaN
27,NaN,NaN
28,NaN,NaN
29,NaN,NaN
30,NaN,NaN
31,NaN,NaN
32,NaN,NaN
33,NaN,NaN
34,NaN,NaN
35,NaN,NaN
36,NaN,NaN
37,NaN,NaN
38,NaN,NaN
39,NaN,NaN

In [41]:
producing_wineries_df.dropna()

       0                         1
2   year  number of wineries in US
3   2009                     6,357
4   2010                     6,941
5   2011                     7,306
6   2012                     7,396
7   2013                     7,498
8   2014                     7,762
9   2015                     8,287
10  2016                     8,702
11  2017                     9,091
12  2018                     9,654
13  2019                    10,043

In [73]:
headers = producing_wineries_df.iloc[2]
new_producing_wineries_df = pd.DataFrame(producing_wineries_df.values[3:13,:], columns=headers)
new_producing_wineries_df.set_index('year', inplace = True)
new_producing_wineries_df

2    number of wineries in US
year
2009                    6,357
2010                    6,941
2011                    7,306
2012                    7,396
2013                    7,498
2014                    7,762
2015                    8,287
2016                    8,702
2017                    9,091
2018                    9,654

In [82]:
new_producing_wineries_df.to_csv(os.path.join("..","Data","Clean","us_wineries_2009_2019_clean.csv"))

In [84]:
file_overwt = pd.read_csv(os.path.join("..","Data","Raw","US_Adults_Percent_Overweight_by_State_Year.csv"),header=0)
print(file_overwt)

                Location   2013   2014   2015   2016   2017
0          United States  0.638  0.641  0.645  0.648  0.654
1                Alabama  0.682  0.670  0.687  0.695  0.702
2                 Alaska  0.661  0.648  0.672  0.667  0.667
3                Arizona  0.618  0.640  0.653  0.632  0.648
4               Arkansas  0.699  0.706  0.695  0.682  0.705
5             California  0.601  0.597  0.604  0.610  0.609
6               Colorado  0.564  0.574  0.566  0.581  0.587
7            Connecticut  0.625  0.604  0.616  0.618  0.632
8               Delaware  0.646  0.674  0.668  0.680  0.685
9   District of Columbia  0.538  0.549  0.544  0.534  0.539
10               Florida  0.628  0.622  0.641  0.632  0.641
11               Georgia  0.657  0.657  0.655  0.658  0.653
12                Hawaii  0.554  0.581  0.570  0.576  0.588
13                 Idaho  0.649  0.657  0.652  0.645  0.659
14              Illinois  0.647  0.638  0.662  0.650  0.658
15               Indiana  0.673  0.665  0.665  0.672  0.680
16                  Iowa  0.670  0.669  0.667  0.687  0.701
17                Kansas  0.653  0.660  0.680  0.667  0.672
18              Kentucky  0.673  0.667  0.672  0.691  0.678
19             Louisiana  0.674  0.689  0.692  0.692  0.700
20                 Maine  0.648  0.645  0.665  0.652  0.651
21              Maryland  0.641  0.649  0.650  0.646  0.662
22         Massachusetts  0.580  0.589  0.597  0.602  0.614
23              Michigan  0.662  0.656  0.662  0.675  0.672
24             Minnesota  0.611  0.641  0.629  0.648  0.649
25           Mississippi  0.693  0.707  0.701  0.713  0.699
26              Missouri  0.655  0.656  0.663  0.672  0.678
27               Montana  0.614  0.630  0.610  0.627  0.622
28              Nebraska  0.655  0.667  0.670  0.685  0.690
29                Nevada  0.649  0.635  0.647  0.623  0.657
30         New Hampshire  0.618  0.636  0.636  0.635  0.649
31            New Jersey  0.628  0.631  0.634  0.638  0.626
32            New Mexico  0.627  0.649  0.645  0.649  0.652
33              New York  0.613  0.611  0.595  0.608  0.613
34        North Carolina  0.661  0.656  0.658  0.668  0.669
35          North Dakota  0.676  0.688  0.670  0.681  0.694
36                  Ohio  0.651  0.667  0.665  0.663  0.680
37              Oklahoma  0.679  0.682  0.689  0.688  0.706
38                Oregon  0.599  0.617  0.645  0.626  0.645
39          Pennsylvania  0.645  0.641  0.662  0.654  0.671
40          Rhode Island  0.646  0.624  0.627  0.637  0.649
41        South Carolina  0.665  0.670  0.662  0.674  0.681
42          South Dakota  0.670  0.652  0.645  0.669  0.677
43             Tennessee  0.684  0.671  0.687  0.686  0.683
44                 Texas  0.661  0.678  0.687  0.684  0.694
45                  Utah  0.592  0.595  0.597  0.604  0.606
46               Vermont  0.619  0.602  0.599  0.617  0.626
47              Virginia  0.640  0.647  0.641  0.655  0.663
48            Washington  0.614  0.634  0.625  0.635  0.622
49         West Virginia  0.688  0.696  0.711  0.709  0.717
50             Wisconsin  0.665  0.674  0.660  0.662  0.673
51               Wyoming  0.644  0.646  0.654  0.642  0.647
52                  Guam  0.635  0.634  0.671  0.645  0.671
53           Puerto Rico  0.666  0.659  0.670  0.665  0.683
54   U.S. Virgin Islands    NaN    NaN    NaN  0.652  0.652

In [88]:
obesity_df = pd.DataFrame(file_overwt)
obesity_df = obesity_df.fillna(value=0)
obesity_df.set_index('Location', inplace = True)
obesity_df

                       2013   2014   2015   2016   2017
Location
United States         0.638  0.641  0.645  0.648  0.654
Alabama               0.682  0.670  0.687  0.695  0.702
Alaska                0.661  0.648  0.672  0.667  0.667
Arizona               0.618  0.640  0.653  0.632  0.648
Arkansas              0.699  0.706  0.695  0.682  0.705
California            0.601  0.597  0.604  0.610  0.609
Colorado              0.564  0.574  0.566  0.581  0.587
Connecticut           0.625  0.604  0.616  0.618  0.632
Delaware              0.646  0.674  0.668  0.680  0.685
District of Columbia  0.538  0.549  0.544  0.534  0.539
Florida               0.628  0.622  0.641  0.632  0.641
Georgia               0.657  0.657  0.655  0.658  0.653
Hawaii                0.554  0.581  0.570  0.576  0.588
Idaho                 0.649  0.657  0.652  0.645  0.659
Illinois              0.647  0.638  0.662  0.650  0.658
Indiana               0.673  0.665  0.665  0.672  0.680
Iowa                  0.670  0.669  0.667  0.687  0.701
Kansas                0.653  0.660  0.680  0.667  0.672
Kentucky              0.673  0.667  0.672  0.691  0.678
Louisiana             0.674  0.689  0.692  0.692  0.700
Maine                 0.648  0.645  0.665  0.652  0.651
Maryland              0.641  0.649  0.650  0.646  0.662
Massachusetts         0.580  0.589  0.597  0.602  0.614
Michigan              0.662  0.656  0.662  0.675  0.672
Minnesota             0.611  0.641  0.629  0.648  0.649
Mississippi           0.693  0.707  0.701  0.713  0.699
Missouri              0.655  0.656  0.663  0.672  0.678
Montana               0.614  0.630  0.610  0.627  0.622
Nebraska              0.655  0.667  0.670  0.685  0.690
Nevada                0.649  0.635  0.647  0.623  0.657
New Hampshire         0.618  0.636  0.636  0.635  0.649
New Jersey            0.628  0.631  0.634  0.638  0.626
New Mexico            0.627  0.649  0.645  0.649  0.652
New York              0.613  0.611  0.595  0.608  0.613
North Carolina        0.661  0.656  0.658  0.668  0.669
North Dakota          0.676  0.688  0.670  0.681  0.694
Ohio                  0.651  0.667  0.665  0.663  0.680
Oklahoma              0.679  0.682  0.689  0.688  0.706
Oregon                0.599  0.617  0.645  0.626  0.645
Pennsylvania          0.645  0.641  0.662  0.654  0.671
Rhode Island          0.646  0.624  0.627  0.637  0.649
South Carolina        0.665  0.670  0.662  0.674  0.681
South Dakota          0.670  0.652  0.645  0.669  0.677
Tennessee             0.684  0.671  0.687  0.686  0.683
Texas                 0.661  0.678  0.687  0.684  0.694
Utah                  0.592  0.595  0.597  0.604  0.606
Vermont               0.619  0.602  0.599  0.617  0.626
Virginia              0.640  0.647  0.641  0.655  0.663
Washington            0.614  0.634  0.625  0.635  0.622
West Virginia         0.688  0.696  0.711  0.709  0.717
Wisconsin             0.665  0.674  0.660  0.662  0.673
Wyoming               0.644  0.646  0.654  0.642  0.647
Guam                  0.635  0.634  0.671  0.645  0.671
Puerto Rico           0.666  0.659  0.670  0.665  0.683
U.S. Virgin Islands   0.000  0.000  0.000  0.652  0.652

In [93]:
obesity_df.to_csv(os.path.join("..","Data","Clean","US_Adults_Percent_Overweight_by_State_Year_Clean.csv"))

In [94]:
file_rpp = pd.read_csv(os.path.join("..","Data","Raw","Regional_Price_Parity_Data.csv"),header=4)
print(file_rpp)

                                                GeoFips  \
0                                                 00000
1                                                 00000
2                                                 00000
3                                                 00000
4                                                 00999
5                                                 00999
6                                                 00999
7                                                 00999
8                                                 10180
9                                                 10180
10                                                10180
11                                                10180
12                                                10420
13                                                10420
14                                                10420
15                                                10420
16                                                10500
17                                                10500
18                                                10500
19                                                10500
20                                                10540
21                                                10540
22                                                10540
23                                                10540
24                                                10580
25                                                10580
26                                                10580
27                                                10580
28                                                10740
29                                                10740
...                                                 ...
1519                                              49180
1520                                              49340
1521                                              49340
1522                                              49340
1523                                              49340
1524                                              49420
1525                                              49420
1526                                              49420
1527                                              49420
1528                                              49620
1529                                              49620
1530                                              49620
1531                                              49620
1532                                              49660
1533                                              49660
1534                                              49660
1535                                              49660
1536                                              49700
1537                                              49700
1538                                              49700
1539                                              49700
1540                                              49740
1541                                              49740
1542                                              49740
1543                                              49740
1544                                Legend / Footnotes:
1545  1/ Regional Price Parities for the United Stat...
1546  2/ Regional Price Parities are not available f...
1547                                (NA) Not available.
1548  Last updated: November 14, 2019-- revised stat...

                                                GeoName  LineCode  \
0                                         United States       1.0
1                                         United States       2.0
2                                         United States       3.0
3                                         United States       4.0
4             United States (Nonmetropolitan Portion)1/       1.0
5             United States (Nonmetropolitan Portion)1/       2.0
6             United States (Nonmetropolitan Portion)1/       3.0
7             United States (Nonmetropolitan Portion)1/       4.0
8           Abilene, TX (Metropolitan Statistical Area)       1.0
9           Abilene, TX (Metropolitan Statistical Area)       2.0
10          Abilene, TX (Metropolitan Statistical Area)       3.0
11          Abilene, TX (Metropolitan Statistical Area)       4.0
12            Akron, OH (Metropolitan Statistical Area)       1.0
13            Akron, OH (Metropolitan Statistical Area)       2.0
14            Akron, OH (Metropolitan Statistical Area)       3.0
15            Akron, OH (Metropolitan Statistical Area)       4.0
16           Albany, GA (Metropolitan Statistical Area)       1.0
17           Albany, GA (Metropolitan Statistical Area)       2.0
18           Albany, GA (Metropolitan Statistical Area)       3.0
19           Albany, GA (Metropolitan Statistical Area)       4.0
20    Albany-Lebanon, OR (Metropolitan Statistical A...       1.0
21    Albany-Lebanon, OR (Metropolitan Statistical A...       2.0
22    Albany-Lebanon, OR (Metropolitan Statistical A...       3.0
23    Albany-Lebanon, OR (Metropolitan Statistical A...       4.0
24    Albany-Schenectady-Troy, NY (Metropolitan Stat...       1.0
25    Albany-Schenectady-Troy, NY (Metropolitan Stat...       2.0
26    Albany-Schenectady-Troy, NY (Metropolitan Stat...       3.0
27    Albany-Schenectady-Troy, NY (Metropolitan Stat...       4.0
28      Albuquerque, NM (Metropolitan Statistical Area)       1.0
29      Albuquerque, NM (Metropolitan Statistical Area)       2.0
...                                                 ...       ...
1519  Winston-Salem, NC (Metropolitan Statistical Area)       4.0
1520   Worcester, MA-CT (Metropolitan Statistical Area)       1.0
1521   Worcester, MA-CT (Metropolitan Statistical Area)       2.0
1522   Worcester, MA-CT (Metropolitan Statistical Area)       3.0
1523   Worcester, MA-CT (Metropolitan Statistical Area)       4.0
1524         Yakima, WA (Metropolitan Statistical Area)       1.0
1525         Yakima, WA (Metropolitan Statistical Area)       2.0
1526         Yakima, WA (Metropolitan Statistical Area)       3.0
1527         Yakima, WA (Metropolitan Statistical Area)       4.0
1528   York-Hanover, PA (Metropolitan Statistical Area)       1.0
1529   York-Hanover, PA (Metropolitan Statistical Area)       2.0
1530   York-Hanover, PA (Metropolitan Statistical Area)       3.0
1531   York-Hanover, PA (Metropolitan Statistical Area)       4.0
1532  Youngstown-Warren-Boardman, OH-PA (Metropolita...       1.0
1533  Youngstown-Warren-Boardman, OH-PA (Metropolita...       2.0
1534  Youngstown-Warren-Boardman, OH-PA (Metropolita...       3.0
1535  Youngstown-Warren-Boardman, OH-PA (Metropolita...       4.0
1536      Yuba City, CA (Metropolitan Statistical Area)       1.0
1537      Yuba City, CA (Metropolitan Statistical Area)       2.0
1538      Yuba City, CA (Metropolitan Statistical Area)       3.0
1539      Yuba City, CA (Metropolitan Statistical Area)       4.0
1540           Yuma, AZ (Metropolitan Statistical Area)       1.0
1541           Yuma, AZ (Metropolitan Statistical Area)       2.0
1542           Yuma, AZ (Metropolitan Statistical Area)       3.0
1543           Yuma, AZ (Metropolitan Statistical Area)       4.0
1544                                                NaN       NaN
1545                                                NaN       NaN
1546                                                NaN       NaN
1547                                                NaN       NaN
1548                                                NaN       NaN

                  Description   2008   2009   2010   2011   2012   2013  \
0             RPPs: All items  100.0  100.0  100.0  100.0  100.0  100.0
1                 RPPs: Goods   99.3   99.2   99.0   99.0   99.0   99.0
2       RPPs: Services: Rents  101.1  101.2  102.0  101.9  101.8  101.8
3       RPPs: Services: Other  100.3  100.3  100.1  100.1  100.1  100.1
4             RPPs: All items   86.6   86.8   87.3   87.5   87.8   88.2
5                 RPPs: Goods   94.3   94.4   94.1   93.9   93.9   93.8
6       RPPs: Services: Rents   63.4   63.3   62.7   63.1   63.5   63.8
7       RPPs: Services: Other   92.1   91.8   91.9   92.4   92.9   93.9
8             RPPs: All items   90.4   89.8   90.4   90.8   91.4   90.9
9                 RPPs: Goods   98.1   98.1   97.2   97.0   97.0   96.8
10      RPPs: Services: Rents   73.4   72.1   72.8   74.6   77.1   75.7
11      RPPs: Services: Other   94.6   94.3   94.0   94.1   94.2   94.0
12            RPPs: All items   89.4   88.5   88.5   89.0   88.8   89.6
13                RPPs: Goods   94.3   93.9   94.0   95.1   94.6   95.3
14      RPPs: Services: Rents   81.9   79.3   77.9   77.6   77.7   78.2
15      RPPs: Services: Other   88.1   87.9   88.1   88.4   88.5   89.6
16            RPPs: All items   83.3   83.6   84.2   84.6   84.6   84.4
17                RPPs: Goods   98.0   98.0   97.1   96.9   96.8   96.7
18      RPPs: Services: Rents   54.7   56.0   54.3   56.3   56.3   55.8
19      RPPs: Services: Other   94.5   94.2   93.9   94.1   94.2   94.1
20            RPPs: All items   96.5   96.0   95.2   93.8   93.1   93.7
21                RPPs: Goods   99.8   99.1   99.3   98.9   98.7   98.8
22      RPPs: Services: Rents   88.2   90.4   88.3   85.3   84.3   85.3
23      RPPs: Services: Other   98.8   95.8   94.8   93.9   93.4   94.2
24            RPPs: All items  100.1   99.6   98.6   98.6   99.1   99.6
25                RPPs: Goods   98.4   98.2   97.9   97.7   97.9   98.1
26      RPPs: Services: Rents  105.7  104.1  101.7  102.6  104.3  104.4
27      RPPs: Services: Other   99.3   98.8   97.9   97.7   98.0   98.8
28            RPPs: All items   96.1   97.0   97.0   97.3   97.2   97.4
29                RPPs: Goods   95.9   96.7   97.1   97.6   97.0   96.4
...                       ...    ...    ...    ...    ...    ...    ...
1519    RPPs: Services: Other   95.2   94.8   94.3   94.4   94.4   94.0
1520          RPPs: All items  105.3  105.1  104.5  104.3  104.0  103.5
1521              RPPs: Goods   98.9   98.1   97.6   98.9  100.2  100.5
1522    RPPs: Services: Rents  106.2  106.9  105.2  106.0  105.7  104.5
1523    RPPs: Services: Other  112.2  112.2  111.9  109.4  107.2  106.3
1524          RPPs: All items   93.2   94.4   94.8   95.8   95.5   95.6
1525              RPPs: Goods   95.8   96.6   97.1   97.6   96.9   96.4
1526    RPPs: Services: Rents   79.3   81.0   80.2   82.8   81.5   81.7
1527    RPPs: Services: Other   97.6   99.3  100.2  100.8  101.3  102.7
1528          RPPs: All items   96.4   96.2   95.5   95.8   96.1   96.3
1529              RPPs: Goods   98.4   98.2   97.9   97.7   97.9   98.1
1530    RPPs: Services: Rents   87.2   87.8   86.5   88.2   89.1   88.4
1531    RPPs: Services: Other   99.3   98.8   97.9   97.7   98.0   98.8
1532          RPPs: All items   89.1   88.2   88.5   88.5   88.7   88.4
1533              RPPs: Goods   96.8   97.4   97.4   97.5   97.7   97.9
1534    RPPs: Services: Rents   65.2   63.1   61.5   60.9   62.3   62.1
1535    RPPs: Services: Other   96.4   95.8   95.3   95.3   95.2   94.7
1536          RPPs: All items   97.7   98.6   98.3   98.8   98.7   99.3
1537              RPPs: Goods   95.8   96.6   97.1   97.6   96.9   96.4
1538    RPPs: Services: Rents  102.3  102.1   97.8   98.3   97.9   99.6
1539    RPPs: Services: Other   97.6   99.3  100.2  100.8  101.3  102.8
1540          RPPs: All items   93.3   94.8   94.2   95.1   93.9   94.0
1541              RPPs: Goods   95.8   96.6   97.1   97.6   96.9   96.4
1542    RPPs: Services: Rents   81.8   84.5   79.9   81.6   77.5   77.1
1543    RPPs: Services: Other   97.6   99.3  100.2  100.8  101.3  102.7
1544                      NaN    NaN    NaN    NaN    NaN    NaN    NaN
1545                      NaN    NaN    NaN    NaN    NaN    NaN    NaN
1546                      NaN    NaN    NaN    NaN    NaN    NaN    NaN
1547                      NaN    NaN    NaN    NaN    NaN    NaN    NaN
1548                      NaN    NaN    NaN    NaN    NaN    NaN    NaN

       2014   2015   2016   2017
0     100.0  100.0  100.0  100.0
1      99.0   99.0   99.0   99.0
2     101.7  101.7  101.7  101.8
3     100.1  100.1  100.1  100.1
4      88.1   88.0   87.7   87.5
5      93.9   94.2   94.2   94.2
6      64.1   63.9   63.7   63.3
7      94.0   93.7   93.7   93.7
8      91.2   90.9   91.5   91.2
9      97.2   97.4   97.3   97.4
10     77.8   76.9   79.5   78.7
11     93.5   93.5   93.5   93.5
12     90.1   90.5   90.3   90.4
13     95.6   95.6   95.7   95.8
14     77.9   77.8   76.7   77.4
15     90.8   91.7   91.8   91.8
16     84.1   83.9   83.1   82.7
17     97.1   97.2   97.2   97.2
18     55.0   55.6   54.7   54.0
19     93.5   93.5   93.5   93.5
20     94.8   94.0   94.7   94.6
21     99.4  100.2  100.2  100.1
22     88.4   85.5   87.9   87.4
23     94.4   93.4   93.4   93.4
24    100.4  100.8  100.9  100.6
25     98.1   98.1   98.1   98.1
26    104.6  104.9  105.0  103.4
27    100.7  101.8  101.8  101.8
28     96.8   96.4   96.0   95.7
29     95.5   95.2   95.2   95.1
...     ...    ...    ...    ...
1519   93.4   93.5   93.5   93.5
1520  103.9  104.1  103.9  103.6
1521  101.0  101.7  101.7  101.7
1522  104.6  104.4  103.6  102.2
1523  106.6  106.5  106.4  106.4
1524   94.6   93.9   93.2   92.7
1525   95.5   95.2   95.1   95.0
1526   80.3   79.2   77.7   76.5
1527  102.0  101.5  101.5  101.5
1528   97.1   97.3   96.9   96.6
1529   98.1   98.1   98.1   98.1
1530   89.4   88.6   87.5   86.4
1531  100.7  101.8  101.8  101.8
1532   88.3   87.2   87.0   86.6
1533   97.5   96.6   96.6   96.5
1534   62.8   61.2   60.8   59.5
1535   94.9   94.2   94.2   94.2
1536   98.2   97.8   96.8   96.6
1537   95.5   95.2   95.1   95.0
1538   97.7   97.5   93.5   92.9
1539  102.0  101.5  101.5  101.5
1540   92.9   92.1   91.2   90.5
1541   95.5   95.2   95.1   95.0
1542   76.2   74.6   72.6   71.1
1543  102.0  101.5  101.5  101.5
1544    NaN    NaN    NaN    NaN
1545    NaN    NaN    NaN    NaN
1546    NaN    NaN    NaN    NaN
1547    NaN    NaN    NaN    NaN
1548    NaN    NaN    NaN    NaN

[1549 rows x 14 columns]

In [96]:
rpp_df = pd.DataFrame(file_rpp)
rpp_df.set_index("GeoFips", inplace = True)
rpp_df

,GeoName,LineCode,Description,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
GeoFips,,,,,,,,,,,,,
00000,United States,1.0,RPPs: All items,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
00000,United States,2.0,RPPs: Goods,99.3,99.2,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
00000,United States,3.0,RPPs: Services: Rents,101.1,101.2,102.0,101.9,101.8,101.8,101.7,101.7,101.7,101.8
00000,United States,4.0,RPPs: Services: Other,100.3,100.3,100.1,100.1,100.1,100.1,100.1,100.1,100.1,100.1
00999,United States (Nonmetropolitan Portion)1/,1.0,RPPs: All items,86.6,86.8,87.3,87.5,87.8,88.2,88.1,88.0,87.7,87.5
00999,United States (Nonmetropolitan Portion)1/,2.0,RPPs: Goods,94.3,94.4,94.1,93.9,93.9,93.8,93.9,94.2,94.2,94.2
00999,United States (Nonmetropolitan Portion)1/,3.0,RPPs: Services: Rents,63.4,63.3,62.7,63.1,63.5,63.8,64.1,63.9,63.7,63.3
00999,United States (Nonmetropolitan Portion)1/,4.0,RPPs: Services: Other,92.1,91.8,91.9,92.4,92.9,93.9,94.0,93.7,93.7,93.7
10180,"Abilene, TX (Metropolitan Statistical Area)",1.0,RPPs: All items,90.4,89.8,90.4,90.8,91.4,90.9,91.2,90.9,91.5,91.2
10180,"Abilene, TX (Metropolitan Statistical Area)",2.0,RPPs: Goods,98.1,98.1,97.2,97.0,97.0,96.8,97.2,97.4,97.3,97.4
10180,"Abilene, TX (Metropolitan Statistical Area)",3.0,RPPs: Services: Rents,73.4,72.1,72.8,74.6,77.1,75.7,77.8,76.9,79.5,78.7
10180,"Abilene, TX (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,94.6,94.3,94.0,94.1,94.2,94.0,93.5,93.5,93.5,93.5
10420,"Akron, OH (Metropolitan Statistical Area)",1.0,RPPs: All items,89.4,88.5,88.5,89.0,88.8,89.6,90.1,90.5,90.3,90.4
10420,"Akron, OH (Metropolitan Statistical Area)",2.0,RPPs: Goods,94.3,93.9,94.0,95.1,94.6,95.3,95.6,95.6,95.7,95.8
10420,"Akron, OH (Metropolitan Statistical Area)",3.0,RPPs: Services: Rents,81.9,79.3,77.9,77.6,77.7,78.2,77.9,77.8,76.7,77.4
10420,"Akron, OH (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,88.1,87.9,88.1,88.4,88.5,89.6,90.8,91.7,91.8,91.8
10500,"Albany, GA (Metropolitan Statistical Area)",1.0,RPPs: All items,83.3,83.6,84.2,84.6,84.6,84.4,84.1,83.9,83.1,82.7
10500,"Albany, GA (Metropolitan Statistical Area)",2.0,RPPs: Goods,98.0,98.0,97.1,96.9,96.8,96.7,97.1,97.2,97.2,97.2
10500,"Albany, GA (Metropolitan Statistical Area)",3.0,RPPs: Services: Rents,54.7,56.0,54.3,56.3,56.3,55.8,55.0,55.6,54.7,54.0
10500,"Albany, GA (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,94.5,94.2,93.9,94.1,94.2,94.1,93.5,93.5,93.5,93.5
10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",1.0,RPPs: All items,96.5,96.0,95.2,93.8,93.1,93.7,94.8,94.0,94.7,94.6
10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",2.0,RPPs: Goods,99.8,99.1,99.3,98.9,98.7,98.8,99.4,100.2,100.2,100.1
10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",3.0,RPPs: Services: Rents,88.2,90.4,88.3,85.3,84.3,85.3,88.4,85.5,87.9,87.4
10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",4.0,RPPs: Services: Other,98.8,95.8,94.8,93.9,93.4,94.2,94.4,93.4,93.4,93.4
10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",1.0,RPPs: All items,100.1,99.6,98.6,98.6,99.1,99.6,100.4,100.8,100.9,100.6
10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",2.0,RPPs: Goods,98.4,98.2,97.9,97.7,97.9,98.1,98.1,98.1,98.1,98.1
10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",3.0,RPPs: Services: Rents,105.7,104.1,101.7,102.6,104.3,104.4,104.6,104.9,105.0,103.4
10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",4.0,RPPs: Services: Other,99.3,98.8,97.9,97.7,98.0,98.8,100.7,101.8,101.8,101.8
10740,"Albuquerque, NM (Metropolitan Statistical Area)",1.0,RPPs: All items,96.1,97.0,97.0,97.3,97.2,97.4,96.8,96.4,96.0,95.7
10740,"Albuquerque, NM (Metropolitan Statistical Area)",2.0,RPPs: Goods,95.9,96.7,97.1,97.6,97.0,96.4,95.5,95.2,95.2,95.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49180,"Winston-Salem, NC (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,95.2,94.8,94.3,94.4,94.4,94.0,93.4,93.5,93.5,93.5
49340,"Worcester, MA-CT (Metropolitan Statistical Area)",1.0,RPPs: All items,105.3,105.1,104.5,104.3,104.0,103.5,103.9,104.1,103.9,103.6
49340,"Worcester, MA-CT (Metropolitan Statistical Area)",2.0,RPPs: Goods,98.9,98.1,97.6,98.9,100.2,100.5,101.0,101.7,101.7,101.7
49340,"Worcester, MA-CT (Metropolitan Statistical Area)",3.0,RPPs: Services: Rents,106.2,106.9,105.2,106.0,105.7,104.5,104.6,104.4,103.6,102.2
49340,"Worcester, MA-CT (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,112.2,112.2,111.9,109.4,107.2,106.3,106.6,106.5,106.4,106.4
49420,"Yakima, WA (Metropolitan Statistical Area)",1.0,RPPs: All items,93.2,94.4,94.8,95.8,95.5,95.6,94.6,93.9,93.2,92.7
49420,"Yakima, WA (Metropolitan Statistical Area)",2.0,RPPs: Goods,95.8,96.6,97.1,97.6,96.9,96.4,95.5,95.2,95.1,95.0
49420,"Yakima, WA (Metropolitan Statistical Area)",3.0,RPPs: Services: Rents,79.3,81.0,80.2,82.8,81.5,81.7,80.3,79.2,77.7,76.5
49420,"Yakima, WA (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,97.6,99.3,100.2,100.8,101.3,102.7,102.0,101.5,101.5,101.5
49620,"York-Hanover, PA (Metropolitan Statistical Area)",1.0,RPPs: All items,96.4,96.2,95.5,95.8,96.1,96.3,97.1,97.3,96.9,96.6
49620,"York-Hanover, PA (Metropolitan Statistical Area)",2.0,RPPs: Goods,98.4,98.2,97.9,97.7,97.9,98.1,98.1,98.1,98.1,98.1
49620,"York-Hanover, PA (Metropolitan Statistical Area)",3.0,RPPs: Services: Rents,87.2,87.8,86.5,88.2,89.1,88.4,89.4,88.6,87.5,86.4
49620,"York-Hanover, PA (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,99.3,98.8,97.9,97.7,98.0,98.8,100.7,101.8,101.8,101.8
49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",1.0,RPPs: All items,89.1,88.2,88.5,88.5,88.7,88.4,88.3,87.2,87.0,86.6
49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",2.0,RPPs: Goods,96.8,97.4,97.4,97.5,97.7,97.9,97.5,96.6,96.6,96.5
49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",3.0,RPPs: Services: Rents,65.2,63.1,61.5,60.9,62.3,62.1,62.8,61.2,60.8,59.5
49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",4.0,RPPs: Services: Other,96.4,95.8,95.3,95.3,95.2,94.7,94.9,94.2,94.2,94.2
49700,"Yuba City, CA (Metropolitan Statistical Area)",1.0,RPPs: All items,97.7,98.6,98.3,98.8,98.7,99.3,98.2,97.8,96.8,96.6
49700,"Yuba City, CA (Metropolitan Statistical Area)",2.0,RPPs: Goods,95.8,96.6,97.1,97.6,96.9,96.4,95.5,95.2,95.1,95.0
49700,"Yuba City, CA (Metropolitan Statistical Area)",3.0,RPPs: Services: Rents,102.3,102.1,97.8,98.3,97.9,99.6,97.7,97.5,93.5,92.9
49700,"Yuba City, CA (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,97.6,99.3,100.2,100.8,101.3,102.8,102.0,101.5,101.5,101.5
49740,"Yuma, AZ (Metropolitan Statistical Area)",1.0,RPPs: All items,93.3,94.8,94.2,95.1,93.9,94.0,92.9,92.1,91.2,90.5
49740,"Yuma, AZ (Metropolitan Statistical Area)",2.0,RPPs: Goods,95.8,96.6,97.1,97.6,96.9,96.4,95.5,95.2,95.1,95.0
49740,"Yuma, AZ (Metropolitan Statistical Area)",3.0,RPPs: Services: Rents,81.8,84.5,79.9,81.6,77.5,77.1,76.2,74.6,72.6,71.1
49740,"Yuma, AZ (Metropolitan Statistical Area)",4.0,RPPs: Services: Other,97.6,99.3,100.2,100.8,101.3,102.7,102.0,101.5,101.5,101.5
Legend / Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/ Regional Price Parities for the United States Nonmetropolitan Portion were estimated using multiple statistical area delineations published by the Office of Management and Budget.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"2/ Regional Price Parities are not available for Enid, OK prior to 2013, Twin Falls, ID prior to 2015 and Poughkeepsie-Newburgh-Middletown, NY for 2008-2017.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(NA) Not available.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Last updated: November 14, 2019-- revised statistics for 2008-2017.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
rpp_df.isnull().any()

GeoName        True
LineCode       True
Description    True
2008           True
2009           True
2010           True
2011           True
2012           True
2013           True
2014           True
2015           True
2016           True
2017           True
dtype: bool

In [102]:
rpp_df.count()

GeoName        1544
LineCode       1544
Description    1544
2008           1544
2009           1544
2010           1544
2011           1544
2012           1544
2013           1544
2014           1544
2015           1544
2016           1544
2017           1544
dtype: int64

In [103]:
new_rpp_df = rpp_df.dropna()
new_rpp_df.count()

GeoName        1544
LineCode       1544
Description    1544
2008           1544
2009           1544
2010           1544
2011           1544
2012           1544
2013           1544
2014           1544
2015           1544
2016           1544
2017           1544
dtype: int64

In [104]:
new_rpp_df.head()

,GeoName,LineCode,Description,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
GeoFips,,,,,,,,,,,,,
00000,United States,1.0,RPPs: All items,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
00000,United States,2.0,RPPs: Goods,99.3,99.2,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
00000,United States,3.0,RPPs: Services: Rents,101.1,101.2,102.0,101.9,101.8,101.8,101.7,101.7,101.7,101.8
00000,United States,4.0,RPPs: Services: Other,100.3,100.3,100.1,100.1,100.1,100.1,100.1,100.1,100.1,100.1
00999,United States (Nonmetropolitan Portion)1/,1.0,RPPs: All items,86.6,86.8,87.3,87.5,87.8,88.2,88.1,88.0,87.7,87.5

In [105]:
new_rpp_df.to_csv(os.path.join("..","Data","Clean","Regional_Price_Parity_Data_Clean.csv"))

In [106]:
file_winereg = pd.read_csv(os.path.join("..","Data","Raw","Wine_Regions.csv"))
print(file_winereg)

     Index                                    Region Name  Vineyards  \
0        1                              Adelaida District         42
1        2                               Alexander Valley        241
2        3                                      Alta Mesa          1
3        4               Ancient Lakes of Columbia Valley          0
4        5                                Anderson Valley         39
5        6                                      Annapolis         10
6        7  Antelope Valley of the California High Desert          0
7        8                               Applegate Valley         37
8        9                           Arroyo Grande Valley         10
9       10                                    Arroyo Seco         37
10      11                                     Atlas Peak         12
11      12                                 Ballard Canyon          8
12      13                                  Bell Mountain          1
13      14                            Ben Lomond Mountain          3
14      15                                 Benmore Valley          0
15      16                                 Bennett Valley         35
16      17                Big Valley District-Lake County         15
17      18                                   Borden Ranch          1
18      19                                      Calistoga         38
19      20                                   Capay Valley          1
20      21                                  Carmel Valley          2
21      22                            CaShenandoah Valley          7
22      23                                  Central Coast        637
23      24                                     Chalk Hill         40
24      25                                        Chalone          3
25      26                             Chehalem Mountains        182
26      27                                  Chiles Valley          2
27      28                                 Cienega Valley          4
28      29                                     Clarksburg         18
29      30                                     Clear Lake         42
..     ...                                            ...        ...
139    140                                   Sonoma Coast        775
140    141                                Sonoma Mountain         37
141    142                                  Sonoma Valley        316
142    143                                    South Coast         28
143    144                                Southern Oregon        134
144    145                       Spring Mountain District         19
145    146                                Sta. Rita Hills         35
146    147                            Stags Leap District         37
147    148                                  Suisun Valley          6
148    149                                Temecula Valley          7
149    150                         Templeton Gap District         23
150    151                          Texas Davis Mountains          0
151    152                              Texas High Plains          1
152    153                             Texas Hill Country          5
153    154                                         Texoma          0
154    155         The Rocks District of Milton-Freewater         25
155    156                                    Tracy Hills          0
156    157                                  Trinity Lakes          0
157    158                                  Umpqua Valley         45
158    159                             Walla Walla Valley        121
159    160                                      West Elks         23
160    161                              West Sonoma Coast         50
161    162                              Wild Horse Valley          0
162    163                              Willamette Valley        778
163    164                                   Willow Creek          0
164    165                                  Yakima Valley         78
165    166                                Yamhill-Carlton        105
166    167                                  York Mountain          1
167    168                            Yorkville Highlands          6
168    169                                     Yountville         19

     Wineries  Tasting Rooms               State  \
0          15             16          California
1          41             23          California
2           0              0          California
3           0              0          Washington
4           7              5          California
5           0              0          California
6           0              0          California
7          17             18              Oregon
8           4              2          California
9           0              0          California
10          1              0          California
11          0              0          California
12          0              0               Texas
13          2              2          California
14          0              0          California
15          2              1          California
16          0              0          California
17          0              0          California
18          1              0          California
19          0              0          California
20          0              0          California
21          3              3          California
22        122            118          California
23          6              3          California
24          0              0          California
25         53             34              Oregon
26          0              0          California
27          0              0          California
28          3              3          California
29          0              0          California
..        ...            ...                 ...
139       115             85          California
140         1              1          California
141        47             33          California
142        10              9          California
143        52             59              Oregon
144         0              0          California
145         2              3          California
146        15             13          California
147         0              0          California
148         4              3          California
149         5              4          California
150         0              0               Texas
151         0              1               Texas
152         2              0               Texas
153         0              0     Texas, Oklahoma
154         0              0              Oregon
155         0              0          California
156         0              0          California
157        19             22              Oregon
158        25             25  Oregon, Washington
159        10             12            Colorado
160         3              2          California
161         0              0          California
162       269            263  Oregon, Washington
163         0              0          California
164         8              7          Washington
165        31             26              Oregon
166         0              0          California
167         2              2          California
168         8              8          California

                                                County
0                                      San Luis Obispo
1                                               Sonoma
2                              Sacramento, San Joaquin
3                             Douglas, Grant, Kittitas
4                                            Mendocino
5                                               Sonoma
6                                    Kern, Los Angeles
7                                   Jackson, Josephine
8                                      San Luis Obispo
9                                             Monterey
10                                                Napa
11                                       Santa Barbara
12                                           Gillespie
13                                          Santa Cruz
14                                                Lake
15                                              Sonoma
16                                                Lake
17                     Amador, Sacramento, San Joaquin
18                                                Napa
19                                                Yolo
20                                            Monterey
21                                   Amador, El Dorado
22   Alameda, Contra Costa, Fresno, Kern, Kings, Me...
23                                              Sonoma
24                                Monterey, San Benito
25                      Clackamas, Washington, Yamhill
26                                                Napa
27                                          San Benito
28                            Sacramento, Solano, Yolo
29                                                Lake
..                                                 ...
139                                             Sonoma
140                                             Sonoma
141                                             Sonoma
142  Los Angeles, Orange, Riverside, San Diego, San...
143                  Douglas, Jackson, Josephine, Lane
144                                               Napa
145                                      Santa Barbara
146                                               Napa
147                                       Napa, Solano
148                               Riverside, San Diego
149                                    San Luis Obispo
150                                         Jeff Davis
151  Armstrong, Deaf Smith, Randall, Borden, Dawson...
152  Bandera, Blanco, Comal, Edwards, Gillespie, Gu...
153  Collin, Cooke, Denton, Fannin, Grayson, Lamar,...
154                                           Umatilla
155                            San Joaquin, Stanislaus
156                                            Trinity
157                                      Douglas, Lane
158                                        Walla Walla
159                                              Delta
160                                  Mendocino, Sonoma
161                                       Napa, Solano
162  Benton, Lane, Linn, Clackamas, Lincoln, Marion...
163                                  Humboldt, Trinity
164                                     Benton, Yakima
165                                Washington, Yamhill
166                                    San Luis Obispo
167                                          Mendocino
168                                               Napa

[169 rows x 7 columns]

In [108]:
winereg_df = pd.DataFrame(file_winereg)
winereg_df.set_index("Region Name", inplace=True)
winereg_df

,Index,Vineyards,Wineries,Tasting Rooms,State,County
Region Name,,,,,,
Adelaida District,1,42,15,16,California,San Luis Obispo
Alexander Valley,2,241,41,23,California,Sonoma
Alta Mesa,3,1,0,0,California,"Sacramento, San Joaquin"
Ancient Lakes of Columbia Valley,4,0,0,0,Washington,"Douglas, Grant, Kittitas"
Anderson Valley,5,39,7,5,California,Mendocino
Annapolis,6,10,0,0,California,Sonoma
Antelope Valley of the California High Desert,7,0,0,0,California,"Kern, Los Angeles"
Applegate Valley,8,37,17,18,Oregon,"Jackson, Josephine"
Arroyo Grande Valley,9,10,4,2,California,San Luis Obispo
Arroyo Seco,10,37,0,0,California,Monterey
Atlas Peak,11,12,1,0,California,Napa
Ballard Canyon,12,8,0,0,California,Santa Barbara
Bell Mountain,13,1,0,0,Texas,Gillespie
Ben Lomond Mountain,14,3,2,2,California,Santa Cruz
Benmore Valley,15,0,0,0,California,Lake
Bennett Valley,16,35,2,1,California,Sonoma
Big Valley District-Lake County,17,15,0,0,California,Lake
Borden Ranch,18,1,0,0,California,"Amador, Sacramento, San Joaquin"
Calistoga,19,38,1,0,California,Napa
Capay Valley,20,1,0,0,California,Yolo
Carmel Valley,21,2,0,0,California,Monterey
CaShenandoah Valley,22,7,3,3,California,"Amador, El Dorado"
Central Coast,23,637,122,118,California,"Alameda, Contra Costa, Fresno, Kern, Kings, Me..."
Chalk Hill,24,40,6,3,California,Sonoma
Chalone,25,3,0,0,California,"Monterey, San Benito"
Chehalem Mountains,26,182,53,34,Oregon,"Clackamas, Washington, Yamhill"
Chiles Valley,27,2,0,0,California,Napa
Cienega Valley,28,4,0,0,California,San Benito
Clarksburg,29,18,3,3,California,"Sacramento, Solano, Yolo"
Clear Lake,30,42,0,0,California,Lake
...,...,...,...,...,...,...
Sonoma Coast,140,775,115,85,California,Sonoma
Sonoma Mountain,141,37,1,1,California,Sonoma
Sonoma Valley,142,316,47,33,California,Sonoma
South Coast,143,28,10,9,California,"Los Angeles, Orange, Riverside, San Diego, San..."
Southern Oregon,144,134,52,59,Oregon,"Douglas, Jackson, Josephine, Lane"
Spring Mountain District,145,19,0,0,California,Napa
Sta. Rita Hills,146,35,2,3,California,Santa Barbara
Stags Leap District,147,37,15,13,California,Napa
Suisun Valley,148,6,0,0,California,"Napa, Solano"
Temecula Valley,149,7,4,3,California,"Riverside, San Diego"
Templeton Gap District,150,23,5,4,California,San Luis Obispo
Texas Davis Mountains,151,0,0,0,Texas,Jeff Davis
Texas High Plains,152,1,0,1,Texas,"Armstrong, Deaf Smith, Randall, Borden, Dawson..."
Texas Hill Country,153,5,2,0,Texas,"Bandera, Blanco, Comal, Edwards, Gillespie, Gu..."
Texoma,154,0,0,0,"Texas, Oklahoma","Collin, Cooke, Denton, Fannin, Grayson, Lamar,..."
The Rocks District of Milton-Freewater,155,25,0,0,Oregon,Umatilla
Tracy Hills,156,0,0,0,California,"San Joaquin, Stanislaus"
Trinity Lakes,157,0,0,0,California,Trinity
Umpqua Valley,158,45,19,22,Oregon,"Douglas, Lane"
Walla Walla Valley,159,121,25,25,"Oregon, Washington",Walla Walla
West Elks,160,23,10,12,Colorado,Delta
West Sonoma Coast,161,50,3,2,California,"Mendocino, Sonoma"
Wild Horse Valley,162,0,0,0,California,"Napa, Solano"
Willamette Valley,163,778,269,263,"Oregon, Washington","Benton, Lane, Linn, Clackamas, Lincoln, Marion..."
Willow Creek,164,0,0,0,California,"Humboldt, Trinity"
Yakima Valley,165,78,8,7,Washington,"Benton, Yakima"
Yamhill-Carlton,166,105,31,26,Oregon,"Washington, Yamhill"
York Mountain,167,1,0,0,California,San Luis Obispo
Yorkville Highlands,168,6,2,2,California,Mendocino
Yountville,169,19,8,8,California,Napa

In [109]:
winereg_df = winereg_df.drop(columns='Index')
winereg_df

,Vineyards,Wineries,Tasting Rooms,State,County
Region Name,,,,,
Adelaida District,42,15,16,California,San Luis Obispo
Alexander Valley,241,41,23,California,Sonoma
Alta Mesa,1,0,0,California,"Sacramento, San Joaquin"
Ancient Lakes of Columbia Valley,0,0,0,Washington,"Douglas, Grant, Kittitas"
Anderson Valley,39,7,5,California,Mendocino
Annapolis,10,0,0,California,Sonoma
Antelope Valley of the California High Desert,0,0,0,California,"Kern, Los Angeles"
Applegate Valley,37,17,18,Oregon,"Jackson, Josephine"
Arroyo Grande Valley,10,4,2,California,San Luis Obispo
Arroyo Seco,37,0,0,California,Monterey
Atlas Peak,12,1,0,California,Napa
Ballard Canyon,8,0,0,California,Santa Barbara
Bell Mountain,1,0,0,Texas,Gillespie
Ben Lomond Mountain,3,2,2,California,Santa Cruz
Benmore Valley,0,0,0,California,Lake
Bennett Valley,35,2,1,California,Sonoma
Big Valley District-Lake County,15,0,0,California,Lake
Borden Ranch,1,0,0,California,"Amador, Sacramento, San Joaquin"
Calistoga,38,1,0,California,Napa
Capay Valley,1,0,0,California,Yolo
Carmel Valley,2,0,0,California,Monterey
CaShenandoah Valley,7,3,3,California,"Amador, El Dorado"
Central Coast,637,122,118,California,"Alameda, Contra Costa, Fresno, Kern, Kings, Me..."
Chalk Hill,40,6,3,California,Sonoma
Chalone,3,0,0,California,"Monterey, San Benito"
Chehalem Mountains,182,53,34,Oregon,"Clackamas, Washington, Yamhill"
Chiles Valley,2,0,0,California,Napa
Cienega Valley,4,0,0,California,San Benito
Clarksburg,18,3,3,California,"Sacramento, Solano, Yolo"
Clear Lake,42,0,0,California,Lake
...,...,...,...,...,...
Sonoma Coast,775,115,85,California,Sonoma
Sonoma Mountain,37,1,1,California,Sonoma
Sonoma Valley,316,47,33,California,Sonoma
South Coast,28,10,9,California,"Los Angeles, Orange, Riverside, San Diego, San..."
Southern Oregon,134,52,59,Oregon,"Douglas, Jackson, Josephine, Lane"
Spring Mountain District,19,0,0,California,Napa
Sta. Rita Hills,35,2,3,California,Santa Barbara
Stags Leap District,37,15,13,California,Napa
Suisun Valley,6,0,0,California,"Napa, Solano"
Temecula Valley,7,4,3,California,"Riverside, San Diego"
Templeton Gap District,23,5,4,California,San Luis Obispo
Texas Davis Mountains,0,0,0,Texas,Jeff Davis
Texas High Plains,1,0,1,Texas,"Armstrong, Deaf Smith, Randall, Borden, Dawson..."
Texas Hill Country,5,2,0,Texas,"Bandera, Blanco, Comal, Edwards, Gillespie, Gu..."
Texoma,0,0,0,"Texas, Oklahoma","Collin, Cooke, Denton, Fannin, Grayson, Lamar,..."
The Rocks District of Milton-Freewater,25,0,0,Oregon,Umatilla
Tracy Hills,0,0,0,California,"San Joaquin, Stanislaus"
Trinity Lakes,0,0,0,California,Trinity
Umpqua Valley,45,19,22,Oregon,"Douglas, Lane"
Walla Walla Valley,121,25,25,"Oregon, Washington",Walla Walla
West Elks,23,10,12,Colorado,Delta
West Sonoma Coast,50,3,2,California,"Mendocino, Sonoma"
Wild Horse Valley,0,0,0,California,"Napa, Solano"
Willamette Valley,778,269,263,"Oregon, Washington","Benton, Lane, Linn, Clackamas, Lincoln, Marion..."
Willow Creek,0,0,0,California,"Humboldt, Trinity"
Yakima Valley,78,8,7,Washington,"Benton, Yakima"
Yamhill-Carlton,105,31,26,Oregon,"Washington, Yamhill"
York Mountain,1,0,0,California,San Luis Obispo
Yorkville Highlands,6,2,2,California,Mendocino
Yountville,19,8,8,California,Napa

In [111]:
# winereg_df.count()
# winereg_df.isnull().any()

Vineyards        False
Wineries         False
Tasting Rooms    False
State            False
County           False
dtype: bool

In [114]:
winereg_df.to_csv(os.path.join("..","Data","Clean","Wine_Regions_Clean.csv"))

In [119]:
file_alccongeo = pd.read_csv(os.path.join("..","Data","Raw","per_capita_alcohol_consumption_geographic_1977_2017.csv"), header=3)
print(file_alccongeo)

                                        geographic area    Year  Beer  Wine  \
0                                               Alabama  2017.0  1.06  0.26
1                                               Alabama  2016.0  1.09  0.26
2                                               Alabama  2015.0  1.12  0.26
3                                               Alabama  2014.0  1.13  0.25
4                                               Alabama  2013.0  1.14  0.25
5                                               Alabama  2012.0  1.16  0.24
6                                               Alabama  2011.0  1.16  0.24
7                                               Alabama  2010.0  1.17  0.23
8                                               Alabama  2009.0  1.19  0.22
9                                               Alabama  2008.0  1.22  0.22
10                                              Alabama  2007.0  1.23  0.22
11                                              Alabama  2006.0  1.21  0.21
12                                              Alabama  2005.0  1.18  0.20
13                                              Alabama  2004.0  1.19  0.20
14                                              Alabama  2003.0  1.19  0.19
15                                              Alabama  2002.0  1.18  0.21
16                                              Alabama  2001.0  1.16  0.17
17                                              Alabama  2000.0  1.19  0.18
18                                              Alabama  1999.0  1.18  0.17
19                                              Alabama  1998.0  1.16  0.17
20                                              Alabama  1997.0  1.14  0.16
21                                              Alabama  1996.0  1.17  0.18
22                                              Alabama  1995.0  1.14  0.16
23                                              Alabama  1994.0  1.16  0.17
24                                              Alabama  1993.0  1.14  0.17
25                                              Alabama  1992.0  1.02  0.19
26                                              Alabama  1991.0  1.00  0.17
27                                              Alabama  1990.0  1.12  0.18
28                                              Alabama  1989.0  1.12  0.17
29                                              Alabama  1988.0  1.12  0.19
...                                                 ...     ...   ...   ...
2267                                         U.S. total  2005.0  1.20  0.36
2268                                         U.S. total  2004.0  1.21  0.35
2269                                         U.S. total  2003.0  1.21  0.34
2270                                         U.S. total  2002.0  1.23  0.33
2271                                         U.S. total  2001.0  1.23  0.31
2272                                         U.S. total  2000.0  1.23  0.31
2273                                         U.S. total  1999.0  1.23  0.31
2274                                         U.S. total  1998.0  1.22  0.30
2275                                         U.S. total  1997.0  1.22  0.30
2276                                         U.S. total  1996.0  1.23  0.30
2277                                         U.S. total  1995.0  1.24  0.29
2278                                         U.S. total  1994.0  1.25  0.28
2279                                         U.S. total  1993.0  1.26  0.28
2280                                         U.S. total  1992.0  1.29  0.30
2281                                         U.S. total  1991.0  1.29  0.30
2282                                         U.S. total  1990.0  1.34  0.33
2283                                         U.S. total  1989.0  1.32  0.34
2284                                         U.S. total  1988.0  1.33  0.36
2285                                         U.S. total  1987.0  1.34  0.38
2286                                         U.S. total  1986.0  1.35  0.39
2287                                         U.S. total  1985.0  1.33  0.38
2288                                         U.S. total  1984.0  1.35  0.37
2289                                         U.S. total  1983.0  1.37  0.36
2290                                         U.S. total  1982.0  1.38  0.36
2291                                         U.S. total  1981.0  1.39  0.35
2292                                         U.S. total  1980.0  1.37  0.34
2293                                         U.S. total  1979.0  1.34  0.31
2294                                         U.S. total  1978.0  1.30  0.30
2295                                         U.S. total  1977.0  1.27  0.29
2296  Decile values (1= highest) apply only to State...     NaN   NaN   NaN

      Spirits  All beverages  all beverages
0        0.67           1.99            9.0
1        0.65           2.01            9.0
2        0.64           2.01            9.0
3        0.62           2.00            9.0
4        0.60           1.99            9.0
5        0.60           2.00            9.0
6        0.59           1.98            9.0
7        0.58           1.98            9.0
8        0.57           1.98            9.0
9        0.57           2.01            9.0
10       0.55           2.00            9.0
11       0.54           1.95            9.0
12       0.53           1.91            9.0
13       0.52           1.91            9.0
14       0.52           1.90            9.0
15       0.54           1.92            9.0
16       0.53           1.86            9.0
17       0.51           1.88            9.0
18       0.51           1.87            9.0
19       0.51           1.85            9.0
20       0.52           1.82            9.0
21       0.53           1.88            8.0
22       0.53           1.82            9.0
23       0.54           1.87            9.0
24       0.56           1.86            9.0
25       0.59           1.79           10.0
26       0.59           1.76           10.0
27       0.61           1.92            9.0
28       0.61           1.90            9.0
29       0.62           1.92            9.0
...       ...            ...            ...
2267     0.70           2.25            NaN
2268     0.68           2.24            NaN
2269     0.67           2.22            NaN
2270     0.64           2.20            NaN
2271     0.64           2.18            NaN
2272     0.64           2.19            NaN
2273     0.63           2.17            NaN
2274     0.62           2.15            NaN
2275     0.62           2.15            NaN
2276     0.63           2.16            NaN
2277     0.63           2.15            NaN
2278     0.65           2.18            NaN
2279     0.68           2.23            NaN
2280     0.71           2.30            NaN
2281     0.71           2.30            NaN
2282     0.77           2.45            NaN
2283     0.78           2.43            NaN
2284     0.79           2.49            NaN
2285     0.83           2.55            NaN
2286     0.84           2.58            NaN
2287     0.91           2.62            NaN
2288     0.94           2.65            NaN
2289     0.96           2.69            NaN
2290     0.98           2.72            NaN
2291     1.02           2.76            NaN
2292     1.04           2.75            NaN
2293     1.04           2.70            NaN
2294     1.05           2.66            NaN
2295     1.04           2.60            NaN
2296      NaN            NaN            NaN

[2297 rows x 7 columns]

In [120]:
alcohol_consump_geo = pd.DataFrame(file_alccongeo)
alcohol_consump_geo.set_index("geographic area", inplace = True)
alcohol_consump_geo.rename(columns = {'all beverages':'Decile all beverages'}, inplace = True)
alcohol_consump_geo

,Year,Beer,Wine,Spirits,All beverages,Decile all beverages
geographic area,,,,,,
Alabama,2017.0,1.06,0.26,0.67,1.99,9.0
Alabama,2016.0,1.09,0.26,0.65,2.01,9.0
Alabama,2015.0,1.12,0.26,0.64,2.01,9.0
Alabama,2014.0,1.13,0.25,0.62,2.00,9.0
Alabama,2013.0,1.14,0.25,0.60,1.99,9.0
Alabama,2012.0,1.16,0.24,0.60,2.00,9.0
Alabama,2011.0,1.16,0.24,0.59,1.98,9.0
Alabama,2010.0,1.17,0.23,0.58,1.98,9.0
Alabama,2009.0,1.19,0.22,0.57,1.98,9.0
Alabama,2008.0,1.22,0.22,0.57,2.01,9.0
Alabama,2007.0,1.23,0.22,0.55,2.00,9.0
Alabama,2006.0,1.21,0.21,0.54,1.95,9.0
Alabama,2005.0,1.18,0.20,0.53,1.91,9.0
Alabama,2004.0,1.19,0.20,0.52,1.91,9.0
Alabama,2003.0,1.19,0.19,0.52,1.90,9.0
Alabama,2002.0,1.18,0.21,0.54,1.92,9.0
Alabama,2001.0,1.16,0.17,0.53,1.86,9.0
Alabama,2000.0,1.19,0.18,0.51,1.88,9.0
Alabama,1999.0,1.18,0.17,0.51,1.87,9.0
Alabama,1998.0,1.16,0.17,0.51,1.85,9.0
Alabama,1997.0,1.14,0.16,0.52,1.82,9.0
Alabama,1996.0,1.17,0.18,0.53,1.88,8.0
Alabama,1995.0,1.14,0.16,0.53,1.82,9.0
Alabama,1994.0,1.16,0.17,0.54,1.87,9.0
Alabama,1993.0,1.14,0.17,0.56,1.86,9.0
Alabama,1992.0,1.02,0.19,0.59,1.79,10.0
Alabama,1991.0,1.00,0.17,0.59,1.76,10.0
Alabama,1990.0,1.12,0.18,0.61,1.92,9.0
Alabama,1989.0,1.12,0.17,0.61,1.90,9.0
Alabama,1988.0,1.12,0.19,0.62,1.92,9.0
...,...,...,...,...,...,...
U.S. total,2005.0,1.20,0.36,0.70,2.25,NaN
U.S. total,2004.0,1.21,0.35,0.68,2.24,NaN
U.S. total,2003.0,1.21,0.34,0.67,2.22,NaN
U.S. total,2002.0,1.23,0.33,0.64,2.20,NaN
U.S. total,2001.0,1.23,0.31,0.64,2.18,NaN
U.S. total,2000.0,1.23,0.31,0.64,2.19,NaN
U.S. total,1999.0,1.23,0.31,0.63,2.17,NaN
U.S. total,1998.0,1.22,0.30,0.62,2.15,NaN
U.S. total,1997.0,1.22,0.30,0.62,2.15,NaN
U.S. total,1996.0,1.23,0.30,0.63,2.16,NaN
U.S. total,1995.0,1.24,0.29,0.63,2.15,NaN
U.S. total,1994.0,1.25,0.28,0.65,2.18,NaN
U.S. total,1993.0,1.26,0.28,0.68,2.23,NaN
U.S. total,1992.0,1.29,0.30,0.71,2.30,NaN
U.S. total,1991.0,1.29,0.30,0.71,2.30,NaN
U.S. total,1990.0,1.34,0.33,0.77,2.45,NaN
U.S. total,1989.0,1.32,0.34,0.78,2.43,NaN
U.S. total,1988.0,1.33,0.36,0.79,2.49,NaN
U.S. total,1987.0,1.34,0.38,0.83,2.55,NaN
U.S. total,1986.0,1.35,0.39,0.84,2.58,NaN
U.S. total,1985.0,1.33,0.38,0.91,2.62,NaN
U.S. total,1984.0,1.35,0.37,0.94,2.65,NaN
U.S. total,1983.0,1.37,0.36,0.96,2.69,NaN
U.S. total,1982.0,1.38,0.36,0.98,2.72,NaN
U.S. total,1981.0,1.39,0.35,1.02,2.76,NaN
U.S. total,1980.0,1.37,0.34,1.04,2.75,NaN
U.S. total,1979.0,1.34,0.31,1.04,2.70,NaN
U.S. total,1978.0,1.30,0.30,1.05,2.66,NaN
U.S. total,1977.0,1.27,0.29,1.04,2.60,NaN
Decile values (1= highest) apply only to State–level data. Numbers may not sum because of rounding.,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
# alcohol_consump_geo.count()
# alcohol_consump_geo.isnull().any()
# alcohol_consump_geo.loc[alcohol_consump_geo.isnull().any(axis=1)]

,Year,Beer,Wine,Spirits,All beverages,Decile all beverages
geographic area,,,,,,
Northeast region,2017.0,1.01,0.52,0.87,2.40,NaN
Northeast region,2016.0,1.03,0.52,0.86,2.41,NaN
Northeast region,2015.0,1.03,0.51,0.84,2.38,NaN
Northeast region,2014.0,1.03,0.52,0.84,2.39,NaN
Northeast region,2013.0,1.05,0.51,0.83,2.40,NaN
Northeast region,2012.0,1.06,0.51,0.82,2.39,NaN
Northeast region,2011.0,1.05,0.50,0.80,2.36,NaN
Northeast region,2010.0,1.06,0.49,0.78,2.33,NaN
Northeast region,2009.0,1.07,0.48,0.77,2.31,NaN
Northeast region,2008.0,1.09,0.47,0.76,2.31,NaN
Northeast region,2007.0,1.09,0.47,0.75,2.31,NaN
Northeast region,2006.0,1.07,0.45,0.73,2.25,NaN
Northeast region,2005.0,1.07,0.44,0.72,2.22,NaN
Northeast region,2004.0,1.07,0.43,0.70,2.20,NaN
Northeast region,2003.0,1.08,0.41,0.68,2.17,NaN
Northeast region,2002.0,1.10,0.40,0.66,2.16,NaN
Northeast region,2001.0,1.10,0.38,0.64,2.13,NaN
Northeast region,2000.0,1.08,0.38,0.66,2.12,NaN
Northeast region,1999.0,1.07,0.38,0.63,2.08,NaN
Northeast region,1998.0,1.07,0.37,0.61,2.05,NaN
Northeast region,1997.0,1.07,0.36,0.63,2.06,NaN
Northeast region,1996.0,1.07,0.36,0.64,2.06,NaN
Northeast region,1995.0,1.11,0.35,0.64,2.11,NaN
Northeast region,1994.0,1.11,0.34,0.67,2.12,NaN
Northeast region,1993.0,1.13,0.34,0.68,2.15,NaN
Northeast region,1992.0,1.14,0.35,0.72,2.21,NaN
Northeast region,1991.0,1.19,0.34,0.73,2.26,NaN
Northeast region,1990.0,1.23,0.38,0.80,2.41,NaN
Northeast region,1989.0,1.22,0.39,0.84,2.44,NaN
Northeast region,1988.0,1.25,0.40,0.86,2.51,NaN
...,...,...,...,...,...,...
U.S. total,2005.0,1.20,0.36,0.70,2.25,NaN
U.S. total,2004.0,1.21,0.35,0.68,2.24,NaN
U.S. total,2003.0,1.21,0.34,0.67,2.22,NaN
U.S. total,2002.0,1.23,0.33,0.64,2.20,NaN
U.S. total,2001.0,1.23,0.31,0.64,2.18,NaN
U.S. total,2000.0,1.23,0.31,0.64,2.19,NaN
U.S. total,1999.0,1.23,0.31,0.63,2.17,NaN
U.S. total,1998.0,1.22,0.30,0.62,2.15,NaN
U.S. total,1997.0,1.22,0.30,0.62,2.15,NaN
U.S. total,1996.0,1.23,0.30,0.63,2.16,NaN
U.S. total,1995.0,1.24,0.29,0.63,2.15,NaN
U.S. total,1994.0,1.25,0.28,0.65,2.18,NaN
U.S. total,1993.0,1.26,0.28,0.68,2.23,NaN
U.S. total,1992.0,1.29,0.30,0.71,2.30,NaN
U.S. total,1991.0,1.29,0.30,0.71,2.30,NaN
U.S. total,1990.0,1.34,0.33,0.77,2.45,NaN
U.S. total,1989.0,1.32,0.34,0.78,2.43,NaN
U.S. total,1988.0,1.33,0.36,0.79,2.49,NaN
U.S. total,1987.0,1.34,0.38,0.83,2.55,NaN
U.S. total,1986.0,1.35,0.39,0.84,2.58,NaN
U.S. total,1985.0,1.33,0.38,0.91,2.62,NaN
U.S. total,1984.0,1.35,0.37,0.94,2.65,NaN
U.S. total,1983.0,1.37,0.36,0.96,2.69,NaN
U.S. total,1982.0,1.38,0.36,0.98,2.72,NaN
U.S. total,1981.0,1.39,0.35,1.02,2.76,NaN
U.S. total,1980.0,1.37,0.34,1.04,2.75,NaN
U.S. total,1979.0,1.34,0.31,1.04,2.70,NaN
U.S. total,1978.0,1.30,0.30,1.05,2.66,NaN
U.S. total,1977.0,1.27,0.29,1.04,2.60,NaN
Decile values (1= highest) apply only to State–level data. Numbers may not sum because of rounding.,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
alcohol_consump_geo = alcohol_consump_geo[:-1]
alcohol_consump_geo

,Year,Beer,Wine,Spirits,All beverages,Decile all beverages
geographic area,,,,,,
Alabama,2017.0,1.06,0.26,0.67,1.99,9.0
Alabama,2016.0,1.09,0.26,0.65,2.01,9.0
Alabama,2015.0,1.12,0.26,0.64,2.01,9.0
Alabama,2014.0,1.13,0.25,0.62,2.00,9.0
Alabama,2013.0,1.14,0.25,0.60,1.99,9.0
Alabama,2012.0,1.16,0.24,0.60,2.00,9.0
Alabama,2011.0,1.16,0.24,0.59,1.98,9.0
Alabama,2010.0,1.17,0.23,0.58,1.98,9.0
Alabama,2009.0,1.19,0.22,0.57,1.98,9.0
Alabama,2008.0,1.22,0.22,0.57,2.01,9.0
Alabama,2007.0,1.23,0.22,0.55,2.00,9.0
Alabama,2006.0,1.21,0.21,0.54,1.95,9.0
Alabama,2005.0,1.18,0.20,0.53,1.91,9.0
Alabama,2004.0,1.19,0.20,0.52,1.91,9.0
Alabama,2003.0,1.19,0.19,0.52,1.90,9.0
Alabama,2002.0,1.18,0.21,0.54,1.92,9.0
Alabama,2001.0,1.16,0.17,0.53,1.86,9.0
Alabama,2000.0,1.19,0.18,0.51,1.88,9.0
Alabama,1999.0,1.18,0.17,0.51,1.87,9.0
Alabama,1998.0,1.16,0.17,0.51,1.85,9.0
Alabama,1997.0,1.14,0.16,0.52,1.82,9.0
Alabama,1996.0,1.17,0.18,0.53,1.88,8.0
Alabama,1995.0,1.14,0.16,0.53,1.82,9.0
Alabama,1994.0,1.16,0.17,0.54,1.87,9.0
Alabama,1993.0,1.14,0.17,0.56,1.86,9.0
Alabama,1992.0,1.02,0.19,0.59,1.79,10.0
Alabama,1991.0,1.00,0.17,0.59,1.76,10.0
Alabama,1990.0,1.12,0.18,0.61,1.92,9.0
Alabama,1989.0,1.12,0.17,0.61,1.90,9.0
Alabama,1988.0,1.12,0.19,0.62,1.92,9.0
...,...,...,...,...,...,...
U.S. total,2006.0,1.20,0.37,0.71,2.28,NaN
U.S. total,2005.0,1.20,0.36,0.70,2.25,NaN
U.S. total,2004.0,1.21,0.35,0.68,2.24,NaN
U.S. total,2003.0,1.21,0.34,0.67,2.22,NaN
U.S. total,2002.0,1.23,0.33,0.64,2.20,NaN
U.S. total,2001.0,1.23,0.31,0.64,2.18,NaN
U.S. total,2000.0,1.23,0.31,0.64,2.19,NaN
U.S. total,1999.0,1.23,0.31,0.63,2.17,NaN
U.S. total,1998.0,1.22,0.30,0.62,2.15,NaN
U.S. total,1997.0,1.22,0.30,0.62,2.15,NaN
U.S. total,1996.0,1.23,0.30,0.63,2.16,NaN
U.S. total,1995.0,1.24,0.29,0.63,2.15,NaN
U.S. total,1994.0,1.25,0.28,0.65,2.18,NaN
U.S. total,1993.0,1.26,0.28,0.68,2.23,NaN
U.S. total,1992.0,1.29,0.30,0.71,2.30,NaN
U.S. total,1991.0,1.29,0.30,0.71,2.30,NaN
U.S. total,1990.0,1.34,0.33,0.77,2.45,NaN
U.S. total,1989.0,1.32,0.34,0.78,2.43,NaN
U.S. total,1988.0,1.33,0.36,0.79,2.49,NaN
U.S. total,1987.0,1.34,0.38,0.83,2.55,NaN
U.S. total,1986.0,1.35,0.39,0.84,2.58,NaN
U.S. total,1985.0,1.33,0.38,0.91,2.62,NaN
U.S. total,1984.0,1.35,0.37,0.94,2.65,NaN
U.S. total,1983.0,1.37,0.36,0.96,2.69,NaN
U.S. total,1982.0,1.38,0.36,0.98,2.72,NaN
U.S. total,1981.0,1.39,0.35,1.02,2.76,NaN
U.S. total,1980.0,1.37,0.34,1.04,2.75,NaN
U.S. total,1979.0,1.34,0.31,1.04,2.70,NaN
U.S. total,1978.0,1.30,0.30,1.05,2.66,NaN
U.S. total,1977.0,1.27,0.29,1.04,2.60,NaN

In [135]:
alcohol_consump_geo_df = alcohol_consump_geo.fillna(value=0)
alcohol_consump_geo_df

,Year,Beer,Wine,Spirits,All beverages,Decile all beverages
geographic area,,,,,,
Alabama,2017.0,1.06,0.26,0.67,1.99,9.0
Alabama,2016.0,1.09,0.26,0.65,2.01,9.0
Alabama,2015.0,1.12,0.26,0.64,2.01,9.0
Alabama,2014.0,1.13,0.25,0.62,2.00,9.0
Alabama,2013.0,1.14,0.25,0.60,1.99,9.0
Alabama,2012.0,1.16,0.24,0.60,2.00,9.0
Alabama,2011.0,1.16,0.24,0.59,1.98,9.0
Alabama,2010.0,1.17,0.23,0.58,1.98,9.0
Alabama,2009.0,1.19,0.22,0.57,1.98,9.0
Alabama,2008.0,1.22,0.22,0.57,2.01,9.0
Alabama,2007.0,1.23,0.22,0.55,2.00,9.0
Alabama,2006.0,1.21,0.21,0.54,1.95,9.0
Alabama,2005.0,1.18,0.20,0.53,1.91,9.0
Alabama,2004.0,1.19,0.20,0.52,1.91,9.0
Alabama,2003.0,1.19,0.19,0.52,1.90,9.0
Alabama,2002.0,1.18,0.21,0.54,1.92,9.0
Alabama,2001.0,1.16,0.17,0.53,1.86,9.0
Alabama,2000.0,1.19,0.18,0.51,1.88,9.0
Alabama,1999.0,1.18,0.17,0.51,1.87,9.0
Alabama,1998.0,1.16,0.17,0.51,1.85,9.0
Alabama,1997.0,1.14,0.16,0.52,1.82,9.0
Alabama,1996.0,1.17,0.18,0.53,1.88,8.0
Alabama,1995.0,1.14,0.16,0.53,1.82,9.0
Alabama,1994.0,1.16,0.17,0.54,1.87,9.0
Alabama,1993.0,1.14,0.17,0.56,1.86,9.0
Alabama,1992.0,1.02,0.19,0.59,1.79,10.0
Alabama,1991.0,1.00,0.17,0.59,1.76,10.0
Alabama,1990.0,1.12,0.18,0.61,1.92,9.0
Alabama,1989.0,1.12,0.17,0.61,1.90,9.0
Alabama,1988.0,1.12,0.19,0.62,1.92,9.0
...,...,...,...,...,...,...
U.S. total,2006.0,1.20,0.37,0.71,2.28,0.0
U.S. total,2005.0,1.20,0.36,0.70,2.25,0.0
U.S. total,2004.0,1.21,0.35,0.68,2.24,0.0
U.S. total,2003.0,1.21,0.34,0.67,2.22,0.0
U.S. total,2002.0,1.23,0.33,0.64,2.20,0.0
U.S. total,2001.0,1.23,0.31,0.64,2.18,0.0
U.S. total,2000.0,1.23,0.31,0.64,2.19,0.0
U.S. total,1999.0,1.23,0.31,0.63,2.17,0.0
U.S. total,1998.0,1.22,0.30,0.62,2.15,0.0
U.S. total,1997.0,1.22,0.30,0.62,2.15,0.0
U.S. total,1996.0,1.23,0.30,0.63,2.16,0.0
U.S. total,1995.0,1.24,0.29,0.63,2.15,0.0
U.S. total,1994.0,1.25,0.28,0.65,2.18,0.0
U.S. total,1993.0,1.26,0.28,0.68,2.23,0.0
U.S. total,1992.0,1.29,0.30,0.71,2.30,0.0
U.S. total,1991.0,1.29,0.30,0.71,2.30,0.0
U.S. total,1990.0,1.34,0.33,0.77,2.45,0.0
U.S. total,1989.0,1.32,0.34,0.78,2.43,0.0
U.S. total,1988.0,1.33,0.36,0.79,2.49,0.0
U.S. total,1987.0,1.34,0.38,0.83,2.55,0.0
U.S. total,1986.0,1.35,0.39,0.84,2.58,0.0
U.S. total,1985.0,1.33,0.38,0.91,2.62,0.0
U.S. total,1984.0,1.35,0.37,0.94,2.65,0.0
U.S. total,1983.0,1.37,0.36,0.96,2.69,0.0
U.S. total,1982.0,1.38,0.36,0.98,2.72,0.0
U.S. total,1981.0,1.39,0.35,1.02,2.76,0.0
U.S. total,1980.0,1.37,0.34,1.04,2.75,0.0
U.S. total,1979.0,1.34,0.31,1.04,2.70,0.0
U.S. total,1978.0,1.30,0.30,1.05,2.66,0.0
U.S. total,1977.0,1.27,0.29,1.04,2.60,0.0

In [136]:
alcohol_consump_geo_df.to_csv(os.path.join("..","Data","Clean","per_capita_alcohol_consumption_geographic_1977_2017_clean.csv"))

In [137]:
file_rent = pd.read_csv(os.path.join("..","Data","Raw","NLIHC_OOR_2018.csv"))
print(file_rent)

     Unnamed: 0  Type  ST         STNAME                       COUNTY/METRO  \
0         STATE     1  AK         Alaska                                NaN
1      NONMETRO     2  AK         Alaska                                NaN
2         METRO     3  AK         Alaska                     Anchorage HMFA
3         METRO     3  AK         Alaska                      Fairbanks MSA
4         METRO     3  AK         Alaska     Matanuska-Susitna Borough HMFA
5        COUNTY     4  AK         Alaska             Aleutians East Borough
6        COUNTY     4  AK         Alaska         Aleutians West Census Area
7        COUNTY     4  AK         Alaska             Anchorage Municipality
8        COUNTY     4  AK         Alaska                 Bethel Census Area
9        COUNTY     4  AK         Alaska                Bristol Bay Borough
10       COUNTY     4  AK         Alaska                     Denali Borough
11       COUNTY     4  AK         Alaska             Dillingham Census Area
12       COUNTY     4  AK         Alaska       Fairbanks North Star Borough
13       COUNTY     4  AK         Alaska                     Haines Borough
14       COUNTY     4  AK         Alaska          Hoonah-Angoon Census Area
15       COUNTY     4  AK         Alaska            Juneau City and Borough
16       COUNTY     4  AK         Alaska            Kenai Peninsula Borough
17       COUNTY     4  AK         Alaska          Ketchikan Gateway Borough
18       COUNTY     4  AK         Alaska              Kodiak Island Borough
19       COUNTY     4  AK         Alaska               Kusilvak Census Area
20       COUNTY     4  AK         Alaska         Lake and Peninsula Borough
21       COUNTY     4  AK         Alaska          Matanuska-Susitna Borough
22       COUNTY     4  AK         Alaska                   Nome Census Area
23       COUNTY     4  AK         Alaska                North Slope Borough
24       COUNTY     4  AK         Alaska           Northwest Arctic Borough
25       COUNTY     4  AK         Alaska             Petersburg Census Area
26       COUNTY     4  AK         Alaska  Prince of Wales-Hyder Census Area
27       COUNTY     4  AK         Alaska             Sitka City and Borough
28       COUNTY     4  AK         Alaska               Skagway Municipality
29       COUNTY     4  AK         Alaska    Southeast Fairbanks Census Area
...         ...   ...  ..            ...                                ...
3926     COUNTY     4  WV  West Virginia                      Wirt County †
3927     COUNTY     4  WV  West Virginia                        Wood County
3928     COUNTY     4  WV  West Virginia                     Wyoming County
3929      STATE     1  WY        Wyoming                                NaN
3930   NONMETRO     2  WY        Wyoming                                NaN
3931      METRO     3  WY        Wyoming                         Casper MSA
3932      METRO     3  WY        Wyoming                       Cheyenne MSA
3933     COUNTY     4  WY        Wyoming                      Albany County
3934     COUNTY     4  WY        Wyoming                    Big Horn County
3935     COUNTY     4  WY        Wyoming                    Campbell County
3936     COUNTY     4  WY        Wyoming                      Carbon County
3937     COUNTY     4  WY        Wyoming                    Converse County
3938     COUNTY     4  WY        Wyoming                       Crook County
3939     COUNTY     4  WY        Wyoming                     Fremont County
3940     COUNTY     4  WY        Wyoming                      Goshen County
3941     COUNTY     4  WY        Wyoming                 Hot Springs County
3942     COUNTY     4  WY        Wyoming                     Johnson County
3943     COUNTY     4  WY        Wyoming                     Laramie County
3944     COUNTY     4  WY        Wyoming                     Lincoln County
3945     COUNTY     4  WY        Wyoming                     Natrona County
3946     COUNTY     4  WY        Wyoming                  Niobrara County †
3947     COUNTY     4  WY        Wyoming                        Park County
3948     COUNTY     4  WY        Wyoming                      Platte County
3949     COUNTY     4  WY        Wyoming                    Sheridan County
3950     COUNTY     4  WY        Wyoming                    Sublette County
3951     COUNTY     4  WY        Wyoming                  Sweetwater County
3952     COUNTY     4  WY        Wyoming                       Teton County
3953     COUNTY     4  WY        Wyoming                       Uinta County
3954     COUNTY     4  WY        Wyoming                    Washakie County
3955     COUNTY     4  WY        Wyoming                      Weston County

      Total households (2012-2016)  Renter households (2012-2016)  \
0                         250235.0                        90922.0
1                          79124.0                        27465.0
2                         104969.0                        41702.0
3                          35303.0                        14298.0
4                          30839.0                         7457.0
5                            788.0                          345.0
6                           1186.0                          850.0
7                         104969.0                        41702.0
8                           4555.0                         1634.0
9                            360.0                          163.0
10                           707.0                          174.0
11                          1375.0                          543.0
12                         35303.0                        14298.0
13                          1170.0                          367.0
14                           836.0                          239.0
15                         12138.0                         4322.0
16                         21481.0                         6099.0
17                          5209.0                         2109.0
18                          4585.0                         1800.0
19                          1734.0                          450.0
20                           468.0                          150.0
21                         30839.0                         7457.0
22                          2879.0                         1147.0
23                          2018.0                         1008.0
24                          1904.0                          860.0
25                          1237.0                          397.0
26                          2267.0                          642.0
27                          3504.0                         1544.0
28                           428.0                          195.0
29                          2085.0                          591.0
...                            ...                            ...
3926                        2432.0                          390.0
3927                       36225.0                        10563.0
3928                        9222.0                         1791.0
3929                      226985.0                        71244.0
3930                      157201.0                        48348.0
3931                       32422.0                        11124.0
3932                       37362.0                        11772.0
3933                       15565.0                         7959.0
3934                        4459.0                         1180.0
3935                       17534.0                         5293.0
3936                        6095.0                         1822.0
3937                        5576.0                         1481.0
3938                        2976.0                          628.0
3939                       15159.0                         4441.0
3940                        5350.0                         1266.0
3941                        2262.0                          594.0
3942                        3668.0                          980.0
3943                       37362.0                        11772.0
3944                        7002.0                         1462.0
3945                       32422.0                        11124.0
3946                         981.0                          292.0
3947                       11826.0                         3314.0
3948                        3680.0                          904.0
3949                       12697.0                         4009.0
3950                        3203.0                          918.0
3951                       16533.0                         4539.0
3952                        8576.0                         3444.0
3953                        7432.0                         2205.0
3954                        3493.0                          889.0
3955                        3134.0                          728.0

      % of total households that are renters (2012-2016)  Minimum wage  \
0                                                  36.0           9.84
1                                                  35.0           9.84
2                                                  40.0           9.84
3                                                  41.0           9.84
4                                                  24.0           9.84
5                                                  44.0           9.84
6                                                  72.0           9.84
7                                                  40.0           9.84
8                                                  36.0           9.84
9                                                  45.0           9.84
10                                                 25.0           9.84
11                                                 39.0           9.84
12                                                 41.0           9.84
13                                                 31.0           9.84
14                                                 29.0           9.84
15                                                 36.0           9.84
16                                                 28.0           9.84
17                                                 40.0           9.84
18                                                 39.0           9.84
19                                                 26.0           9.84
20                                                 32.0           9.84
21                                                 24.0           9.84
22                                                 40.0           9.84
23                                                 50.0           9.84
24                                                 45.0           9.84
25                                                 32.0           9.84
26                                                 28.0           9.84
27                                                 44.0           9.84
28                                                 46.0           9.84
29                                                 28.0           9.84
...                                                 ...            ...
3926                                               16.0           8.75
3927                                               29.0           8.75
3928                                               19.0           8.75
3929                                               31.0           7.25
3930                                               31.0           7.25
3931                                               34.0           7.25
3932                                               32.0           7.25
3933                                               51.0           7.25
3934                                               26.0           7.25
3935                                               30.0           7.25
3936                                               30.0           7.25
3937                                               27.0           7.25
3938                                               21.0           7.25
3939                                               29.0           7.25
3940                                               24.0           7.25
3941                                               26.0           7.25
3942                                               27.0           7.25
3943                                               32.0           7.25
3944                                               21.0           7.25
3945                                               34.0           7.25
3946                                               30.0           7.25
3947                                               28.0           7.25
3948                                               25.0           7.25
3949                                               32.0           7.25
3950                                               29.0           7.25
3951                                               27.0           7.25
3952                                               40.0           7.25
3953                                               30.0           7.25
3954                                               25.0           7.25
3955                                               23.0           7.25

      Estimated mean renter wage  ...  \
0                          18.84  ...
1                          22.96  ...
2                          17.82  ...
3                          16.30  ...
4                          11.11  ...
5                          25.02  ...
6                          27.77  ...
7                          17.82  ...
8                          20.09  ...
9                          19.42  ...
10                         24.50  ...
11                         18.19  ...
12                         16.30  ...
13                         12.91  ...
14                          9.61  ...
15                         14.86  ...
16                         14.98  ...
17                         14.52  ...
18                         13.99  ...
19                         12.56  ...
20                         20.85  ...
21                         11.11  ...
22                         23.88  ...
23                         54.27  ...
24                         40.46  ...
25                          9.15  ...
26                         13.35  ...
27                         13.96  ...
28                         14.86  ...
29                         26.90  ...
...                          ...  ...
3926                         NaN  ...
3927                       10.25  ...
3928                       12.20  ...
3929                       14.25  ...
3930                       14.43  ...
3931                       15.34  ...
3932                       12.34  ...
3933                        8.79  ...
3934                       11.05  ...
3935                       16.76  ...
3936                       20.00  ...
3937                       15.55  ...
3938                       17.91  ...
3939                       11.79  ...
3940                       11.77  ...
3941                       12.79  ...
3942                       11.59  ...
3943                       12.34  ...
3944                       14.07  ...
3945                       15.34  ...
3946                         NaN  ...
3947                       12.57  ...
3948                       15.56  ...
3949                       12.03  ...
3950                       17.30  ...
3951                       18.93  ...
3952                       15.00  ...
3953                       10.18  ...
3954                       11.85  ...
3955                       12.76  ...

      Work hours per week at min. wage needed to afford 0 bdrm FMR  \
0                                                  69.0
1                                                  68.0
2                                                  72.0
3                                                  68.0
4                                                  58.0
5                                                  59.0
6                                                  81.0
7                                                  72.0
8                                                  83.0
9                                                  70.0
10                                                 81.0
11                                                 79.0
12                                                 68.0
13                                                 55.0
14                                                 42.0
15                                                 71.0
16                                                 64.0
17                                                 63.0
18                                                 70.0
19                                                 52.0
20                                                 49.0
21                                                 58.0
22                                                 76.0
23                                                 72.0
24                                                 84.0
25                                                 54.0
26                                                 62.0
27                                                 71.0
28                                                 75.0
29                                                 68.0
...                                                 ...
3926                                               47.0
3927                                               47.0
3928                                               47.0
3929                                               65.0
3930                                               63.0
3931                                               70.0
3932                                               70.0
3933                                               59.0
3934                                               52.0
3935                                               74.0
3936                                               60.0
3937                                               58.0
3938                                               60.0
3939                                               54.0
3940                                               56.0
3941                                               52.0
3942                                               65.0
3943                                               70.0
3944                                               64.0
3945                                               70.0
3946                                               52.0
3947                                               58.0
3948                                               52.0
3949                                               67.0
3950                                               65.0
3951                                               64.0
3952                                               90.0
3953                                               55.0
3954                                               52.0
3955                                               60.0

      Work hours per week at min. wage needed to afford 1 bdrm FMR  \
0                                                  78.0
1                                                  76.0
2                                                  81.0
3                                                  80.0
4                                                  65.0
5                                                  72.0
6                                                  96.0
7                                                  81.0
8                                                 101.0
9                                                  74.0
10                                                 88.0
11                                                 82.0
12                                                 80.0
13                                                 67.0
14                                                 51.0

In [139]:
rent_df = pd.DataFrame(file_rent)
rent_df.head()

,Unnamed: 0,Type,ST,STNAME,COUNTY/METRO,Total households (2012-2016),Renter households (2012-2016),% of total households that are renters (2012-2016),Minimum wage,Estimated mean renter wage,...,Work hours per week at min. wage needed to afford 0 bdrm FMR,Work hours per week at min. wage needed to afford 1 bdrm FMR,Work hours per week at min. wage needed to afford 2 bdrm FMR,Work hours per week at min. wage needed to afford 3 bdrm FMR,Work hours per week at min. wage needed to afford 4 bdrm FMR,Work hours per week at mean renter wage needed to afford 0 bdrm FMR,Work hours per week at mean renter wage needed to afford 1 bdrm FMR,Work hours per week at mean renter wage needed to afford 2 bdrm FMR,Work hours per week at mean renter wage needed to afford 3 bdrm FMR,Work hours per week at mean renter wage needed to afford 4 bdrm FMR
0,STATE,1,AK,Alaska,NaN,250235.0,90922.0,36.0,9.84,18.84,...,69.0,78.0,101.0,143.0,172.0,36.0,41.0,53.0,75.0,90.0
1,NONMETRO,2,AK,Alaska,NaN,79124.0,27465.0,35.0,9.84,22.96,...,68.0,76.0,96.0,128.0,151.0,29.0,33.0,41.0,55.0,65.0
2,METRO,3,AK,Alaska,Anchorage HMFA,104969.0,41702.0,40.0,9.84,17.82,...,72.0,81.0,105.0,152.0,184.0,40.0,45.0,58.0,84.0,102.0
3,METRO,3,AK,Alaska,Fairbanks MSA,35303.0,14298.0,41.0,9.84,16.30,...,68.0,80.0,107.0,156.0,188.0,41.0,49.0,65.0,94.0,114.0
4,METRO,3,AK,Alaska,Matanuska-Susitna Borough HMFA,30839.0,7457.0,24.0,9.84,11.11,...,58.0,65.0,87.0,126.0,153.0,51.0,58.0,77.0,112.0,135.0

In [142]:
list(rent_df.columns.values)

['Unnamed: 0',
 'Type',
 'ST',
 'STNAME',
 'COUNTY/METRO',
 'Total households (2012-2016)',
 'Renter households (2012-2016)',
 '% of total households that are renters (2012-2016)',
 'Minimum wage',
 'Estimated mean renter wage',
 'SSI monthly payment',
 'Zero bedroom FMR',
 'One bedroom FMR',
 'Two bedroom FMR',
 'Three bedroom FMR',
 'Four bedroom FMR',
 'Annual AMI',
 '30% of AMI ',
 'Estimated renter median income',
 'Rent affordable at renter median income',
 'Rent affordable at 30% of AMI',
 'Rent affordable with full-time job paying min wage',
 'Rent affordable with full-time job paying mean renter wage',
 'Rent affordable to SSI recipient',
 'Income needed to afford 0 bdrm FMR',
 'Income needed to afford 1 bdrm FMR',
 'Income needed to afford 2 bdrm FMR',
 'Income needed to afford 3 bdrm FMR',
 'Income needed to afford 4 bdrm FMR',
 'Housing Wage for 0 bdrm FMR',
 'Housing Wage for 1 bdrm FMR',
 'Housing Wage for 2 bdrm FMR',
 'Housing Wage for 3 bdrm FMR',
 'Housing Wage for 4 bdrm FMR',
 'Work hours per week at min. wage needed to afford 0 bdrm FMR',
 'Work hours per week at min. wage needed to afford 1 bdrm FMR',
 'Work hours per week at min. wage needed to afford 2 bdrm FMR',
 'Work hours per week at min. wage needed to afford 3 bdrm FMR',
 'Work hours per week at min. wage needed to afford 4 bdrm FMR',
 'Work hours per week at mean renter wage needed to afford 0 bdrm FMR',
 'Work hours per week at mean renter wage needed to afford 1 bdrm FMR',
 'Work hours per week at mean renter wage needed to afford 2 bdrm FMR',
 'Work hours per week at mean renter wage needed to afford 3 bdrm FMR',
 'Work hours per week at mean renter wage needed to afford 4 bdrm FMR']

In [143]:
rent_df.rename(columns = {'Unnamed: 0' : 'Type', 'Type' : 'Type Code'}, inplace = True)
rent_df

,Type,Type Code,ST,STNAME,COUNTY/METRO,Total households (2012-2016),Renter households (2012-2016),% of total households that are renters (2012-2016),Minimum wage,Estimated mean renter wage,...,Work hours per week at min. wage needed to afford 0 bdrm FMR,Work hours per week at min. wage needed to afford 1 bdrm FMR,Work hours per week at min. wage needed to afford 2 bdrm FMR,Work hours per week at min. wage needed to afford 3 bdrm FMR,Work hours per week at min. wage needed to afford 4 bdrm FMR,Work hours per week at mean renter wage needed to afford 0 bdrm FMR,Work hours per week at mean renter wage needed to afford 1 bdrm FMR,Work hours per week at mean renter wage needed to afford 2 bdrm FMR,Work hours per week at mean renter wage needed to afford 3 bdrm FMR,Work hours per week at mean renter wage needed to afford 4 bdrm FMR
0,STATE,1,AK,Alaska,NaN,250235.0,90922.0,36.0,9.84,18.84,...,69.0,78.0,101.0,143.0,172.0,36.0,41.0,53.0,75.0,90.0
1,NONMETRO,2,AK,Alaska,NaN,79124.0,27465.0,35.0,9.84,22.96,...,68.0,76.0,96.0,128.0,151.0,29.0,33.0,41.0,55.0,65.0
2,METRO,3,AK,Alaska,Anchorage HMFA,104969.0,41702.0,40.0,9.84,17.82,...,72.0,81.0,105.0,152.0,184.0,40.0,45.0,58.0,84.0,102.0
3,METRO,3,AK,Alaska,Fairbanks MSA,35303.0,14298.0,41.0,9.84,16.30,...,68.0,80.0,107.0,156.0,188.0,41.0,49.0,65.0,94.0,114.0
4,METRO,3,AK,Alaska,Matanuska-Susitna Borough HMFA,30839.0,7457.0,24.0,9.84,11.11,...,58.0,65.0,87.0,126.0,153.0,51.0,58.0,77.0,112.0,135.0
5,COUNTY,4,AK,Alaska,Aleutians East Borough,788.0,345.0,44.0,9.84,25.02,...,59.0,72.0,82.0,103.0,112.0,23.0,28.0,32.0,41.0,44.0
6,COUNTY,4,AK,Alaska,Aleutians West Census Area,1186.0,850.0,72.0,9.84,27.77,...,81.0,96.0,127.0,160.0,196.0,29.0,34.0,45.0,57.0,69.0
7,COUNTY,4,AK,Alaska,Anchorage Municipality,104969.0,41702.0,40.0,9.84,17.82,...,72.0,81.0,105.0,152.0,184.0,40.0,45.0,58.0,84.0,102.0
8,COUNTY,4,AK,Alaska,Bethel Census Area,4555.0,1634.0,36.0,9.84,20.09,...,83.0,101.0,116.0,145.0,158.0,41.0,49.0,57.0,71.0,77.0
9,COUNTY,4,AK,Alaska,Bristol Bay Borough,360.0,163.0,45.0,9.84,19.42,...,70.0,74.0,98.0,126.0,133.0,35.0,38.0,49.0,64.0,67.0
10,COUNTY,4,AK,Alaska,Denali Borough,707.0,174.0,25.0,9.84,24.50,...,81.0,88.0,114.0,144.0,175.0,33.0,35.0,46.0,58.0,70.0
11,COUNTY,4,AK,Alaska,Dillingham Census Area,1375.0,543.0,39.0,9.84,18.19,...,79.0,82.0,94.0,130.0,144.0,43.0,44.0,51.0,70.0,78.0
12,COUNTY,4,AK,Alaska,Fairbanks North Star Borough,35303.0,14298.0,41.0,9.84,16.30,...,68.0,80.0,107.0,156.0,188.0,41.0,49.0,65.0,94.0,114.0
13,COUNTY,4,AK,Alaska,Haines Borough,1170.0,367.0,31.0,9.84,12.91,...,55.0,67.0,77.0,97.0,119.0,42.0,51.0,59.0,74.0,90.0
14,COUNTY,4,AK,Alaska,Hoonah-Angoon Census Area,836.0,239.0,29.0,9.84,9.61,...,42.0,51.0,66.0,89.0,89.0,43.0,52.0,67.0,91.0,92.0
15,COUNTY,4,AK,Alaska,Juneau City and Borough,12138.0,4322.0,36.0,9.84,14.86,...,71.0,84.0,111.0,159.0,196.0,47.0,55.0,74.0,106.0,130.0
16,COUNTY,4,AK,Alaska,Kenai Peninsula Borough,21481.0,6099.0,28.0,9.84,14.98,...,64.0,64.0,85.0,110.0,125.0,42.0,42.0,56.0,72.0,82.0
17,COUNTY,4,AK,Alaska,Ketchikan Gateway Borough,5209.0,2109.0,40.0,9.84,14.52,...,63.0,74.0,98.0,129.0,173.0,42.0,50.0,66.0,87.0,117.0
18,COUNTY,4,AK,Alaska,Kodiak Island Borough,4585.0,1800.0,39.0,9.84,13.99,...,70.0,72.0,83.0,121.0,136.0,49.0,51.0,58.0,85.0,96.0
19,COUNTY,4,AK,Alaska,Kusilvak Census Area,1734.0,450.0,26.0,9.84,12.56,...,52.0,63.0,72.0,90.0,98.0,40.0,49.0,57.0,71.0,77.0
20,COUNTY,4,AK,Alaska,Lake and Peninsula Borough,468.0,150.0,32.0,9.84,20.85,...,49.0,59.0,69.0,86.0,106.0,23.0,28.0,33.0,41.0,50.0
21,COUNTY,4,AK,Alaska,Matanuska-Susitna Borough,30839.0,7457.0,24.0,9.84,11.11,...,58.0,65.0,87.0,126.0,153.0,51.0,58.0,77.0,112.0,135.0
22,COUNTY,4,AK,Alaska,Nome Census Area,2879.0,1147.0,40.0,9.84,23.88,...,76.0,100.0,119.0,149.0,162.0,31.0,41.0,49.0,61.0,67.0
23,COUNTY,4,AK,Alaska,North Slope Borough,2018.0,1008.0,50.0,9.84,54.27,...,72.0,80.0,92.0,125.0,159.0,13.0,15.0,17.0,23.0,29.0
24,COUNTY,4,AK,Alaska,Northwest Arctic Borough,1904.0,860.0,45.0,9.84,40.46,...,84.0,87.0,100.0,135.0,136.0,21.0,21.0,24.0,33.0,33.0
25,COUNTY,4,AK,Alaska,Petersburg Census Area,1237.0,397.0,32.0,9.84,9.15,...,54.0,64.0,85.0,106.0,131.0,58.0,69.0,91.0,114.0,140.0
26,COUNTY,4,AK,Alaska,Prince of Wales-Hyder Census Area,2267.0,642.0,28.0,9.84,13.35,...,62.0,62.0,81.0,101.0,110.0,46.0,46.0,59.0,75.0,81.0
27,COUNTY,4,AK,Alaska,Sitka City and Borough,3504.0,1544.0,44.0,9.84,13.96,...,71.0,79.0,99.0,137.0,174.0,50.0,55.0,69.0,97.0,122.0
28,COUNTY,4,AK,Alaska,Skagway Municipality,428.0,195.0,46.0,9.84,14.86,...,75.0,85.0,106.0,154.0,163.0,50.0,56.0,70.0,102.0,108.0
29,COUNTY,4,AK,Alaska,Southeast Fairbanks Census Area,2085.0,591.0,28.0,9.84,26.90,...,68.0,81.0,95.0,139.0,168.0,25.0,29.0,35.0,51.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3926,COUNTY,4,WV,West Virginia,Wirt County †,2432.0,390.0,16.0,8.75,NaN,...,47.0,51.0,61.0,86.0,95.0,NaN,NaN,NaN,NaN,NaN
3927,COUNTY,4,WV,West Virginia,Wood County,36225.0,10563.0,29.0,8.75,10.25,...,47.0,51.0,61.0,86.0,95.0,40.0,44.0,52.0,74.0,81.0
3928,COUNTY,4,WV,West Virginia,Wyoming County,9222.0,1791.0,19.0,8.75,12.20,...,47.0,48.0,57.0,82.0,97.0,34.0,34.0,41.0,59.0,70.0
3929,STATE,1,WY,Wyoming,NaN,226985.0,71244.0,31.0,7.25,14.25,...,65.0,71.0,91.0,124.0,151.0,33.0,36.0,46.0,63.0,77.0
3930,NONMETRO,2,WY,Wyoming,NaN,157201.0,48348.0,31.0,7.25,14.43,...,63.0,70.0,90.0,121.0,146.0,32.0,35.0,45.0,61.0,73.0
3931,METRO,3,WY,Wyoming,Casper MSA,32422.0,11124.0,34.0,7.25,15.34,...,70.0,76.0,92.0,127.0,160.0,33.0,36.0,44.0,60.0,76.0
3932,METRO,3,WY,Wyoming,Cheyenne MSA,37362.0,11772.0,32.0,7.25,12.34,...,70.0,70.0,94.0,131.0,162.0,41.0,41.0,55.0,77.0,95.0
3933,COUNTY,4,WY,Wyoming,Albany County,15565.0,7959.0,51.0,7.25,8.79,...,59.0,65.0,84.0,123.0,149.0,49.0,54.0,70.0,101.0,123.0
3934,COUNTY,4,WY,Wyoming,Big Horn County,4459.0,1180.0,26.0,7.25,11.05,...,52.0,56.0,74.0,95.0,130.0,34.0,37.0,49.0,63.0,85.0
3935,COUNTY,4,WY,Wyoming,Campbell County,17534.0,5293.0,30.0,7.25,16.76,...,74.0,79.0,104.0,141.0,141.0,32.0,34.0,45.0,61.0,61.0
3936,COUNTY,4,WY,Wyoming,Carbon County,6095.0,1822.0,30.0,7.25,20.00,...,60.0,64.0,85.0,117.0,128.0,22.0,23.0,31.0,43.0,46.0
3937,COUNTY,4,WY,Wyoming,Converse County,5576.0,1481.0,27.0,7.25,15.55,...,58.0,61.0,82.0,119.0,134.0,27.0,29.0,38.0,55.0,62.0
3938,COUNTY,4,WY,Wyoming,Crook County,2976.0,628.0,21.0,7.25,17.91,...,60.0,63.0,84.0,106.0,138.0,24.0,26.0,34.0,43.0,56.0
3939,COUNTY,4,WY,Wyoming,Fremont County,15159.0,4441.0,29.0,7.25,11.79,...,54.0,65.0,83.0,110.0,123.0,33.0,40.0,51.0,68.0,76.0
3940,COUNTY,4,WY,Wyoming,Goshen County,5350.0,1266.0,24.0,7.25,11.77,...,56.0,59.0,78.0,100.0,128.0,34.0,36.0,48.0,62.0,79.0
3941,COUNTY,4,WY,Wyoming,Hot Springs County,2262.0,594.0,26.0,7.25,12.79,...,52.0,58.0,74.0,105.0,126.0,29.0,33.0,42.0,59.0,72.0
3942,COUNTY,4,WY,Wyoming,Johnson County,3668.0,980.0,27.0,7.25,11.59,...,65.0,69.0,92.0,129.0,151.0,41.0,43.0,58.0,80.0,94.0
3943,COUNTY,4,WY,Wyoming,Laramie County,37362.0,11772.0,32.0,7.25,12.34,...,70.0,70.0,94.0,131.0,162.0,41.0,41.0,55.0,77.0,95.0
3944,COUNTY,4,WY,Wyoming,Lincoln County,7002.0,1462.0,21.0,7.25,14.07,...,64.0,68.0,91.0,116.0,131.0,33.0,35.0,47.0,60.0,67.0
3945,COUNTY,4,WY,Wyoming,Natrona County,32422.0,11124.0,34.0,7.25,15.34,...,70.0,76.0,92.0,127.0,160.0,33.0,36.0,44.0,60.0,76.0
3946,COUNTY,4,WY,Wyoming,Niobrara County †,981.0,292.0,30.0,7.25,NaN,...,52.0,56.0,74.0,99.0,121.0,NaN,NaN,NaN,NaN,NaN
3947,COUNTY,4,WY,Wyoming,Park County,11826.0,3314.0,28.0,7.25,12.57,...,58.0,64.0,82.0,104.0,124.0,33.0,37.0,47.0,60.0,72.0
3948,COUNTY,4,WY,Wyoming,Platte County,3680.0,904.0,25.0,7.25,15.56,...,52.0,56.0,74.0,93.0,116.0,24.0,26.0,34.0,43.0,54.0
3949,COUNTY,4,WY,Wyoming,Sheridan County,12697.0,4009.0,32.0,7.25,12.03,...,67.0,72.0,94.0,118.0,166.0,40.0,43.0,57.0,71.0,100.0
3950,COUNTY,4,WY,Wyoming,Sublette County,3203.0,918.0,29.0,7.25,17.30,...,65.0,79.0,91.0,132.0,149.0,27.0,33.0,38.0,55.0,62.0
3951,COUNTY,4,WY,Wyoming,Sweetwater County,16533.0,4539.0,27.0,7.25,18.93,...,64.0,74.0,91.0,122.0,160.0,25.0,28.0,35.0,47.0,61.0
3952,COUNTY,4,WY,Wyoming,Teton County,8576.0,3444.0,40.0,7.25,15.00,...,90.0,110.0,126.0,171.0,223.0,43.0,53.0,61.0,83.0,108.0
3953,COUNTY,4,WY,Wyoming,Uinta County,7432.0,2205.0,30.0,7.25,10.18,...,55.0,59.0,78.0,106.0,119.0,39.0,42.0,56.0,76.0,85.0
3954,COUNTY,4,WY,Wyoming,Washakie County,3493.0,889.0,25.0,7.25,11.85,...,52.0,64.0,74.0,108.0,125.0,32.0,39.0,45.0,66.0,77.0
3955,COUNTY,4,WY,Wyoming,Weston County,3134.0,728.0,23.0,7.25,12.76,...,60.0,69.0,84.0,106.0,138.0,34.0,39.0,48.0,60.0,78.0

In [144]:
rent_df.count()

Type                                                                   3956
Type Code                                                              3956
ST                                                                     3956
STNAME                                                                 3956
COUNTY/METRO                                                           3856
Total households (2012-2016)                                           3955
Renter households (2012-2016)                                          3955
% of total households that are renters (2012-2016)                     3955
Minimum wage                                                           3956
Estimated mean renter wage                                             3922
SSI monthly payment                                                    3956
Zero bedroom FMR                                                       3955
One bedroom FMR                                                        3955
Two bedroom FMR                                                        3955
Three bedroom FMR                                                      3955
Four bedroom FMR                                                       3955
Annual AMI                                                             3955
30% of AMI                                                             3955
Estimated renter median income                                         3950
Rent affordable at renter median income                                3950
Rent affordable at 30% of AMI                                          3955
Rent affordable with full-time job paying min wage                     3956
Rent affordable with full-time job paying mean renter wage             3922
Rent affordable to SSI recipient                                       3956
Income needed to afford 0 bdrm FMR                                     3955
Income needed to afford 1 bdrm FMR                                     3955
Income needed to afford 2 bdrm FMR                                     3955
Income needed to afford 3 bdrm FMR                                     3955
Income needed to afford 4 bdrm FMR                                     3955
Housing Wage for 0 bdrm FMR                                            3955
Housing Wage for 1 bdrm FMR                                            3955
Housing Wage for 2 bdrm FMR                                            3955
Housing Wage for 3 bdrm FMR                                            3955
Housing Wage for 4 bdrm FMR                                            3955
Work hours per week at min. wage needed to afford 0 bdrm FMR           3955
Work hours per week at min. wage needed to afford 1 bdrm FMR           3955
Work hours per week at min. wage needed to afford 2 bdrm FMR           3955
Work hours per week at min. wage needed to afford 3 bdrm FMR           3955
Work hours per week at min. wage needed to afford 4 bdrm FMR           3955
Work hours per week at mean renter wage needed to afford 0 bdrm FMR    3922
Work hours per week at mean renter wage needed to afford 1 bdrm FMR    3922
Work hours per week at mean renter wage needed to afford 2 bdrm FMR    3922
Work hours per week at mean renter wage needed to afford 3 bdrm FMR    3922
Work hours per week at mean renter wage needed to afford 4 bdrm FMR    3922
dtype: int64

In [147]:
# rent_df.isnull().any()
rent_df.loc[rent_df.isnull().any(axis=1)]

,Type,Type Code,ST,STNAME,COUNTY/METRO,Total households (2012-2016),Renter households (2012-2016),% of total households that are renters (2012-2016),Minimum wage,Estimated mean renter wage,...,Work hours per week at min. wage needed to afford 0 bdrm FMR,Work hours per week at min. wage needed to afford 1 bdrm FMR,Work hours per week at min. wage needed to afford 2 bdrm FMR,Work hours per week at min. wage needed to afford 3 bdrm FMR,Work hours per week at min. wage needed to afford 4 bdrm FMR,Work hours per week at mean renter wage needed to afford 0 bdrm FMR,Work hours per week at mean renter wage needed to afford 1 bdrm FMR,Work hours per week at mean renter wage needed to afford 2 bdrm FMR,Work hours per week at mean renter wage needed to afford 3 bdrm FMR,Work hours per week at mean renter wage needed to afford 4 bdrm FMR
0,STATE,1,AK,Alaska,NaN,250235.0,90922.0,36.0,9.84,18.84,...,69.0,78.0,101.0,143.0,172.0,36.0,41.0,53.0,75.0,90.0
1,NONMETRO,2,AK,Alaska,NaN,79124.0,27465.0,35.0,9.84,22.96,...,68.0,76.0,96.0,128.0,151.0,29.0,33.0,41.0,55.0,65.0
34,STATE,1,AL,Alabama,NaN,1851061.0,583237.0,32.0,7.25,12.53,...,61.0,67.0,81.0,107.0,126.0,35.0,39.0,47.0,62.0,73.0
35,NONMETRO,2,AL,Alabama,NaN,440758.0,129482.0,29.0,7.25,10.72,...,50.0,53.0,66.0,89.0,99.0,34.0,36.0,45.0,60.0,67.0
120,STATE,1,AR,Arkansas,NaN,1141480.0,392028.0,34.0,8.50,13.05,...,47.0,52.0,65.0,88.0,103.0,31.0,34.0,42.0,58.0,67.0
121,NONMETRO,2,AR,Arkansas,NaN,447121.0,135996.0,30.0,8.50,10.99,...,44.0,45.0,58.0,78.0,90.0,34.0,35.0,45.0,61.0,69.0
183,COUNTY,4,AR,Arkansas,Newton County †,3243.0,483.0,15.0,8.50,NaN,...,43.0,44.0,57.0,83.0,83.0,NaN,NaN,NaN,NaN,NaN
208,STATE,1,AZ,Arizona,NaN,2448919.0,917041.0,37.0,10.50,16.54,...,48.0,56.0,70.0,102.0,117.0,30.0,35.0,45.0,65.0,74.0
209,NONMETRO,2,AZ,Arizona,NaN,113778.0,33474.0,29.0,10.50,14.74,...,42.0,43.0,55.0,74.0,83.0,30.0,31.0,39.0,52.0,59.0
232,STATE,1,CA,California,NaN,12807387.0,5878380.0,46.0,11.00,21.50,...,79.0,93.0,119.0,164.0,189.0,40.0,48.0,61.0,84.0,97.0
233,NONMETRO,2,CA,California,NaN,326743.0,115571.0,35.0,11.00,12.10,...,45.0,51.0,67.0,95.0,108.0,41.0,47.0,61.0,86.0,99.0
322,STATE,1,CO,Colorado,NaN,2051616.0,730999.0,36.0,10.20,17.59,...,64.0,74.0,94.0,134.0,156.0,37.0,43.0,54.0,78.0,91.0
323,NONMETRO,2,CO,Colorado,NaN,264356.0,84399.0,32.0,10.20,13.21,...,54.0,58.0,74.0,101.0,113.0,42.0,45.0,57.0,78.0,87.0
396,STATE,1,CT,Connecticut,NaN,1354713.0,454490.0,34.0,10.10,17.38,...,66.0,79.0,99.0,125.0,146.0,39.0,46.0,57.0,73.0,85.0
397,NONMETRO,2,CT,Connecticut,NaN,74339.0,17326.0,23.0,10.10,12.23,...,53.0,65.0,83.0,105.0,113.0,44.0,54.0,69.0,87.0,94.0
410,STATE,1,DC,District of Columbia,NaN,276546.0,163874.0,59.0,13.25,27.75,...,87.0,91.0,104.0,137.0,168.0,42.0,43.0,50.0,65.0,80.0
413,STATE,1,DE,Delaware,NaN,348051.0,101111.0,29.0,8.25,16.99,...,75.0,87.0,106.0,139.0,159.0,37.0,42.0,51.0,68.0,77.0
414,METRO,3,DE,Delaware,Dover MSA †,62140.0,19052.0,31.0,8.25,NaN,...,72.0,75.0,87.0,127.0,153.0,NaN,NaN,NaN,NaN,NaN
417,COUNTY,4,DE,Delaware,Kent County †,62140.0,19052.0,31.0,8.25,NaN,...,72.0,75.0,87.0,127.0,153.0,NaN,NaN,NaN,NaN,NaN
420,STATE,1,FL,Florida,NaN,7393262.0,2605942.0,35.0,8.25,16.10,...,72.0,84.0,104.0,141.0,169.0,37.0,43.0,53.0,72.0,87.0
421,NONMETRO,2,FL,Florida,NaN,242270.0,69364.0,29.0,8.25,11.80,...,58.0,64.0,79.0,105.0,122.0,41.0,45.0,56.0,74.0,85.0
518,STATE,1,GA,Georgia,NaN,3611706.0,1345295.0,37.0,7.25,16.28,...,79.0,83.0,97.0,128.0,155.0,35.0,37.0,43.0,57.0,69.0
519,NONMETRO,2,GA,Georgia,NaN,641594.0,219376.0,34.0,7.25,10.58,...,57.0,58.0,74.0,99.0,116.0,39.0,40.0,50.0,68.0,79.0
676,COUNTY,4,GA,Georgia,Taliaferro County †,748.0,232.0,31.0,7.25,NaN,...,65.0,65.0,82.0,103.0,120.0,NaN,NaN,NaN,NaN,NaN
697,COUNTY,4,GA,Georgia,Webster County †,1025.0,194.0,19.0,7.25,NaN,...,56.0,56.0,71.0,90.0,113.0,NaN,NaN,NaN,NaN,NaN
705,STATE,1,HI,Hawaii,NaN,452030.0,192176.0,43.0,10.10,16.16,...,96.0,109.0,143.0,205.0,245.0,60.0,68.0,89.0,128.0,153.0
706,NONMETRO,2,HI,Hawaii,NaN,88524.0,30307.0,34.0,10.10,12.99,...,69.0,81.0,105.0,134.0,157.0,53.0,63.0,81.0,104.0,122.0
708,METRO,3,HI,Hawaii,Kalawao County HMFA †,55.0,53.0,96.0,10.10,NaN,...,86.0,99.0,124.0,180.0,218.0,NaN,NaN,NaN,NaN,NaN
712,COUNTY,4,HI,Hawaii,Kalawao County †,55.0,53.0,96.0,10.10,NaN,...,86.0,99.0,124.0,180.0,218.0,NaN,NaN,NaN,NaN,NaN
715,STATE,1,IA,Iowa,NaN,1242641.0,359522.0,29.0,7.25,12.50,...,56.0,65.0,83.0,111.0,126.0,32.0,38.0,48.0,64.0,73.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3011,STATE,1,SD,South Dakota,NaN,333536.0,107391.0,32.0,8.85,11.90,...,44.0,51.0,65.0,88.0,100.0,33.0,38.0,48.0,65.0,75.0
3012,NONMETRO,2,SD,South Dakota,NaN,175289.0,57105.0,33.0,8.85,10.62,...,40.0,46.0,60.0,81.0,90.0,34.0,39.0,50.0,67.0,75.0
3025,COUNTY,4,SD,South Dakota,Buffalo County †,496.0,280.0,56.0,8.85,NaN,...,45.0,52.0,68.0,85.0,93.0,NaN,NaN,NaN,NaN,NaN
3084,STATE,1,TN,Tennessee,NaN,2522204.0,849161.0,34.0,7.25,14.50,...,62.0,71.0,87.0,116.0,136.0,31.0,35.0,43.0,58.0,68.0
3085,NONMETRO,2,TN,Tennessee,NaN,583957.0,167080.0,29.0,7.25,10.97,...,51.0,54.0,68.0,92.0,103.0,33.0,36.0,45.0,61.0,68.0
3200,STATE,1,TX,Texas,NaN,9289554.0,3542096.0,38.0,7.25,18.20,...,75.0,86.0,107.0,144.0,178.0,30.0,34.0,42.0,57.0,71.0
3201,NONMETRO,2,TX,Texas,NaN,1056118.0,303578.0,29.0,7.25,13.30,...,60.0,64.0,80.0,107.0,126.0,33.0,35.0,44.0,58.0,69.0
3322,COUNTY,4,TX,Texas,Foard County †,526.0,113.0,21.0,7.25,NaN,...,56.0,59.0,74.0,98.0,116.0,NaN,NaN,NaN,NaN,NaN
3376,COUNTY,4,TX,Texas,Kent County †,284.0,82.0,29.0,7.25,NaN,...,56.0,59.0,74.0,108.0,116.0,NaN,NaN,NaN,NaN,NaN
3379,COUNTY,4,TX,Texas,King County †,114.0,84.0,74.0,7.25,NaN,...,81.0,85.0,107.0,134.0,167.0,NaN,NaN,NaN,NaN,NaN
3395,COUNTY,4,TX,Texas,Loving County †,37.0,20.0,54.0,7.25,NaN,...,59.0,62.0,78.0,104.0,122.0,NaN,NaN,NaN,NaN,NaN
3466,COUNTY,4,TX,Texas,Terrell County †,396.0,127.0,32.0,7.25,NaN,...,60.0,63.0,79.0,103.0,124.0,NaN,NaN,NaN,NaN,NaN
3499,STATE,1,UT,Utah,NaN,918367.0,279600.0,30.0,7.25,13.92,...,66.0,79.0,98.0,140.0,164.0,34.0,41.0,51.0,73.0,85.0
3500,NONMETRO,2,UT,Utah,NaN,103006.0,27572.0,27.0,7.25,12.09,...,61.0,72.0,90.0,125.0,145.0,37.0,43.0,54.0,75.0,87.0
3537,STATE,1,VA,Virginia,NaN,3090178.0,1057417.0,34.0,7.25,17.69,...,106.0,111.0,131.0,175.0,214.0,43.0,46.0,54.0,72.0,88.0
3538,NONMETRO,2,VA,Virginia,NaN,422937.0,118758.0,28.0,7.25,11.03,...,58.0,65.0,80.0,106.0,124.0,38.0,42.0,52.0,69.0,82.0
3654,COUNTY,4,VA,Virginia,Bedford city †,NaN,NaN,NaN,7.25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3692,STATE,1,VT,Vermont,NaN,255955.0,75203.0,29.0,10.50,12.85,...,60.0,68.0,85.0,112.0,124.0,49.0,56.0,70.0,91.0,101.0
3693,NONMETRO,2,VT,Vermont,NaN,171718.0,46914.0,27.0,10.50,12.01,...,55.0,59.0,73.0,95.0,110.0,48.0,52.0,64.0,83.0,96.0
3706,STATE,1,WA,Washington,NaN,2696606.0,1013225.0,38.0,11.50,18.91,...,66.0,75.0,93.0,135.0,159.0,40.0,46.0,57.0,82.0,97.0
3707,NONMETRO,2,WA,Washington,NaN,279203.0,93189.0,33.0,11.50,11.03,...,37.0,43.0,56.0,78.0,88.0,39.0,45.0,58.0,81.0,92.0
3736,COUNTY,4,WA,Washington,Garfield County †,952.0,278.0,29.0,11.50,NaN,...,30.0,38.0,47.0,68.0,82.0,NaN,NaN,NaN,NaN,NaN
3764,STATE,1,WI,Wisconsin,NaN,2310246.0,762613.0,33.0,7.25,13.35,...,62.0,73.0,91.0,121.0,137.0,34.0,39.0,50.0,66.0,74.0
3765,NONMETRO,2,WI,Wisconsin,NaN,615307.0,160323.0,26.0,7.25,11.08,...,53.0,59.0,77.0,102.0,113.0,35.0,39.0,51.0,67.0,74.0
3857,STATE,1,WV,West Virginia,NaN,739397.0,203457.0,28.0,8.75,11.36,...,48.0,53.0,64.0,85.0,98.0,37.0,41.0,50.0,66.0,76.0
3858,NONMETRO,2,WV,West Virginia,NaN,282836.0,67854.0,24.0,8.75,10.95,...,46.0,49.0,59.0,77.0,91.0,36.0,39.0,47.0,61.0,73.0
3926,COUNTY,4,WV,West Virginia,Wirt County †,2432.0,390.0,16.0,8.75,NaN,...,47.0,51.0,61.0,86.0,95.0,NaN,NaN,NaN,NaN,NaN
3929,STATE,1,WY,Wyoming,NaN,226985.0,71244.0,31.0,7.25,14.25,...,65.0,71.0,91.0,124.0,151.0,33.0,36.0,46.0,63.0,77.0
3930,NONMETRO,2,WY,Wyoming,NaN,157201.0,48348.0,31.0,7.25,14.43,...,63.0,70.0,90.0,121.0,146.0,32.0,35.0,45.0,61.0,73.0
3946,COUNTY,4,WY,Wyoming,Niobrara County †,981.0,292.0,30.0,7.25,NaN,...,52.0,56.0,74.0,99.0,121.0,NaN,NaN,NaN,NaN,NaN

In [148]:
rent_df['COUNTY/METRO'].fillna("Does Not Apply", inplace=True)
rent_df

,Type,Type Code,ST,STNAME,COUNTY/METRO,Total households (2012-2016),Renter households (2012-2016),% of total households that are renters (2012-2016),Minimum wage,Estimated mean renter wage,...,Work hours per week at min. wage needed to afford 0 bdrm FMR,Work hours per week at min. wage needed to afford 1 bdrm FMR,Work hours per week at min. wage needed to afford 2 bdrm FMR,Work hours per week at min. wage needed to afford 3 bdrm FMR,Work hours per week at min. wage needed to afford 4 bdrm FMR,Work hours per week at mean renter wage needed to afford 0 bdrm FMR,Work hours per week at mean renter wage needed to afford 1 bdrm FMR,Work hours per week at mean renter wage needed to afford 2 bdrm FMR,Work hours per week at mean renter wage needed to afford 3 bdrm FMR,Work hours per week at mean renter wage needed to afford 4 bdrm FMR
0,STATE,1,AK,Alaska,Does Not Apply,250235.0,90922.0,36.0,9.84,18.84,...,69.0,78.0,101.0,143.0,172.0,36.0,41.0,53.0,75.0,90.0
1,NONMETRO,2,AK,Alaska,Does Not Apply,79124.0,27465.0,35.0,9.84,22.96,...,68.0,76.0,96.0,128.0,151.0,29.0,33.0,41.0,55.0,65.0
2,METRO,3,AK,Alaska,Anchorage HMFA,104969.0,41702.0,40.0,9.84,17.82,...,72.0,81.0,105.0,152.0,184.0,40.0,45.0,58.0,84.0,102.0
3,METRO,3,AK,Alaska,Fairbanks MSA,35303.0,14298.0,41.0,9.84,16.30,...,68.0,80.0,107.0,156.0,188.0,41.0,49.0,65.0,94.0,114.0
4,METRO,3,AK,Alaska,Matanuska-Susitna Borough HMFA,30839.0,7457.0,24.0,9.84,11.11,...,58.0,65.0,87.0,126.0,153.0,51.0,58.0,77.0,112.0,135.0
5,COUNTY,4,AK,Alaska,Aleutians East Borough,788.0,345.0,44.0,9.84,25.02,...,59.0,72.0,82.0,103.0,112.0,23.0,28.0,32.0,41.0,44.0
6,COUNTY,4,AK,Alaska,Aleutians West Census Area,1186.0,850.0,72.0,9.84,27.77,...,81.0,96.0,127.0,160.0,196.0,29.0,34.0,45.0,57.0,69.0
7,COUNTY,4,AK,Alaska,Anchorage Municipality,104969.0,41702.0,40.0,9.84,17.82,...,72.0,81.0,105.0,152.0,184.0,40.0,45.0,58.0,84.0,102.0
8,COUNTY,4,AK,Alaska,Bethel Census Area,4555.0,1634.0,36.0,9.84,20.09,...,83.0,101.0,116.0,145.0,158.0,41.0,49.0,57.0,71.0,77.0
9,COUNTY,4,AK,Alaska,Bristol Bay Borough,360.0,163.0,45.0,9.84,19.42,...,70.0,74.0,98.0,126.0,133.0,35.0,38.0,49.0,64.0,67.0
10,COUNTY,4,AK,Alaska,Denali Borough,707.0,174.0,25.0,9.84,24.50,...,81.0,88.0,114.0,144.0,175.0,33.0,35.0,46.0,58.0,70.0
11,COUNTY,4,AK,Alaska,Dillingham Census Area,1375.0,543.0,39.0,9.84,18.19,...,79.0,82.0,94.0,130.0,144.0,43.0,44.0,51.0,70.0,78.0
12,COUNTY,4,AK,Alaska,Fairbanks North Star Borough,35303.0,14298.0,41.0,9.84,16.30,...,68.0,80.0,107.0,156.0,188.0,41.0,49.0,65.0,94.0,114.0
13,COUNTY,4,AK,Alaska,Haines Borough,1170.0,367.0,31.0,9.84,12.91,...,55.0,67.0,77.0,97.0,119.0,42.0,51.0,59.0,74.0,90.0
14,COUNTY,4,AK,Alaska,Hoonah-Angoon Census Area,836.0,239.0,29.0,9.84,9.61,...,42.0,51.0,66.0,89.0,89.0,43.0,52.0,67.0,91.0,92.0
15,COUNTY,4,AK,Alaska,Juneau City and Borough,12138.0,4322.0,36.0,9.84,14.86,...,71.0,84.0,111.0,159.0,196.0,47.0,55.0,74.0,106.0,130.0
16,COUNTY,4,AK,Alaska,Kenai Peninsula Borough,21481.0,6099.0,28.0,9.84,14.98,...,64.0,64.0,85.0,110.0,125.0,42.0,42.0,56.0,72.0,82.0
17,COUNTY,4,AK,Alaska,Ketchikan Gateway Borough,5209.0,2109.0,40.0,9.84,14.52,...,63.0,74.0,98.0,129.0,173.0,42.0,50.0,66.0,87.0,117.0
18,COUNTY,4,AK,Alaska,Kodiak Island Borough,4585.0,1800.0,39.0,9.84,13.99,...,70.0,72.0,83.0,121.0,136.0,49.0,51.0,58.0,85.0,96.0
19,COUNTY,4,AK,Alaska,Kusilvak Census Area,1734.0,450.0,26.0,9.84,12.56,...,52.0,63.0,72.0,90.0,98.0,40.0,49.0,57.0,71.0,77.0
20,COUNTY,4,AK,Alaska,Lake and Peninsula Borough,468.0,150.0,32.0,9.84,20.85,...,49.0,59.0,69.0,86.0,106.0,23.0,28.0,33.0,41.0,50.0
21,COUNTY,4,AK,Alaska,Matanuska-Susitna Borough,30839.0,7457.0,24.0,9.84,11.11,...,58.0,65.0,87.0,126.0,153.0,51.0,58.0,77.0,112.0,135.0
22,COUNTY,4,AK,Alaska,Nome Census Area,2879.0,1147.0,40.0,9.84,23.88,...,76.0,100.0,119.0,149.0,162.0,31.0,41.0,49.0,61.0,67.0
23,COUNTY,4,AK,Alaska,North Slope Borough,2018.0,1008.0,50.0,9.84,54.27,...,72.0,80.0,92.0,125.0,159.0,13.0,15.0,17.0,23.0,29.0
24,COUNTY,4,AK,Alaska,Northwest Arctic Borough,1904.0,860.0,45.0,9.84,40.46,...,84.0,87.0,100.0,135.0,136.0,21.0,21.0,24.0,33.0,33.0
25,COUNTY,4,AK,Alaska,Petersburg Census Area,1237.0,397.0,32.0,9.84,9.15,...,54.0,64.0,85.0,106.0,131.0,58.0,69.0,91.0,114.0,140.0
26,COUNTY,4,AK,Alaska,Prince of Wales-Hyder Census Area,2267.0,642.0,28.0,9.84,13.35,...,62.0,62.0,81.0,101.0,110.0,46.0,46.0,59.0,75.0,81.0
27,COUNTY,4,AK,Alaska,Sitka City and Borough,3504.0,1544.0,44.0,9.84,13.96,...,71.0,79.0,99.0,137.0,174.0,50.0,55.0,69.0,97.0,122.0
28,COUNTY,4,AK,Alaska,Skagway Municipality,428.0,195.0,46.0,9.84,14.86,...,75.0,85.0,106.0,154.0,163.0,50.0,56.0,70.0,102.0,108.0
29,COUNTY,4,AK,Alaska,Southeast Fairbanks Census Area,2085.0,591.0,28.0,9.84,26.90,...,68.0,81.0,95.0,139.0,168.0,25.0,29.0,35.0,51.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3926,COUNTY,4,WV,West Virginia,Wirt County †,2432.0,390.0,16.0,8.75,NaN,...,47.0,51.0,61.0,86.0,95.0,NaN,NaN,NaN,NaN,NaN
3927,COUNTY,4,WV,West Virginia,Wood County,36225.0,10563.0,29.0,8.75,10.25,...,47.0,51.0,61.0,86.0,95.0,40.0,44.0,52.0,74.0,81.0
3928,COUNTY,4,WV,West Virginia,Wyoming County,9222.0,1791.0,19.0,8.75,12.20,...,47.0,48.0,57.0,82.0,97.0,34.0,34.0,41.0,59.0,70.0
3929,STATE,1,WY,Wyoming,Does Not Apply,226985.0,71244.0,31.0,7.25,14.25,...,65.0,71.0,91.0,124.0,151.0,33.0,36.0,46.0,63.0,77.0
3930,NONMETRO,2,WY,Wyoming,Does Not Apply,157201.0,48348.0,31.0,7.25,14.43,...,63.0,70.0,90.0,121.0,146.0,32.0,35.0,45.0,61.0,73.0
3931,METRO,3,WY,Wyoming,Casper MSA,32422.0,11124.0,34.0,7.25,15.34,...,70.0,76.0,92.0,127.0,160.0,33.0,36.0,44.0,60.0,76.0
3932,METRO,3,WY,Wyoming,Cheyenne MSA,37362.0,11772.0,32.0,7.25,12.34,...,70.0,70.0,94.0,131.0,162.0,41.0,41.0,55.0,77.0,95.0
3933,COUNTY,4,WY,Wyoming,Albany County,15565.0,7959.0,51.0,7.25,8.79,...,59.0,65.0,84.0,123.0,149.0,49.0,54.0,70.0,101.0,123.0
3934,COUNTY,4,WY,Wyoming,Big Horn County,4459.0,1180.0,26.0,7.25,11.05,...,52.0,56.0,74.0,95.0,130.0,34.0,37.0,49.0,63.0,85.0
3935,COUNTY,4,WY,Wyoming,Campbell County,17534.0,5293.0,30.0,7.25,16.76,...,74.0,79.0,104.0,141.0,141.0,32.0,34.0,45.0,61.0,61.0
3936,COUNTY,4,WY,Wyoming,Carbon County,6095.0,1822.0,30.0,7.25,20.00,...,60.0,64.0,85.0,117.0,128.0,22.0,23.0,31.0,43.0,46.0
3937,COUNTY,4,WY,Wyoming,Converse County,5576.0,1481.0,27.0,7.25,15.55,...,58.0,61.0,82.0,119.0,134.0,27.0,29.0,38.0,55.0,62.0
3938,COUNTY,4,WY,Wyoming,Crook County,2976.0,628.0,21.0,7.25,17.91,...,60.0,63.0,84.0,106.0,138.0,24.0,26.0,34.0,43.0,56.0
3939,COUNTY,4,WY,Wyoming,Fremont County,15159.0,4441.0,29.0,7.25,11.79,...,54.0,65.0,83.0,110.0,123.0,33.0,40.0,51.0,68.0,76.0
3940,COUNTY,4,WY,Wyoming,Goshen County,5350.0,1266.0,24.0,7.25,11.77,...,56.0,59.0,78.0,100.0,128.0,34.0,36.0,48.0,62.0,79.0
3941,COUNTY,4,WY,Wyoming,Hot Springs County,2262.0,594.0,26.0,7.25,12.79,...,52.0,58.0,74.0,105.0,126.0,29.0,33.0,42.0,59.0,72.0
3942,COUNTY,4,WY,Wyoming,Johnson County,3668.0,980.0,27.0,7.25,11.59,...,65.0,69.0,92.0,129.0,151.0,41.0,43.0,58.0,80.0,94.0
3943,COUNTY,4,WY,Wyoming,Laramie County,37362.0,11772.0,32.0,7.25,12.34,...,70.0,70.0,94.0,131.0,162.0,41.0,41.0,55.0,77.0,95.0
3944,COUNTY,4,WY,Wyoming,Lincoln County,7002.0,1462.0,21.0,7.25,14.07,...,64.0,68.0,91.0,116.0,131.0,33.0,35.0,47.0,60.0,67.0
3945,COUNTY,4,WY,Wyoming,Natrona County,32422.0,11124.0,34.0,7.25,15.34,...,70.0,76.0,92.0,127.0,160.0,33.0,36.0,44.0,60.0,76.0
3946,COUNTY,4,WY,Wyoming,Niobrara County †,981.0,292.0,30.0,7.25,NaN,...,52.0,56.0,74.0,99.0,121.0,NaN,NaN,NaN,NaN,NaN
3947,COUNTY,4,WY,Wyoming,Park County,11826.0,3314.0,28.0,7.25,12.57,...,58.0,64.0,82.0,104.0,124.0,33.0,37.0,47.0,60.0,72.0
3948,COUNTY,4,WY,Wyoming,Platte County,3680.0,904.0,25.0,7.25,15.56,...,52.0,56.0,74.0,93.0,116.0,24.0,26.0,34.0,43.0,54.0
3949,COUNTY,4,WY,Wyoming,Sheridan County,12697.0,4009.0,32.0,7.25,12.03,...,67.0,72.0,94.0,118.0,166.0,40.0,43.0,57.0,71.0,100.0
3950,COUNTY,4,WY,Wyoming,Sublette County,3203.0,918.0,29.0,7.25,17.30,...,65.0,79.0,91.0,132.0,149.0,27.0,33.0,38.0,55.0,62.0
3951,COUNTY,4,WY,Wyoming,Sweetwater County,16533.0,4539.0,27.0,7.25,18.93,...,64.0,74.0,91.0,122.0,160.0,25.0,28.0,35.0,47.0,61.0
3952,COUNTY,4,WY,Wyoming,Teton County,8576.0,3444.0,40.0,7.25,15.00,...,90.0,110.0,126.0,171.0,223.0,43.0,53.0,61.0,83.0,108.0
3953,COUNTY,4,WY,Wyoming,Uinta County,7432.0,2205.0,30.0,7.25,10.18,...,55.0,59.0,78.0,106.0,119.0,39.0,42.0,56.0,76.0,85.0
3954,COUNTY,4,WY,Wyoming,Washakie County,3493.0,889.0,25.0,7.25,11.85,...,52.0,64.0,74.0,108.0,125.0,32.0,39.0,45.0,66.0,77.0
3955,COUNTY,4,WY,Wyoming,Weston County,3134.0,728.0,23.0,7.25,12.76,...,60.0,69.0,84.0,106.0,138.0,34.0,39.0,48.0,60.0,78.0

In [149]:
rent_df.loc[rent_df.isnull().any(axis=1)]

,Type,Type Code,ST,STNAME,COUNTY/METRO,Total households (2012-2016),Renter households (2012-2016),% of total households that are renters (2012-2016),Minimum wage,Estimated mean renter wage,...,Work hours per week at min. wage needed to afford 0 bdrm FMR,Work hours per week at min. wage needed to afford 1 bdrm FMR,Work hours per week at min. wage needed to afford 2 bdrm FMR,Work hours per week at min. wage needed to afford 3 bdrm FMR,Work hours per week at min. wage needed to afford 4 bdrm FMR,Work hours per week at mean renter wage needed to afford 0 bdrm FMR,Work hours per week at mean renter wage needed to afford 1 bdrm FMR,Work hours per week at mean renter wage needed to afford 2 bdrm FMR,Work hours per week at mean renter wage needed to afford 3 bdrm FMR,Work hours per week at mean renter wage needed to afford 4 bdrm FMR
183,COUNTY,4,AR,Arkansas,Newton County †,3243.0,483.0,15.0,8.50,NaN,...,43.0,44.0,57.0,83.0,83.0,NaN,NaN,NaN,NaN,NaN
414,METRO,3,DE,Delaware,Dover MSA †,62140.0,19052.0,31.0,8.25,NaN,...,72.0,75.0,87.0,127.0,153.0,NaN,NaN,NaN,NaN,NaN
417,COUNTY,4,DE,Delaware,Kent County †,62140.0,19052.0,31.0,8.25,NaN,...,72.0,75.0,87.0,127.0,153.0,NaN,NaN,NaN,NaN,NaN
676,COUNTY,4,GA,Georgia,Taliaferro County †,748.0,232.0,31.0,7.25,NaN,...,65.0,65.0,82.0,103.0,120.0,NaN,NaN,NaN,NaN,NaN
697,COUNTY,4,GA,Georgia,Webster County †,1025.0,194.0,19.0,7.25,NaN,...,56.0,56.0,71.0,90.0,113.0,NaN,NaN,NaN,NaN,NaN
708,METRO,3,HI,Hawaii,Kalawao County HMFA †,55.0,53.0,96.0,10.10,NaN,...,86.0,99.0,124.0,180.0,218.0,NaN,NaN,NaN,NaN,NaN
712,COUNTY,4,HI,Hawaii,Kalawao County †,55.0,53.0,96.0,10.10,NaN,...,86.0,99.0,124.0,180.0,218.0,NaN,NaN,NaN,NaN,NaN
1357,COUNTY,4,KY,Kentucky,Robertson County †,961.0,208.0,22.0,7.25,NaN,...,51.0,59.0,71.0,89.0,99.0,NaN,NaN,NaN,NaN,NaN
1447,COUNTY,4,LA,Louisiana,Tensas Parish †,1941.0,768.0,40.0,7.25,NaN,...,55.0,56.0,72.0,105.0,109.0,NaN,NaN,NaN,NaN,NaN
1478,COUNTY,4,MA,Massachusetts,Nantucket County †,3836.0,1385.0,36.0,11.00,NaN,...,86.0,96.0,110.0,149.0,150.0,NaN,NaN,NaN,NaN,NaN
2007,COUNTY,4,MT,Montana,Petroleum County †,212.0,83.0,39.0,8.30,NaN,...,53.0,59.0,75.0,104.0,124.0,NaN,NaN,NaN,NaN,NaN
2107,COUNTY,4,NC,North Carolina,Hyde County †,1936.0,530.0,27.0,7.25,NaN,...,79.0,79.0,97.0,122.0,154.0,NaN,NaN,NaN,NaN,NaN
2210,COUNTY,4,ND,North Dakota,Slope County †,306.0,49.0,16.0,7.25,NaN,...,61.0,62.0,81.0,114.0,120.0,NaN,NaN,NaN,NaN,NaN
2233,COUNTY,4,NE,Nebraska,Arthur County †,183.0,69.0,38.0,9.00,NaN,...,45.0,52.0,69.0,86.0,94.0,NaN,NaN,NaN,NaN,NaN
2234,COUNTY,4,NE,Nebraska,Banner County †,314.0,106.0,34.0,9.00,NaN,...,36.0,42.0,56.0,71.0,78.0,NaN,NaN,NaN,NaN,NaN
2235,COUNTY,4,NE,Nebraska,Blaine County †,251.0,106.0,42.0,9.00,NaN,...,37.0,42.0,56.0,71.0,78.0,NaN,NaN,NaN,NaN,NaN
2282,COUNTY,4,NE,Nebraska,Keya Paha County †,338.0,100.0,30.0,9.00,NaN,...,36.0,42.0,56.0,71.0,78.0,NaN,NaN,NaN,NaN,NaN
2288,COUNTY,4,NE,Nebraska,Loup County †,248.0,47.0,19.0,9.00,NaN,...,36.0,42.0,56.0,71.0,78.0,NaN,NaN,NaN,NaN,NaN
2289,COUNTY,4,NE,Nebraska,McPherson County †,195.0,64.0,33.0,9.00,NaN,...,36.0,42.0,56.0,71.0,78.0,NaN,NaN,NaN,NaN,NaN
2313,COUNTY,4,NE,Nebraska,Sioux County †,544.0,155.0,28.0,9.00,NaN,...,36.0,42.0,56.0,70.0,78.0,NaN,NaN,NaN,NaN,NaN
2390,COUNTY,4,NM,New Mexico,Harding County †,193.0,41.0,21.0,7.50,NaN,...,55.0,56.0,71.0,104.0,116.0,NaN,NaN,NaN,NaN,NaN
2421,COUNTY,4,NV,Nevada,Esmeralda County †,454.0,200.0,44.0,8.25,NaN,...,41.0,54.0,65.0,92.0,105.0,NaN,NaN,NaN,NaN,NaN
2807,COUNTY,4,PA,Pennsylvania,Forest County †,1816.0,278.0,15.0,7.25,NaN,...,57.0,57.0,76.0,95.0,134.0,NaN,NaN,NaN,NaN,NaN
2887,COUNTY,4,PR,Puerto Rico,Culebra Municipio †,509.0,182.0,36.0,7.25,NaN,...,34.0,36.0,41.0,52.0,57.0,NaN,NaN,NaN,NaN,NaN
3025,COUNTY,4,SD,South Dakota,Buffalo County †,496.0,280.0,56.0,8.85,NaN,...,45.0,52.0,68.0,85.0,93.0,NaN,NaN,NaN,NaN,NaN
3322,COUNTY,4,TX,Texas,Foard County †,526.0,113.0,21.0,7.25,NaN,...,56.0,59.0,74.0,98.0,116.0,NaN,NaN,NaN,NaN,NaN
3376,COUNTY,4,TX,Texas,Kent County †,284.0,82.0,29.0,7.25,NaN,...,56.0,59.0,74.0,108.0,116.0,NaN,NaN,NaN,NaN,NaN
3379,COUNTY,4,TX,Texas,King County †,114.0,84.0,74.0,7.25,NaN,...,81.0,85.0,107.0,134.0,167.0,NaN,NaN,NaN,NaN,NaN
3395,COUNTY,4,TX,Texas,Loving County †,37.0,20.0,54.0,7.25,NaN,...,59.0,62.0,78.0,104.0,122.0,NaN,NaN,NaN,NaN,NaN
3466,COUNTY,4,TX,Texas,Terrell County †,396.0,127.0,32.0,7.25,NaN,...,60.0,63.0,79.0,103.0,124.0,NaN,NaN,NaN,NaN,NaN
3654,COUNTY,4,VA,Virginia,Bedford city †,NaN,NaN,NaN,7.25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3736,COUNTY,4,WA,Washington,Garfield County †,952.0,278.0,29.0,11.50,NaN,...,30.0,38.0,47.0,68.0,82.0,NaN,NaN,NaN,NaN,NaN
3926,COUNTY,4,WV,West Virginia,Wirt County †,2432.0,390.0,16.0,8.75,NaN,...,47.0,51.0,61.0,86.0,95.0,NaN,NaN,NaN,NaN,NaN
3946,COUNTY,4,WY,Wyoming,Niobrara County †,981.0,292.0,30.0,7.25,NaN,...,52.0,56.0,74.0,99.0,121.0,NaN,NaN,NaN,NaN,NaN

In [150]:
rent_df.fillna(value="Not Provided", inplace = True)
rent_df

,Type,Type Code,ST,STNAME,COUNTY/METRO,Total households (2012-2016),Renter households (2012-2016),% of total households that are renters (2012-2016),Minimum wage,Estimated mean renter wage,...,Work hours per week at min. wage needed to afford 0 bdrm FMR,Work hours per week at min. wage needed to afford 1 bdrm FMR,Work hours per week at min. wage needed to afford 2 bdrm FMR,Work hours per week at min. wage needed to afford 3 bdrm FMR,Work hours per week at min. wage needed to afford 4 bdrm FMR,Work hours per week at mean renter wage needed to afford 0 bdrm FMR,Work hours per week at mean renter wage needed to afford 1 bdrm FMR,Work hours per week at mean renter wage needed to afford 2 bdrm FMR,Work hours per week at mean renter wage needed to afford 3 bdrm FMR,Work hours per week at mean renter wage needed to afford 4 bdrm FMR
0,STATE,1,AK,Alaska,Does Not Apply,250235,90922,36,9.84,18.84,...,69,78,101,143,172,36,41,53,75,90
1,NONMETRO,2,AK,Alaska,Does Not Apply,79124,27465,35,9.84,22.96,...,68,76,96,128,151,29,33,41,55,65
2,METRO,3,AK,Alaska,Anchorage HMFA,104969,41702,40,9.84,17.82,...,72,81,105,152,184,40,45,58,84,102
3,METRO,3,AK,Alaska,Fairbanks MSA,35303,14298,41,9.84,16.3,...,68,80,107,156,188,41,49,65,94,114
4,METRO,3,AK,Alaska,Matanuska-Susitna Borough HMFA,30839,7457,24,9.84,11.11,...,58,65,87,126,153,51,58,77,112,135
5,COUNTY,4,AK,Alaska,Aleutians East Borough,788,345,44,9.84,25.02,...,59,72,82,103,112,23,28,32,41,44
6,COUNTY,4,AK,Alaska,Aleutians West Census Area,1186,850,72,9.84,27.77,...,81,96,127,160,196,29,34,45,57,69
7,COUNTY,4,AK,Alaska,Anchorage Municipality,104969,41702,40,9.84,17.82,...,72,81,105,152,184,40,45,58,84,102
8,COUNTY,4,AK,Alaska,Bethel Census Area,4555,1634,36,9.84,20.09,...,83,101,116,145,158,41,49,57,71,77
9,COUNTY,4,AK,Alaska,Bristol Bay Borough,360,163,45,9.84,19.42,...,70,74,98,126,133,35,38,49,64,67
10,COUNTY,4,AK,Alaska,Denali Borough,707,174,25,9.84,24.5,...,81,88,114,144,175,33,35,46,58,70
11,COUNTY,4,AK,Alaska,Dillingham Census Area,1375,543,39,9.84,18.19,...,79,82,94,130,144,43,44,51,70,78
12,COUNTY,4,AK,Alaska,Fairbanks North Star Borough,35303,14298,41,9.84,16.3,...,68,80,107,156,188,41,49,65,94,114
13,COUNTY,4,AK,Alaska,Haines Borough,1170,367,31,9.84,12.91,...,55,67,77,97,119,42,51,59,74,90
14,COUNTY,4,AK,Alaska,Hoonah-Angoon Census Area,836,239,29,9.84,9.61,...,42,51,66,89,89,43,52,67,91,92
15,COUNTY,4,AK,Alaska,Juneau City and Borough,12138,4322,36,9.84,14.86,...,71,84,111,159,196,47,55,74,106,130
16,COUNTY,4,AK,Alaska,Kenai Peninsula Borough,21481,6099,28,9.84,14.98,...,64,64,85,110,125,42,42,56,72,82
17,COUNTY,4,AK,Alaska,Ketchikan Gateway Borough,5209,2109,40,9.84,14.52,...,63,74,98,129,173,42,50,66,87,117
18,COUNTY,4,AK,Alaska,Kodiak Island Borough,4585,1800,39,9.84,13.99,...,70,72,83,121,136,49,51,58,85,96
19,COUNTY,4,AK,Alaska,Kusilvak Census Area,1734,450,26,9.84,12.56,...,52,63,72,90,98,40,49,57,71,77
20,COUNTY,4,AK,Alaska,Lake and Peninsula Borough,468,150,32,9.84,20.85,...,49,59,69,86,106,23,28,33,41,50
21,COUNTY,4,AK,Alaska,Matanuska-Susitna Borough,30839,7457,24,9.84,11.11,...,58,65,87,126,153,51,58,77,112,135
22,COUNTY,4,AK,Alaska,Nome Census Area,2879,1147,40,9.84,23.88,...,76,100,119,149,162,31,41,49,61,67
23,COUNTY,4,AK,Alaska,North Slope Borough,2018,1008,50,9.84,54.27,...,72,80,92,125,159,13,15,17,23,29
24,COUNTY,4,AK,Alaska,Northwest Arctic Borough,1904,860,45,9.84,40.46,...,84,87,100,135,136,21,21,24,33,33
25,COUNTY,4,AK,Alaska,Petersburg Census Area,1237,397,32,9.84,9.15,...,54,64,85,106,131,58,69,91,114,140
26,COUNTY,4,AK,Alaska,Prince of Wales-Hyder Census Area,2267,642,28,9.84,13.35,...,62,62,81,101,110,46,46,59,75,81
27,COUNTY,4,AK,Alaska,Sitka City and Borough,3504,1544,44,9.84,13.96,...,71,79,99,137,174,50,55,69,97,122
28,COUNTY,4,AK,Alaska,Skagway Municipality,428,195,46,9.84,14.86,...,75,85,106,154,163,50,56,70,102,108
29,COUNTY,4,AK,Alaska,Southeast Fairbanks Census Area,2085,591,28,9.84,26.9,...,68,81,95,139,168,25,29,35,51,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3926,COUNTY,4,WV,West Virginia,Wirt County †,2432,390,16,8.75,Not Provided,...,47,51,61,86,95,Not Provided,Not Provided,Not Provided,Not Provided,Not Provided
3927,COUNTY,4,WV,West Virginia,Wood County,36225,10563,29,8.75,10.25,...,47,51,61,86,95,40,44,52,74,81
3928,COUNTY,4,WV,West Virginia,Wyoming County,9222,1791,19,8.75,12.2,...,47,48,57,82,97,34,34,41,59,70
3929,STATE,1,WY,Wyoming,Does Not Apply,226985,71244,31,7.25,14.25,...,65,71,91,124,151,33,36,46,63,77
3930,NONMETRO,2,WY,Wyoming,Does Not Apply,157201,48348,31,7.25,14.43,...,63,70,90,121,146,32,35,45,61,73
3931,METRO,3,WY,Wyoming,Casper MSA,32422,11124,34,7.25,15.34,...,70,76,92,127,160,33,36,44,60,76
3932,METRO,3,WY,Wyoming,Cheyenne MSA,37362,11772,32,7.25,12.34,...,70,70,94,131,162,41,41,55,77,95
3933,COUNTY,4,WY,Wyoming,Albany County,15565,7959,51,7.25,8.79,...,59,65,84,123,149,49,54,70,101,123
3934,COUNTY,4,WY,Wyoming,Big Horn County,4459,1180,26,7.25,11.05,...,52,56,74,95,130,34,37,49,63,85
3935,COUNTY,4,WY,Wyoming,Campbell County,17534,5293,30,7.25,16.76,...,74,79,104,141,141,32,34,45,61,61
3936,COUNTY,4,WY,Wyoming,Carbon County,6095,1822,30,7.25,20,...,60,64,85,117,128,22,23,31,43,46
3937,COUNTY,4,WY,Wyoming,Converse County,5576,1481,27,7.25,15.55,...,58,61,82,119,134,27,29,38,55,62
3938,COUNTY,4,WY,Wyoming,Crook County,2976,628,21,7.25,17.91,...,60,63,84,106,138,24,26,34,43,56
3939,COUNTY,4,WY,Wyoming,Fremont County,15159,4441,29,7.25,11.79,...,54,65,83,110,123,33,40,51,68,76
3940,COUNTY,4,WY,Wyoming,Goshen County,5350,1266,24,7.25,11.77,...,56,59,78,100,128,34,36,48,62,79
3941,COUNTY,4,WY,Wyoming,Hot Springs County,2262,594,26,7.25,12.79,...,52,58,74,105,126,29,33,42,59,72
3942,COUNTY,4,WY,Wyoming,Johnson County,3668,980,27,7.25,11.59,...,65,69,92,129,151,41,43,58,80,94
3943,COUNTY,4,WY,Wyoming,Laramie County,37362,11772,32,7.25,12.34,...,70,70,94,131,162,41,41,55,77,95
3944,COUNTY,4,WY,Wyoming,Lincoln County,7002,1462,21,7.25,14.07,...,64,68,91,116,131,33,35,47,60,67
3945,COUNTY,4,WY,Wyoming,Natrona County,32422,11124,34,7.25,15.34,...,70,76,92,127,160,33,36,44,60,76
3946,COUNTY,4,WY,Wyoming,Niobrara County †,981,292,30,7.25,Not Provided,...,52,56,74,99,121,Not Provided,Not Provided,Not Provided,Not Provided,Not Provided
3947,COUNTY,4,WY,Wyoming,Park County,11826,3314,28,7.25,12.57,...,58,64,82,104,124,33,37,47,60,72
3948,COUNTY,4,WY,Wyoming,Platte County,3680,904,25,7.25,15.56,...,52,56,74,93,116,24,26,34,43,54
3949,COUNTY,4,WY,Wyoming,Sheridan County,12697,4009,32,7.25,12.03,...,67,72,94,118,166,40,43,57,71,100
3950,COUNTY,4,WY,Wyoming,Sublette County,3203,918,29,7.25,17.3,...,65,79,91,132,149,27,33,38,55,62
3951,COUNTY,4,WY,Wyoming,Sweetwater County,16533,4539,27,7.25,18.93,...,64,74,91,122,160,25,28,35,47,61
3952,COUNTY,4,WY,Wyoming,Teton County,8576,3444,40,7.25,15,...,90,110,126,171,223,43,53,61,83,108
3953,COUNTY,4,WY,Wyoming,Uinta County,7432,2205,30,7.25,10.18,...,55,59,78,106,119,39,42,56,76,85
3954,COUNTY,4,WY,Wyoming,Washakie County,3493,889,25,7.25,11.85,...,52,64,74,108,125,32,39,45,66,77
3955,COUNTY,4,WY,Wyoming,Weston County,3134,728,23,7.25,12.76,...,60,69,84,106,138,34,39,48,60,78

In [151]:
rent_df.count()

Type                                                                   3956
Type Code                                                              3956
ST                                                                     3956
STNAME                                                                 3956
COUNTY/METRO                                                           3956
Total households (2012-2016)                                           3956
Renter households (2012-2016)                                          3956
% of total households that are renters (2012-2016)                     3956
Minimum wage                                                           3956
Estimated mean renter wage                                             3956
SSI monthly payment                                                    3956
Zero bedroom FMR                                                       3956
One bedroom FMR                                                        3956
Two bedroom FMR                                                        3956
Three bedroom FMR                                                      3956
Four bedroom FMR                                                       3956
Annual AMI                                                             3956
30% of AMI                                                             3956
Estimated renter median income                                         3956
Rent affordable at renter median income                                3956
Rent affordable at 30% of AMI                                          3956
Rent affordable with full-time job paying min wage                     3956
Rent affordable with full-time job paying mean renter wage             3956
Rent affordable to SSI recipient                                       3956
Income needed to afford 0 bdrm FMR                                     3956
Income needed to afford 1 bdrm FMR                                     3956
Income needed to afford 2 bdrm FMR                                     3956
Income needed to afford 3 bdrm FMR                                     3956
Income needed to afford 4 bdrm FMR                                     3956
Housing Wage for 0 bdrm FMR                                            3956
Housing Wage for 1 bdrm FMR                                            3956
Housing Wage for 2 bdrm FMR                                            3956
Housing Wage for 3 bdrm FMR                                            3956
Housing Wage for 4 bdrm FMR                                            3956
Work hours per week at min. wage needed to afford 0 bdrm FMR           3956
Work hours per week at min. wage needed to afford 1 bdrm FMR           3956
Work hours per week at min. wage needed to afford 2 bdrm FMR           3956
Work hours per week at min. wage needed to afford 3 bdrm FMR           3956
Work hours per week at min. wage needed to afford 4 bdrm FMR           3956
Work hours per week at mean renter wage needed to afford 0 bdrm FMR    3956
Work hours per week at mean renter wage needed to afford 1 bdrm FMR    3956
Work hours per week at mean renter wage needed to afford 2 bdrm FMR    3956
Work hours per week at mean renter wage needed to afford 3 bdrm FMR    3956
Work hours per week at mean renter wage needed to afford 4 bdrm FMR    3956
dtype: int64

In [153]:
rent_df.to_csv(os.path.join("..","Data","Clean","NLIHC_OOR_2018_Clean.csv"), index=False)

In [178]:
file_consump = pd.read_csv(os.path.join("..","Data","Raw","NIAAA_2017_Alcohol_Consumption_2017.csv"), header = 3)
print(file_consump)

                                           Unnamed: 0     Volume  Ethanol  \
0                                             Alabama     95,387    4,292
1                                              Alaska     14,006      630
2                                             Arizona    142,228    6,400
3                                            Arkansas     50,336    2,265
4                                          California    679,723   30,588
5                                            Colorado    117,582    5,291
6                                         Connecticut     54,948    2,473
7                                            Delaware     20,486      922
8                                   Dist. of Columbia     14,477      651
9                                             Florida    421,631   18,973
10                                            Georgia    183,613    8,263
11                                             Hawaii     33,821    1,522
12                                              Idaho     27,671    1,245
13                                           Illinois    257,845   11,603
14                                            Indiana    117,420    5,284
15                                               Iowa     72,660    3,270
16                                             Kansas     53,915    2,426
17                                           Kentucky     77,010    3,465
18                                          Louisiana    104,780    4,715
19                                              Maine     34,286    1,543
20                                           Maryland     90,649    4,079
21                                      Massachusetts    122,373    5,507
22                                           Michigan    186,717    8,402
23                                          Minnesota    116,097    5,224
24                                        Mississippi     67,642    3,044
25                                           Missouri    127,055    5,717
26                                            Montana     31,229    1,405
27                                           Nebraska     43,245    1,946
28                                             Nevada     75,764    3,409
29                                      New Hampshire     46,996    2,115
30                                         New Jersey    131,936    5,937
31                                         New Mexico     40,147    1,807
32                                           New York    328,659   14,790
33                                     North Carolina    197,559    8,890
34                                       North Dakota     20,614      928
35                                               Ohio    239,227   10,765
36                                           Oklahoma     72,757    3,274
37                                             Oregon     95,424    4,294
38                                       Pennsylvania    309,101   13,910
39                                       Rhode Island     18,566      835
40                                     South Carolina    105,524    4,749
41                                       South Dakota     23,913    1,076
42                                          Tennessee    121,699    5,476
43                                              Texas    636,031   28,621
44                                               Utah     32,023    1,441
45                                            Vermont     18,414      829
46                                           Virginia    150,304    6,764
47                                         Washington    126,914    5,711
48                                      West Virginia     39,866    1,794
49                                          Wisconsin    141,887    6,385
50                                            Wyoming     12,324      555
51                                            Regions        NaN      NaN
52                                          Northeast  1,065,279   47,938
53                                            Midwest  1,400,595   63,027
54                                              South  2,449,752  110,239
55                                               West  1,428,856   64,299
56                                         U.S. total  6,344,482  285,502
57  Decile values (1 = highest) apply only to Stat...        NaN      NaN

    Per capita Volume.1 Ethanol.1  Per capita.1 Volume.2 Ethanol.2  \
0         1.06    8,120     1,048          0.26    6,535     2,686
1         1.06    2,432       314          0.53    1,757       722
2         1.11   17,599     2,270          0.39   11,080     4,554
3         0.92    4,336       559          0.23    3,987     1,639
4         0.94  145,969    18,830          0.58   61,835    25,414
5         1.14   18,485     2,385          0.52   13,402     5,508
6         0.82   14,084     1,817          0.60    7,230     2,971
7         1.15    4,465       576          0.72    3,404     1,399
8         1.10    4,688       605          1.02    2,422       995
9         1.07   72,108     9,302          0.52   44,732    18,385
10        0.97   16,429     2,119          0.25   14,519     5,967
11        1.28    5,318       686          0.58    2,257       928
12        0.91   12,700     1,638          1.19    2,734     1,124
13        1.10   36,749     4,741          0.45   21,398     8,795
14        0.97   12,318     1,589          0.29   11,314     4,650
15        1.27    4,762       614          0.24    5,589     2,297
16        1.03    2,632       340          0.14    4,602     1,891
17        0.94    5,941       766          0.21    7,328     3,012
18        1.23    9,895     1,276          0.33    9,228     3,793
19        1.35    3,917       505          0.44    2,936     1,207
20        0.81   15,450     1,993          0.40   11,210     4,607
21        0.95   29,569     3,814          0.66   13,789     5,667
22        1.01   25,515     3,291          0.40   18,872     7,756
23        1.14   15,588     2,011          0.44   13,152     5,406
24        1.25    3,331       430          0.18    4,591     1,887
25        1.13   15,150     1,954          0.39   12,378     5,087
26        1.61    3,471       448          0.51    2,081       855
27        1.26    2,608       336          0.22    2,720     1,118
28        1.38   11,548     1,490          0.60    8,681     3,568
29        1.84    7,804     1,007          0.88    5,653     2,323
30        0.79   34,074     4,396          0.59   17,267     7,097
31        1.06    3,929       507          0.30    3,382     1,390
32        0.89   68,378     8,821          0.53   31,619    12,995
33        1.05   28,721     3,705          0.44   13,501     5,549
34        1.51    1,600       206          0.34    1,943       799
35        1.11   23,045     2,973          0.31   14,002     5,755
36        1.03    4,839       624          0.20    5,008     2,058
37        1.24   15,955     2,058          0.59    7,838     3,222
38        1.29   27,682     3,571          0.33   18,726     7,696
39        0.93    4,069       525          0.58    2,380       978
40        1.14    8,133     1,049          0.25    8,108     3,332
41        1.54    1,614       208          0.30    1,747       718
42        0.99   13,660     1,762          0.32   10,890     4,476
43        1.27   61,573     7,943          0.35   39,600    16,275
44        0.61    3,661       472          0.20    3,213     1,321
45        1.55    3,323       429          0.80      971       399
46        0.96   26,642     3,437          0.49   11,478     4,717
47        0.93   24,557     3,168          0.52   11,739     4,825
48        1.17    1,294       167          0.11    1,724       708
49        1.33   14,998     1,935          0.40   14,704     6,043
50        1.17    1,157       149          0.32    1,369       563
51         NaN      NaN       NaN           NaN      NaN       NaN
52        1.01  192,900    24,884          0.52  100,571    41,334
53        1.12  156,579    20,199          0.36  122,422    50,315
54        1.09  289,625    37,362          0.37  198,266    81,487
55        1.01  266,780    34,415          0.54  131,368    53,992
56        1.06  905,883   116,859          0.43  552,626   227,129
57         NaN      NaN       NaN           NaN      NaN       NaN

    Per capita.2 Ethanol.3  Per capita.3  U.S. decile
0           0.67     8,026          1.99          9.0
1           1.22     1,666          2.81          3.0
2           0.79    13,224          2.30          6.0
3           0.67     4,463          1.82         10.0
4           0.78    74,832          2.30          6.0
5           1.19    13,184          2.85          3.0
6           0.98     7,261          2.40          5.0
7           1.74     2,897          3.60          1.0
8           1.69     2,252          3.81          1.0
9           1.04    46,660          2.63          4.0
10          0.70    16,349          1.92         10.0
11          0.78     3,136          2.65          4.0
12          0.82     4,007          2.92          2.0
13          0.83    25,138          2.38          5.0
14          0.85    11,523          2.11          8.0
15          0.89     6,181          2.40          5.0
16          0.80     4,657          1.97          9.0
17          0.82     7,244          1.97          9.0
18          0.99     9,784          2.56          5.0
19          1.05     3,255          2.84          3.0
20          0.92    10,680          2.13          8.0
21          0.97    14,988          2.58          4.0
22          0.93    19,450          2.34          6.0
23          1.18    12,641          2.77          3.0
24          0.78     5,360          2.20          7.0
25          1.01    12,759          2.53          5.0
26          0.98     2,708          3.11          2.0
27          0.72     3,401          2.20          7.0
28          1.45     8,467          3.43          1.0
29          2.02     5,445          4.74          1.0
30          0.95    17,429          2.33          6.0
31          0.81     3,703          2.16          8.0
32          0.78    36,606          2.20          7.0
33          0.65    18,144          2.13          8.0
34          1.30     1,933          3.15          1.0
35          0.60    19,493          2.02          9.0
36          0.65     5,957          1.87         10.0
37          0.93     9,574          2.76          3.0
38          0.71    25,177          2.34          6.0
39          1.08     2,339          2.59          4.0
40          0.80     9,130          2.19          7.0
41          1.03     2,002          2.86          2.0
42          0.81    11,714          2.11          9.0
43          0.72    52,840          2.34          6.0
44          0.56     3,234          1.36         10.0
45          0.75     1,656          3.10          2.0
46          0.67    14,918          2.12          8.0
47          0.79    13,704          2.24          7.0
48          0.46     2,669          1.74         10.0
49          1.26    14,363          2.99          2.0
50          1.19     1,266          2.68          4.0
51           NaN       NaN           NaN          NaN
52          0.87   114,156          2.40          NaN
53          0.89   133,541          2.38          NaN
54          0.80   229,088          2.25          NaN
55          0.85   152,705          2.40          NaN
56          0.84   629,490          2.34          NaN
57           NaN       NaN           NaN          NaN

In [179]:
consumption_df = pd.DataFrame(file_consump)
consumption_df

,Unnamed: 0,Volume,Ethanol,Per capita,Volume.1,Ethanol.1,Per capita.1,Volume.2,Ethanol.2,Per capita.2,Ethanol.3,Per capita.3,U.S. decile
0,Alabama,"95,387","4,292",1.06,"8,120","1,048",0.26,"6,535","2,686",0.67,"8,026",1.99,9.0
1,Alaska,"14,006",630,1.06,"2,432",314,0.53,"1,757",722,1.22,"1,666",2.81,3.0
2,Arizona,"142,228","6,400",1.11,"17,599","2,270",0.39,"11,080","4,554",0.79,"13,224",2.30,6.0
3,Arkansas,"50,336","2,265",0.92,"4,336",559,0.23,"3,987","1,639",0.67,"4,463",1.82,10.0
4,California,"679,723","30,588",0.94,"145,969","18,830",0.58,"61,835","25,414",0.78,"74,832",2.30,6.0
5,Colorado,"117,582","5,291",1.14,"18,485","2,385",0.52,"13,402","5,508",1.19,"13,184",2.85,3.0
6,Connecticut,"54,948","2,473",0.82,"14,084","1,817",0.60,"7,230","2,971",0.98,"7,261",2.40,5.0
7,Delaware,"20,486",922,1.15,"4,465",576,0.72,"3,404","1,399",1.74,"2,897",3.60,1.0
8,Dist. of Columbia,"14,477",651,1.10,"4,688",605,1.02,"2,422",995,1.69,"2,252",3.81,1.0
9,Florida,"421,631","18,973",1.07,"72,108","9,302",0.52,"44,732","18,385",1.04,"46,660",2.63,4.0
10,Georgia,"183,613","8,263",0.97,"16,429","2,119",0.25,"14,519","5,967",0.70,"16,349",1.92,10.0
11,Hawaii,"33,821","1,522",1.28,"5,318",686,0.58,"2,257",928,0.78,"3,136",2.65,4.0
12,Idaho,"27,671","1,245",0.91,"12,700","1,638",1.19,"2,734","1,124",0.82,"4,007",2.92,2.0
13,Illinois,"257,845","11,603",1.10,"36,749","4,741",0.45,"21,398","8,795",0.83,"25,138",2.38,5.0
14,Indiana,"117,420","5,284",0.97,"12,318","1,589",0.29,"11,314","4,650",0.85,"11,523",2.11,8.0
15,Iowa,"72,660","3,270",1.27,"4,762",614,0.24,"5,589","2,297",0.89,"6,181",2.40,5.0
16,Kansas,"53,915","2,426",1.03,"2,632",340,0.14,"4,602","1,891",0.80,"4,657",1.97,9.0
17,Kentucky,"77,010","3,465",0.94,"5,941",766,0.21,"7,328","3,012",0.82,"7,244",1.97,9.0
18,Louisiana,"104,780","4,715",1.23,"9,895","1,276",0.33,"9,228","3,793",0.99,"9,784",2.56,5.0
19,Maine,"34,286","1,543",1.35,"3,917",505,0.44,"2,936","1,207",1.05,"3,255",2.84,3.0
20,Maryland,"90,649","4,079",0.81,"15,450","1,993",0.40,"11,210","4,607",0.92,"10,680",2.13,8.0
21,Massachusetts,"122,373","5,507",0.95,"29,569","3,814",0.66,"13,789","5,667",0.97,"14,988",2.58,4.0
22,Michigan,"186,717","8,402",1.01,"25,515","3,291",0.40,"18,872","7,756",0.93,"19,450",2.34,6.0
23,Minnesota,"116,097","5,224",1.14,"15,588","2,011",0.44,"13,152","5,406",1.18,"12,641",2.77,3.0
24,Mississippi,"67,642","3,044",1.25,"3,331",430,0.18,"4,591","1,887",0.78,"5,360",2.20,7.0
25,Missouri,"127,055","5,717",1.13,"15,150","1,954",0.39,"12,378","5,087",1.01,"12,759",2.53,5.0
26,Montana,"31,229","1,405",1.61,"3,471",448,0.51,"2,081",855,0.98,"2,708",3.11,2.0
27,Nebraska,"43,245","1,946",1.26,"2,608",336,0.22,"2,720","1,118",0.72,"3,401",2.20,7.0
28,Nevada,"75,764","3,409",1.38,"11,548","1,490",0.60,"8,681","3,568",1.45,"8,467",3.43,1.0
29,New Hampshire,"46,996","2,115",1.84,"7,804","1,007",0.88,"5,653","2,323",2.02,"5,445",4.74,1.0
30,New Jersey,"131,936","5,937",0.79,"34,074","4,396",0.59,"17,267","7,097",0.95,"17,429",2.33,6.0
31,New Mexico,"40,147","1,807",1.06,"3,929",507,0.30,"3,382","1,390",0.81,"3,703",2.16,8.0
32,New York,"328,659","14,790",0.89,"68,378","8,821",0.53,"31,619","12,995",0.78,"36,606",2.20,7.0
33,North Carolina,"197,559","8,890",1.05,"28,721","3,705",0.44,"13,501","5,549",0.65,"18,144",2.13,8.0
34,North Dakota,"20,614",928,1.51,"1,600",206,0.34,"1,943",799,1.30,"1,933",3.15,1.0
35,Ohio,"239,227","10,765",1.11,"23,045","2,973",0.31,"14,002","5,755",0.60,"19,493",2.02,9.0
36,Oklahoma,"72,757","3,274",1.03,"4,839",624,0.20,"5,008","2,058",0.65,"5,957",1.87,10.0
37,Oregon,"95,424","4,294",1.24,"15,955","2,058",0.59,"7,838","3,222",0.93,"9,574",2.76,3.0
38,Pennsylvania,"309,101","13,910",1.29,"27,682","3,571",0.33,"18,726","7,696",0.71,"25,177",2.34,6.0
39,Rhode Island,"18,566",835,0.93,"4,069",525,0.58,"2,380",978,1.08,"2,339",2.59,4.0
40,South Carolina,"105,524","4,749",1.14,"8,133","1,049",0.25,"8,108","3,332",0.80,"9,130",2.19,7.0
41,South Dakota,"23,913","1,076",1.54,"1,614",208,0.30,"1,747",718,1.03,"2,002",2.86,2.0
42,Tennessee,"121,699","5,476",0.99,"13,660","1,762",0.32,"10,890","4,476",0.81,"11,714",2.11,9.0
43,Texas,"636,031","28,621",1.27,"61,573","7,943",0.35,"39,600","16,275",0.72,"52,840",2.34,6.0
44,Utah,"32,023","1,441",0.61,"3,661",472,0.20,"3,213","1,321",0.56,"3,234",1.36,10.0
45,Vermont,"18,414",829,1.55,"3,323",429,0.80,971,399,0.75,"1,656",3.10,2.0
46,Virginia,"150,304","6,764",0.96,"26,642","3,437",0.49,"11,478","4,717",0.67,"14,918",2.12,8.0
47,Washington,"126,914","5,711",0.93,"24,557","3,168",0.52,"11,739","4,825",0.79,"13,704",2.24,7.0
48,West Virginia,"39,866","1,794",1.17,"1,294",167,0.11,"1,724",708,0.46,"2,669",1.74,10.0
49,Wisconsin,"141,887","6,385",1.33,"14,998","1,935",0.40,"14,704","6,043",1.26,"14,363",2.99,2.0
50,Wyoming,"12,324",555,1.17,"1,157",149,0.32,"1,369",563,1.19,"1,266",2.68,4.0
51,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Northeast,"1,065,279","47,938",1.01,"192,900","24,884",0.52,"100,571","41,334",0.87,"114,156",2.40,NaN
53,Midwest,"1,400,595","63,027",1.12,"156,579","20,199",0.36,"122,422","50,315",0.89,"133,541",2.38,NaN
54,South,"2,449,752","110,239",1.09,"289,625","37,362",0.37,"198,266","81,487",0.80,"229,088",2.25,NaN
55,West,"1,428,856","64,299",1.01,"266,780","34,415",0.54,"131,368","53,992",0.85,"152,705",2.40,NaN
56,U.S. total,"6,344,482","285,502",1.06,"905,883","116,859",0.43,"552,626","227,129",0.84,"629,490",2.34,NaN
57,Decile values (1 = highest) apply only to Stat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [180]:
list(consumption_df.columns.values)

['Unnamed: 0',
 'Volume',
 'Ethanol',
 'Per capita',
 'Volume.1',
 'Ethanol.1',
 'Per capita.1',
 'Volume.2',
 'Ethanol.2',
 'Per capita.2',
 'Ethanol.3',
 'Per capita.3',
 'U.S. decile']

In [181]:
consumption_df.rename(columns = {'Unnamed: 0':'State or Region',
 'Volume' : 'Beer Volume in Thousands of Gallons',
 'Ethanol' : 'Beer Ethanol in Thousands of Gallons',
 'Per capita':'Beer per Capita Consumption in Gallons',
 'Volume.1':'Wine Volume in Thousands of Gallons',
 'Ethanol.1':'Wine Ethanol in Thousands of Gallons',
 'Per capita.1':'Wine per Capita Consumption in Gallons',
 'Volume.2':'Spirits Volume in Thousands of Gallons',
 'Ethanol.2':'Spirits Ethanol in Thousands of Gallons',
 'Per capita.2':'Spirits per Capita Consumption in Gallons',
 'Ethanol.3':'All Beverages Ethanol in Thousands of Gallons',
 'Per capita.3':'All Beverages per Capita Consumption in Gallons'}, inplace = True)
consumption_df

,State or Region,Beer Volume in Thousands of Gallons,Beer Ethanol in Thousands of Gallons,Beer per Capita Consumption in Gallons,Wine Volume in Thousands of Gallons,Wine Ethanol in Thousands of Gallons,Wine per Capita Consumption in Gallons,Spirits Volume in Thousands of Gallons,Spirits Ethanol in Thousands of Gallons,Spirits per Capita Consumption in Gallons,All Beverages Ethanol in Thousands of Gallons,All Beverages per Capita Consumption in Gallons,U.S. decile
0,Alabama,"95,387","4,292",1.06,"8,120","1,048",0.26,"6,535","2,686",0.67,"8,026",1.99,9.0
1,Alaska,"14,006",630,1.06,"2,432",314,0.53,"1,757",722,1.22,"1,666",2.81,3.0
2,Arizona,"142,228","6,400",1.11,"17,599","2,270",0.39,"11,080","4,554",0.79,"13,224",2.30,6.0
3,Arkansas,"50,336","2,265",0.92,"4,336",559,0.23,"3,987","1,639",0.67,"4,463",1.82,10.0
4,California,"679,723","30,588",0.94,"145,969","18,830",0.58,"61,835","25,414",0.78,"74,832",2.30,6.0
5,Colorado,"117,582","5,291",1.14,"18,485","2,385",0.52,"13,402","5,508",1.19,"13,184",2.85,3.0
6,Connecticut,"54,948","2,473",0.82,"14,084","1,817",0.60,"7,230","2,971",0.98,"7,261",2.40,5.0
7,Delaware,"20,486",922,1.15,"4,465",576,0.72,"3,404","1,399",1.74,"2,897",3.60,1.0
8,Dist. of Columbia,"14,477",651,1.10,"4,688",605,1.02,"2,422",995,1.69,"2,252",3.81,1.0
9,Florida,"421,631","18,973",1.07,"72,108","9,302",0.52,"44,732","18,385",1.04,"46,660",2.63,4.0
10,Georgia,"183,613","8,263",0.97,"16,429","2,119",0.25,"14,519","5,967",0.70,"16,349",1.92,10.0
11,Hawaii,"33,821","1,522",1.28,"5,318",686,0.58,"2,257",928,0.78,"3,136",2.65,4.0
12,Idaho,"27,671","1,245",0.91,"12,700","1,638",1.19,"2,734","1,124",0.82,"4,007",2.92,2.0
13,Illinois,"257,845","11,603",1.10,"36,749","4,741",0.45,"21,398","8,795",0.83,"25,138",2.38,5.0
14,Indiana,"117,420","5,284",0.97,"12,318","1,589",0.29,"11,314","4,650",0.85,"11,523",2.11,8.0
15,Iowa,"72,660","3,270",1.27,"4,762",614,0.24,"5,589","2,297",0.89,"6,181",2.40,5.0
16,Kansas,"53,915","2,426",1.03,"2,632",340,0.14,"4,602","1,891",0.80,"4,657",1.97,9.0
17,Kentucky,"77,010","3,465",0.94,"5,941",766,0.21,"7,328","3,012",0.82,"7,244",1.97,9.0
18,Louisiana,"104,780","4,715",1.23,"9,895","1,276",0.33,"9,228","3,793",0.99,"9,784",2.56,5.0
19,Maine,"34,286","1,543",1.35,"3,917",505,0.44,"2,936","1,207",1.05,"3,255",2.84,3.0
20,Maryland,"90,649","4,079",0.81,"15,450","1,993",0.40,"11,210","4,607",0.92,"10,680",2.13,8.0
21,Massachusetts,"122,373","5,507",0.95,"29,569","3,814",0.66,"13,789","5,667",0.97,"14,988",2.58,4.0
22,Michigan,"186,717","8,402",1.01,"25,515","3,291",0.40,"18,872","7,756",0.93,"19,450",2.34,6.0
23,Minnesota,"116,097","5,224",1.14,"15,588","2,011",0.44,"13,152","5,406",1.18,"12,641",2.77,3.0
24,Mississippi,"67,642","3,044",1.25,"3,331",430,0.18,"4,591","1,887",0.78,"5,360",2.20,7.0
25,Missouri,"127,055","5,717",1.13,"15,150","1,954",0.39,"12,378","5,087",1.01,"12,759",2.53,5.0
26,Montana,"31,229","1,405",1.61,"3,471",448,0.51,"2,081",855,0.98,"2,708",3.11,2.0
27,Nebraska,"43,245","1,946",1.26,"2,608",336,0.22,"2,720","1,118",0.72,"3,401",2.20,7.0
28,Nevada,"75,764","3,409",1.38,"11,548","1,490",0.60,"8,681","3,568",1.45,"8,467",3.43,1.0
29,New Hampshire,"46,996","2,115",1.84,"7,804","1,007",0.88,"5,653","2,323",2.02,"5,445",4.74,1.0
30,New Jersey,"131,936","5,937",0.79,"34,074","4,396",0.59,"17,267","7,097",0.95,"17,429",2.33,6.0
31,New Mexico,"40,147","1,807",1.06,"3,929",507,0.30,"3,382","1,390",0.81,"3,703",2.16,8.0
32,New York,"328,659","14,790",0.89,"68,378","8,821",0.53,"31,619","12,995",0.78,"36,606",2.20,7.0
33,North Carolina,"197,559","8,890",1.05,"28,721","3,705",0.44,"13,501","5,549",0.65,"18,144",2.13,8.0
34,North Dakota,"20,614",928,1.51,"1,600",206,0.34,"1,943",799,1.30,"1,933",3.15,1.0
35,Ohio,"239,227","10,765",1.11,"23,045","2,973",0.31,"14,002","5,755",0.60,"19,493",2.02,9.0
36,Oklahoma,"72,757","3,274",1.03,"4,839",624,0.20,"5,008","2,058",0.65,"5,957",1.87,10.0
37,Oregon,"95,424","4,294",1.24,"15,955","2,058",0.59,"7,838","3,222",0.93,"9,574",2.76,3.0
38,Pennsylvania,"309,101","13,910",1.29,"27,682","3,571",0.33,"18,726","7,696",0.71,"25,177",2.34,6.0
39,Rhode Island,"18,566",835,0.93,"4,069",525,0.58,"2,380",978,1.08,"2,339",2.59,4.0
40,South Carolina,"105,524","4,749",1.14,"8,133","1,049",0.25,"8,108","3,332",0.80,"9,130",2.19,7.0
41,South Dakota,"23,913","1,076",1.54,"1,614",208,0.30,"1,747",718,1.03,"2,002",2.86,2.0
42,Tennessee,"121,699","5,476",0.99,"13,660","1,762",0.32,"10,890","4,476",0.81,"11,714",2.11,9.0
43,Texas,"636,031","28,621",1.27,"61,573","7,943",0.35,"39,600","16,275",0.72,"52,840",2.34,6.0
44,Utah,"32,023","1,441",0.61,"3,661",472,0.20,"3,213","1,321",0.56,"3,234",1.36,10.0
45,Vermont,"18,414",829,1.55,"3,323",429,0.80,971,399,0.75,"1,656",3.10,2.0
46,Virginia,"150,304","6,764",0.96,"26,642","3,437",0.49,"11,478","4,717",0.67,"14,918",2.12,8.0
47,Washington,"126,914","5,711",0.93,"24,557","3,168",0.52,"11,739","4,825",0.79,"13,704",2.24,7.0
48,West Virginia,"39,866","1,794",1.17,"1,294",167,0.11,"1,724",708,0.46,"2,669",1.74,10.0
49,Wisconsin,"141,887","6,385",1.33,"14,998","1,935",0.40,"14,704","6,043",1.26,"14,363",2.99,2.0
50,Wyoming,"12,324",555,1.17,"1,157",149,0.32,"1,369",563,1.19,"1,266",2.68,4.0
51,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Northeast,"1,065,279","47,938",1.01,"192,900","24,884",0.52,"100,571","41,334",0.87,"114,156",2.40,NaN
53,Midwest,"1,400,595","63,027",1.12,"156,579","20,199",0.36,"122,422","50,315",0.89,"133,541",2.38,NaN
54,South,"2,449,752","110,239",1.09,"289,625","37,362",0.37,"198,266","81,487",0.80,"229,088",2.25,NaN
55,West,"1,428,856","64,299",1.01,"266,780","34,415",0.54,"131,368","53,992",0.85,"152,705",2.40,NaN
56,U.S. total,"6,344,482","285,502",1.06,"905,883","116,859",0.43,"552,626","227,129",0.84,"629,490",2.34,NaN
57,Decile values (1 = highest) apply only to Stat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [182]:
consumption_df = consumption_df[:-1]
consumption_df

,State or Region,Beer Volume in Thousands of Gallons,Beer Ethanol in Thousands of Gallons,Beer per Capita Consumption in Gallons,Wine Volume in Thousands of Gallons,Wine Ethanol in Thousands of Gallons,Wine per Capita Consumption in Gallons,Spirits Volume in Thousands of Gallons,Spirits Ethanol in Thousands of Gallons,Spirits per Capita Consumption in Gallons,All Beverages Ethanol in Thousands of Gallons,All Beverages per Capita Consumption in Gallons,U.S. decile
0,Alabama,"95,387","4,292",1.06,"8,120","1,048",0.26,"6,535","2,686",0.67,"8,026",1.99,9.0
1,Alaska,"14,006",630,1.06,"2,432",314,0.53,"1,757",722,1.22,"1,666",2.81,3.0
2,Arizona,"142,228","6,400",1.11,"17,599","2,270",0.39,"11,080","4,554",0.79,"13,224",2.30,6.0
3,Arkansas,"50,336","2,265",0.92,"4,336",559,0.23,"3,987","1,639",0.67,"4,463",1.82,10.0
4,California,"679,723","30,588",0.94,"145,969","18,830",0.58,"61,835","25,414",0.78,"74,832",2.30,6.0
5,Colorado,"117,582","5,291",1.14,"18,485","2,385",0.52,"13,402","5,508",1.19,"13,184",2.85,3.0
6,Connecticut,"54,948","2,473",0.82,"14,084","1,817",0.60,"7,230","2,971",0.98,"7,261",2.40,5.0
7,Delaware,"20,486",922,1.15,"4,465",576,0.72,"3,404","1,399",1.74,"2,897",3.60,1.0
8,Dist. of Columbia,"14,477",651,1.10,"4,688",605,1.02,"2,422",995,1.69,"2,252",3.81,1.0
9,Florida,"421,631","18,973",1.07,"72,108","9,302",0.52,"44,732","18,385",1.04,"46,660",2.63,4.0
10,Georgia,"183,613","8,263",0.97,"16,429","2,119",0.25,"14,519","5,967",0.70,"16,349",1.92,10.0
11,Hawaii,"33,821","1,522",1.28,"5,318",686,0.58,"2,257",928,0.78,"3,136",2.65,4.0
12,Idaho,"27,671","1,245",0.91,"12,700","1,638",1.19,"2,734","1,124",0.82,"4,007",2.92,2.0
13,Illinois,"257,845","11,603",1.10,"36,749","4,741",0.45,"21,398","8,795",0.83,"25,138",2.38,5.0
14,Indiana,"117,420","5,284",0.97,"12,318","1,589",0.29,"11,314","4,650",0.85,"11,523",2.11,8.0
15,Iowa,"72,660","3,270",1.27,"4,762",614,0.24,"5,589","2,297",0.89,"6,181",2.40,5.0
16,Kansas,"53,915","2,426",1.03,"2,632",340,0.14,"4,602","1,891",0.80,"4,657",1.97,9.0
17,Kentucky,"77,010","3,465",0.94,"5,941",766,0.21,"7,328","3,012",0.82,"7,244",1.97,9.0
18,Louisiana,"104,780","4,715",1.23,"9,895","1,276",0.33,"9,228","3,793",0.99,"9,784",2.56,5.0
19,Maine,"34,286","1,543",1.35,"3,917",505,0.44,"2,936","1,207",1.05,"3,255",2.84,3.0
20,Maryland,"90,649","4,079",0.81,"15,450","1,993",0.40,"11,210","4,607",0.92,"10,680",2.13,8.0
21,Massachusetts,"122,373","5,507",0.95,"29,569","3,814",0.66,"13,789","5,667",0.97,"14,988",2.58,4.0
22,Michigan,"186,717","8,402",1.01,"25,515","3,291",0.40,"18,872","7,756",0.93,"19,450",2.34,6.0
23,Minnesota,"116,097","5,224",1.14,"15,588","2,011",0.44,"13,152","5,406",1.18,"12,641",2.77,3.0
24,Mississippi,"67,642","3,044",1.25,"3,331",430,0.18,"4,591","1,887",0.78,"5,360",2.20,7.0
25,Missouri,"127,055","5,717",1.13,"15,150","1,954",0.39,"12,378","5,087",1.01,"12,759",2.53,5.0
26,Montana,"31,229","1,405",1.61,"3,471",448,0.51,"2,081",855,0.98,"2,708",3.11,2.0
27,Nebraska,"43,245","1,946",1.26,"2,608",336,0.22,"2,720","1,118",0.72,"3,401",2.20,7.0
28,Nevada,"75,764","3,409",1.38,"11,548","1,490",0.60,"8,681","3,568",1.45,"8,467",3.43,1.0
29,New Hampshire,"46,996","2,115",1.84,"7,804","1,007",0.88,"5,653","2,323",2.02,"5,445",4.74,1.0
30,New Jersey,"131,936","5,937",0.79,"34,074","4,396",0.59,"17,267","7,097",0.95,"17,429",2.33,6.0
31,New Mexico,"40,147","1,807",1.06,"3,929",507,0.30,"3,382","1,390",0.81,"3,703",2.16,8.0
32,New York,"328,659","14,790",0.89,"68,378","8,821",0.53,"31,619","12,995",0.78,"36,606",2.20,7.0
33,North Carolina,"197,559","8,890",1.05,"28,721","3,705",0.44,"13,501","5,549",0.65,"18,144",2.13,8.0
34,North Dakota,"20,614",928,1.51,"1,600",206,0.34,"1,943",799,1.30,"1,933",3.15,1.0
35,Ohio,"239,227","10,765",1.11,"23,045","2,973",0.31,"14,002","5,755",0.60,"19,493",2.02,9.0
36,Oklahoma,"72,757","3,274",1.03,"4,839",624,0.20,"5,008","2,058",0.65,"5,957",1.87,10.0
37,Oregon,"95,424","4,294",1.24,"15,955","2,058",0.59,"7,838","3,222",0.93,"9,574",2.76,3.0
38,Pennsylvania,"309,101","13,910",1.29,"27,682","3,571",0.33,"18,726","7,696",0.71,"25,177",2.34,6.0
39,Rhode Island,"18,566",835,0.93,"4,069",525,0.58,"2,380",978,1.08,"2,339",2.59,4.0
40,South Carolina,"105,524","4,749",1.14,"8,133","1,049",0.25,"8,108","3,332",0.80,"9,130",2.19,7.0
41,South Dakota,"23,913","1,076",1.54,"1,614",208,0.30,"1,747",718,1.03,"2,002",2.86,2.0
42,Tennessee,"121,699","5,476",0.99,"13,660","1,762",0.32,"10,890","4,476",0.81,"11,714",2.11,9.0
43,Texas,"636,031","28,621",1.27,"61,573","7,943",0.35,"39,600","16,275",0.72,"52,840",2.34,6.0
44,Utah,"32,023","1,441",0.61,"3,661",472,0.20,"3,213","1,321",0.56,"3,234",1.36,10.0
45,Vermont,"18,414",829,1.55,"3,323",429,0.80,971,399,0.75,"1,656",3.10,2.0
46,Virginia,"150,304","6,764",0.96,"26,642","3,437",0.49,"11,478","4,717",0.67,"14,918",2.12,8.0
47,Washington,"126,914","5,711",0.93,"24,557","3,168",0.52,"11,739","4,825",0.79,"13,704",2.24,7.0
48,West Virginia,"39,866","1,794",1.17,"1,294",167,0.11,"1,724",708,0.46,"2,669",1.74,10.0
49,Wisconsin,"141,887","6,385",1.33,"14,998","1,935",0.40,"14,704","6,043",1.26,"14,363",2.99,2.0
50,Wyoming,"12,324",555,1.17,"1,157",149,0.32,"1,369",563,1.19,"1,266",2.68,4.0
51,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Northeast,"1,065,279","47,938",1.01,"192,900","24,884",0.52,"100,571","41,334",0.87,"114,156",2.40,NaN
53,Midwest,"1,400,595","63,027",1.12,"156,579","20,199",0.36,"122,422","50,315",0.89,"133,541",2.38,NaN
54,South,"2,449,752","110,239",1.09,"289,625","37,362",0.37,"198,266","81,487",0.80,"229,088",2.25,NaN
55,West,"1,428,856","64,299",1.01,"266,780","34,415",0.54,"131,368","53,992",0.85,"152,705",2.40,NaN
56,U.S. total,"6,344,482","285,502",1.06,"905,883","116,859",0.43,"552,626","227,129",0.84,"629,490",2.34,NaN

In [183]:
# consumption_df.count()
# consumption_df.isnull().any()
consumption_df.loc[consumption_df.isnull().any(axis=1)]

,State or Region,Beer Volume in Thousands of Gallons,Beer Ethanol in Thousands of Gallons,Beer per Capita Consumption in Gallons,Wine Volume in Thousands of Gallons,Wine Ethanol in Thousands of Gallons,Wine per Capita Consumption in Gallons,Spirits Volume in Thousands of Gallons,Spirits Ethanol in Thousands of Gallons,Spirits per Capita Consumption in Gallons,All Beverages Ethanol in Thousands of Gallons,All Beverages per Capita Consumption in Gallons,U.S. decile
51,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Northeast,"1,065,279","47,938",1.01,"192,900","24,884",0.52,"100,571","41,334",0.87,"114,156",2.40,NaN
53,Midwest,"1,400,595","63,027",1.12,"156,579","20,199",0.36,"122,422","50,315",0.89,"133,541",2.38,NaN
54,South,"2,449,752","110,239",1.09,"289,625","37,362",0.37,"198,266","81,487",0.80,"229,088",2.25,NaN
55,West,"1,428,856","64,299",1.01,"266,780","34,415",0.54,"131,368","53,992",0.85,"152,705",2.40,NaN
56,U.S. total,"6,344,482","285,502",1.06,"905,883","116,859",0.43,"552,626","227,129",0.84,"629,490",2.34,NaN

In [184]:
consumption_df = consumption_df.drop(consumption_df.index[51])
# consumption_df.count()
consumption_df.loc[consumption_df.isnull().any(axis=1)]

,State or Region,Beer Volume in Thousands of Gallons,Beer Ethanol in Thousands of Gallons,Beer per Capita Consumption in Gallons,Wine Volume in Thousands of Gallons,Wine Ethanol in Thousands of Gallons,Wine per Capita Consumption in Gallons,Spirits Volume in Thousands of Gallons,Spirits Ethanol in Thousands of Gallons,Spirits per Capita Consumption in Gallons,All Beverages Ethanol in Thousands of Gallons,All Beverages per Capita Consumption in Gallons,U.S. decile
52,Northeast,"1,065,279","47,938",1.01,"192,900","24,884",0.52,"100,571","41,334",0.87,"114,156",2.40,NaN
53,Midwest,"1,400,595","63,027",1.12,"156,579","20,199",0.36,"122,422","50,315",0.89,"133,541",2.38,NaN
54,South,"2,449,752","110,239",1.09,"289,625","37,362",0.37,"198,266","81,487",0.80,"229,088",2.25,NaN
55,West,"1,428,856","64,299",1.01,"266,780","34,415",0.54,"131,368","53,992",0.85,"152,705",2.40,NaN
56,U.S. total,"6,344,482","285,502",1.06,"905,883","116,859",0.43,"552,626","227,129",0.84,"629,490",2.34,NaN

In [185]:
consumption_df.fillna(value = 0, inplace = True)
consumption_df.count()

State or Region                                    56
Beer Volume in Thousands of Gallons                56
Beer Ethanol in Thousands of Gallons               56
Beer per Capita Consumption in Gallons             56
Wine Volume in Thousands of Gallons                56
Wine Ethanol in Thousands of Gallons               56
Wine per Capita Consumption in Gallons             56
Spirits Volume in Thousands of Gallons             56
Spirits Ethanol in Thousands of Gallons            56
Spirits per Capita Consumption in Gallons          56
All Beverages Ethanol in Thousands of Gallons      56
All Beverages per Capita Consumption in Gallons    56
U.S. decile                                        56
dtype: int64

In [186]:
consumption_df

,State or Region,Beer Volume in Thousands of Gallons,Beer Ethanol in Thousands of Gallons,Beer per Capita Consumption in Gallons,Wine Volume in Thousands of Gallons,Wine Ethanol in Thousands of Gallons,Wine per Capita Consumption in Gallons,Spirits Volume in Thousands of Gallons,Spirits Ethanol in Thousands of Gallons,Spirits per Capita Consumption in Gallons,All Beverages Ethanol in Thousands of Gallons,All Beverages per Capita Consumption in Gallons,U.S. decile
0,Alabama,"95,387","4,292",1.06,"8,120","1,048",0.26,"6,535","2,686",0.67,"8,026",1.99,9.0
1,Alaska,"14,006",630,1.06,"2,432",314,0.53,"1,757",722,1.22,"1,666",2.81,3.0
2,Arizona,"142,228","6,400",1.11,"17,599","2,270",0.39,"11,080","4,554",0.79,"13,224",2.30,6.0
3,Arkansas,"50,336","2,265",0.92,"4,336",559,0.23,"3,987","1,639",0.67,"4,463",1.82,10.0
4,California,"679,723","30,588",0.94,"145,969","18,830",0.58,"61,835","25,414",0.78,"74,832",2.30,6.0
5,Colorado,"117,582","5,291",1.14,"18,485","2,385",0.52,"13,402","5,508",1.19,"13,184",2.85,3.0
6,Connecticut,"54,948","2,473",0.82,"14,084","1,817",0.60,"7,230","2,971",0.98,"7,261",2.40,5.0
7,Delaware,"20,486",922,1.15,"4,465",576,0.72,"3,404","1,399",1.74,"2,897",3.60,1.0
8,Dist. of Columbia,"14,477",651,1.10,"4,688",605,1.02,"2,422",995,1.69,"2,252",3.81,1.0
9,Florida,"421,631","18,973",1.07,"72,108","9,302",0.52,"44,732","18,385",1.04,"46,660",2.63,4.0
10,Georgia,"183,613","8,263",0.97,"16,429","2,119",0.25,"14,519","5,967",0.70,"16,349",1.92,10.0
11,Hawaii,"33,821","1,522",1.28,"5,318",686,0.58,"2,257",928,0.78,"3,136",2.65,4.0
12,Idaho,"27,671","1,245",0.91,"12,700","1,638",1.19,"2,734","1,124",0.82,"4,007",2.92,2.0
13,Illinois,"257,845","11,603",1.10,"36,749","4,741",0.45,"21,398","8,795",0.83,"25,138",2.38,5.0
14,Indiana,"117,420","5,284",0.97,"12,318","1,589",0.29,"11,314","4,650",0.85,"11,523",2.11,8.0
15,Iowa,"72,660","3,270",1.27,"4,762",614,0.24,"5,589","2,297",0.89,"6,181",2.40,5.0
16,Kansas,"53,915","2,426",1.03,"2,632",340,0.14,"4,602","1,891",0.80,"4,657",1.97,9.0
17,Kentucky,"77,010","3,465",0.94,"5,941",766,0.21,"7,328","3,012",0.82,"7,244",1.97,9.0
18,Louisiana,"104,780","4,715",1.23,"9,895","1,276",0.33,"9,228","3,793",0.99,"9,784",2.56,5.0
19,Maine,"34,286","1,543",1.35,"3,917",505,0.44,"2,936","1,207",1.05,"3,255",2.84,3.0
20,Maryland,"90,649","4,079",0.81,"15,450","1,993",0.40,"11,210","4,607",0.92,"10,680",2.13,8.0
21,Massachusetts,"122,373","5,507",0.95,"29,569","3,814",0.66,"13,789","5,667",0.97,"14,988",2.58,4.0
22,Michigan,"186,717","8,402",1.01,"25,515","3,291",0.40,"18,872","7,756",0.93,"19,450",2.34,6.0
23,Minnesota,"116,097","5,224",1.14,"15,588","2,011",0.44,"13,152","5,406",1.18,"12,641",2.77,3.0
24,Mississippi,"67,642","3,044",1.25,"3,331",430,0.18,"4,591","1,887",0.78,"5,360",2.20,7.0
25,Missouri,"127,055","5,717",1.13,"15,150","1,954",0.39,"12,378","5,087",1.01,"12,759",2.53,5.0
26,Montana,"31,229","1,405",1.61,"3,471",448,0.51,"2,081",855,0.98,"2,708",3.11,2.0
27,Nebraska,"43,245","1,946",1.26,"2,608",336,0.22,"2,720","1,118",0.72,"3,401",2.20,7.0
28,Nevada,"75,764","3,409",1.38,"11,548","1,490",0.60,"8,681","3,568",1.45,"8,467",3.43,1.0
29,New Hampshire,"46,996","2,115",1.84,"7,804","1,007",0.88,"5,653","2,323",2.02,"5,445",4.74,1.0
30,New Jersey,"131,936","5,937",0.79,"34,074","4,396",0.59,"17,267","7,097",0.95,"17,429",2.33,6.0
31,New Mexico,"40,147","1,807",1.06,"3,929",507,0.30,"3,382","1,390",0.81,"3,703",2.16,8.0
32,New York,"328,659","14,790",0.89,"68,378","8,821",0.53,"31,619","12,995",0.78,"36,606",2.20,7.0
33,North Carolina,"197,559","8,890",1.05,"28,721","3,705",0.44,"13,501","5,549",0.65,"18,144",2.13,8.0
34,North Dakota,"20,614",928,1.51,"1,600",206,0.34,"1,943",799,1.30,"1,933",3.15,1.0
35,Ohio,"239,227","10,765",1.11,"23,045","2,973",0.31,"14,002","5,755",0.60,"19,493",2.02,9.0
36,Oklahoma,"72,757","3,274",1.03,"4,839",624,0.20,"5,008","2,058",0.65,"5,957",1.87,10.0
37,Oregon,"95,424","4,294",1.24,"15,955","2,058",0.59,"7,838","3,222",0.93,"9,574",2.76,3.0
38,Pennsylvania,"309,101","13,910",1.29,"27,682","3,571",0.33,"18,726","7,696",0.71,"25,177",2.34,6.0
39,Rhode Island,"18,566",835,0.93,"4,069",525,0.58,"2,380",978,1.08,"2,339",2.59,4.0
40,South Carolina,"105,524","4,749",1.14,"8,133","1,049",0.25,"8,108","3,332",0.80,"9,130",2.19,7.0
41,South Dakota,"23,913","1,076",1.54,"1,614",208,0.30,"1,747",718,1.03,"2,002",2.86,2.0
42,Tennessee,"121,699","5,476",0.99,"13,660","1,762",0.32,"10,890","4,476",0.81,"11,714",2.11,9.0
43,Texas,"636,031","28,621",1.27,"61,573","7,943",0.35,"39,600","16,275",0.72,"52,840",2.34,6.0
44,Utah,"32,023","1,441",0.61,"3,661",472,0.20,"3,213","1,321",0.56,"3,234",1.36,10.0
45,Vermont,"18,414",829,1.55,"3,323",429,0.80,971,399,0.75,"1,656",3.10,2.0
46,Virginia,"150,304","6,764",0.96,"26,642","3,437",0.49,"11,478","4,717",0.67,"14,918",2.12,8.0
47,Washington,"126,914","5,711",0.93,"24,557","3,168",0.52,"11,739","4,825",0.79,"13,704",2.24,7.0
48,West Virginia,"39,866","1,794",1.17,"1,294",167,0.11,"1,724",708,0.46,"2,669",1.74,10.0
49,Wisconsin,"141,887","6,385",1.33,"14,998","1,935",0.40,"14,704","6,043",1.26,"14,363",2.99,2.0
50,Wyoming,"12,324",555,1.17,"1,157",149,0.32,"1,369",563,1.19,"1,266",2.68,4.0
52,Northeast,"1,065,279","47,938",1.01,"192,900","24,884",0.52,"100,571","41,334",0.87,"114,156",2.40,0.0
53,Midwest,"1,400,595","63,027",1.12,"156,579","20,199",0.36,"122,422","50,315",0.89,"133,541",2.38,0.0
54,South,"2,449,752","110,239",1.09,"289,625","37,362",0.37,"198,266","81,487",0.80,"229,088",2.25,0.0
55,West,"1,428,856","64,299",1.01,"266,780","34,415",0.54,"131,368","53,992",0.85,"152,705",2.40,0.0
56,U.S. total,"6,344,482","285,502",1.06,"905,883","116,859",0.43,"552,626","227,129",0.84,"629,490",2.34,0.0

In [ ]:
consumption_df.to_csv(os.path.join("..","Data","Clean",""))